### ISSUE TITLE
Discarding outermost pixels

### ISSUE THREAD

**Issue by vineetbansal** [ComputationalCryoEM/ASPIRE-Python#1]
The paper suggests `..we discard the 100 outermost pixels.`, but the following snippet discards 99 pixels from the top and left, and 100 pixels from the bottom and right, reducing a 4096x4096 image to 3897x3897 in size.

https://github.com/ComputationalCryoEM/aspyre/blob/c4f34a170d1dcc681356cbac319ee09f3774cfa6/src/aspyre/apple/picking.py#L53

The margins will be moved to the config.json file soon, and if/when this is corrected, the unit tests would have to be rewritten to pick the updated centers. At that point this can be closed.

**Comment by ayeletheimowitz** [comment]
So long as 
https://github.com/ComputationalCryoEM/aspyre/blob/c4f34a170d1dcc681356cbac319ee09f3774cfa6/src/aspyre/apple/picking.py#L53

and 
https://github.com/ComputationalCryoEM/aspyre/blob/c4f34a170d1dcc681356cbac319ee09f3774cfa6/src/aspyre/apple/picking.py#L288

are consistent, it doesn't matter if we use 99 pixels or 100.

**Comment by garrettwrong** [comment]
Cool, I think we can close this then. Thank you!
