### ISSUE TITLE
FFB `filter_to_basis_mat` not commuting with filtering

### ISSUE THREAD

**Issue by janden** [ComputationalCryoEM/ASPIRE-Python#1016]
I'm not sure this suggestion is working for FFB.  I'll bring it up later.

       The function for FFB has not ever been unit tested outside of its use in cov2d (same as this was being tested upsteam).

_Originally posted by @garrettwrong in https://github.com/ComputationalCryoEM/ASPIRE-Python/pull/991#discussion_r1324636734_

We should take a look at this to make sure that multiplication by the matrix return from `filter_to_basis_mat` is equivalent to running `evaluate`, `filter`, then `expand`.

**Comment by garrettwrong** [comment]
It appears that filter to basis mat is probably not working as intended for either FB or FFB, or I am grossly misunderstanding.

It should be the case that only very minor adjustment (array transpose and/or converging some variable names) would allow the code to work for both of those basis.  I'm hoping improving the action of this method might lead to the FB case "just working" ™️  too.  

It is sort of surprising cov2d works as well as it does atm given what I am seeing with an `IdentifyFilter`...

**Comment by janden** [comment]
Hmm ok. I'm starting to wonder what `filter_to_basis_mat` actually does then. Could you post a code sample?

**Comment by garrettwrong** [comment]
Sure, this is one of the quick scripts I was tinkering with.

```
import numpy as np
from aspire.source import Simulation
from aspire.image import Image
from aspire.basis import FBBasis2D, FFBBasis2D, Coef
from aspire.operators import IdentityFilter, RadialCTFFilter, DiagMatrix

L=64

fb = FBBasis2D(L)
ffb = FFBBasis2D(L)

#filt = IdentityFilter()
filt = RadialCTFFilter(pixel_size=1)

sim = Simulation(L,C=1,n=1)
imgs = sim.images[:]
#imgs.show()


for basis in (fb, ffb):
    # generate some coefficients
    coef = basis.expand(imgs)

    # filter to basis mat
    coef_ftbm = Coef(basis, np.diag(DiagMatrix(coef.asnumpy()[0]).dense() @  basis.filter_to_basis_mat(filt).dense()))

    # evaluate -> filter -> expand
    _imgs = coef.evaluate()
    imgs2 = _imgs.filter(filt)
    coef2 = basis.expand(imgs2)
    #coef2 = basis.evaluate_t(imgs2)

    # compare coefs from using ftbm operator with coef from eval->filter->exp
    rmse = np.sqrt(np.mean((coef2-coef_ftbm).asnumpy()**2))
    print(f"{basis}.filter_to_basis_mat vs eval filter expand", rmse)

    # # compare with base image coef (only useful for Id filter)
    # rmse = np.sqrt(np.mean((coef2-coef).asnumpy()**2))
    # print(f"{basis} eval filter expand vs base image coef", rmse)

    # # compare with base image coef (only useful for Id filter)
    # rmse = np.sqrt(np.mean((coef_ftbm-coef).asnumpy()**2))
    # print(f"{basis}.filter_to_basis_mat vs base image coef", rmse)
```

Probably easier to discuss verbally in our meeting, but two main things are i) current filter to fb/basis mat implementation in python doesn't look much like the one from MATALB (to my eyes) ii) if i use a hacked eval filter expand approach, cov2d with FB seems to work okay (nice), but then breaks cov2d using FFB....  Before I left for vacation I was looking for some baked in normalization etc that did not agree and started resuming that a few days ago.

**Comment by janden** [comment]
I can't quite follow what's happening here:
```
coef_ftbm = Coef(basis, np.diag(DiagMatrix(coef.asnumpy()[0]).dense() @  basis.filter_to_basis_mat(filt).dense()))
```
Why are we creating a diagonal matrix from the coefficients? Shouldn't it be something more like
```
coef_ftbm = Coef(basis, basis.filter_to_basis_mat(filt) @ coef.asnumpy()))
```
?

**Comment by garrettwrong** [comment]
basis.filter_to_basis_mat(filt) is returning a blk diagonal (except in some upstream code I had for FLE basis).

Regardless, I'm not sure it matters how it is applied (I also used `apply`) the results seemed the same.

**Comment by garrettwrong** [comment]
eg,

coef_ftbm = basis.filter_to_basis_mat(filt).apply(coef.asnumpy()[0])

**Comment by garrettwrong** [comment]
Tests have been added comparing ftbm with manual contstruction for `IdentityFilter` and `RadialCTFFilter` in #1031 .  Each test includes the current accuracy achieved as of writing for relevant basis classes.  They can be incrementally improved as needed from here.

Closing.
