### ISSUE TITLE
3D Reconstruction from Relion Star File Produces Ball-like Volume in ASPIRE

### ISSUE THREAD

**Issue by phonchi** [ComputationalCryoEM/ASPIRE-Python#1026]
Dear ASPIRE Developers,

I am working with a star file generated from Relion and am trying to utilize the methods provided by ASPIRE. To ensure that the conversion from Relion to ASPIRE is correct, especially regarding CTF and Orientations, I first attempted to reconstruct the 3D volume using ASPIRE's `MeanEstimator` using the star file from Relion. However, the resulting volume appears as a ball-like blob in Chimera. The following is the test data generation process (volume is from [https://github.com/ComputationalCryoEM/ASPIRE-Python/blob/main/gallery/tutorials/data/clean70SRibosome_vol_65p.mrc](https://github.com/ComputationalCryoEM/ASPIRE-Python/blob/main/gallery/tutorials/data/clean70SRibosome_vol_65p.mrc))

**Star File Generation Process (Relion):**
```bash
relion_project --i clean70SRibosome_vol_65p.mrc --nr_uniform 3000 --angpix 5 
relion_star_handler --i proj.star --add_column rlnDefocusU --add_column_value 21580.0
relion_star_handler --i out.star --add_column rlnDefocusV --add_column_value 21580.0
relion_star_handler --i out.star --add_column rlnDefocusAngle --add_column_value 0.0
relion_project --i clean70SRibosome_vol_65p.mrc --ang out.star --ctf
```
Then I manually add `_rlnAmplitudeContrast` (with value 0.15) to the `proj.star` file. (The file is available here: [https://drive.google.com/drive/folders/1fATzVomr5Q2oe-eNAlGbnQULDH5UXRe8?usp=sharing](https://drive.google.com/drive/folders/1fATzVomr5Q2oe-eNAlGbnQULDH5UXRe8?usp=sharing))

**Reconstruction Process (Relion):**
```bash
relion_reconstruct --i proj.star --angpix 5 --ctf
```
The volume generated by Relion seems reasonable. Then I switch to ASPIRE as follows:

**Reconstruction Process (ASPIRE):**
```python
import os

import matplotlib.pyplot as plt
import numpy as np

from aspire.basis import FBBasis3D
from aspire.noise import AnisotropicNoiseEstimator
from aspire.reconstruction import MeanEstimator
from aspire.source import RelionSource

data_folder = "/home/user"
file_path = "/home/user/proj.star"

source = RelionSource(
    file_path,
    pixel_size=5,
    max_rows=10000,
    data_folder=data_folder,
)

# Reduce the resolution
L = 32  
source = source.downsample(L)

#source = source.phase_flip()
noise_estimator = AnisotropicNoiseEstimator(source)
source = source.whiten(noise_estimator)
# We'll create a 3D Fourier Bessel Basis corresponding to volume resolution L.
basis = FBBasis3D((L, L, L))
# Estimate mean Volume
mean_estimator = MeanEstimator(source, basis, batch_size=8192)
mean_est = mean_estimator.estimate()

vol = mean_est.asnumpy()[0]
# Visualize volume
L = vol.shape[0]
# Plots
plt.suptitle("Orthogonal Projections", size=20)
plt.subplot(1, 3, 1, title="x-axis")
plt.imshow(np.sum(vol, axis=0), cmap="gray")
plt.subplot(1, 3, 2, title="y-axis")
plt.imshow(np.sum(vol, axis=1), cmap="gray")
plt.subplot(1, 3, 3, title="z-axis")
plt.imshow(np.sum(vol, axis=2), cmap="gray")
plt.tight_layout()
plt.subplots_adjust(top=1.25)
plt.show()

mean_est.save('aspire.mrc', overwrite=True)
```
Orthogonal projections are also attached ![aspire1](https://github.com/ComputationalCryoEM/ASPIRE-Python/assets/11373055/7ef2e7c7-2103-4f2b-a3e0-d4d10695f773)).

I've tried four different preprocessing methods:
1. No preprocessing.
2. Whitening (as shown in the code).
3. Phase flip.
4. Phase flip followed by whitening.

All methods produce a similar ball-like blob. I'm wondering if I should:
- Increase the resolution (currently `L=32`).
- Use more images (currently `n=3000`).
- Try a different preprocessing pipeline.
- Or adjust other parts of the code?

**Environment:**
- ASPIRE version: 0.12.0
- OS: Ubuntu 20.04.6

Any guidance or suggestions would be highly appreciated. Thank you!

**Comment by j-c-c** [comment]
Dear @phonchi,

Thank you for reporting this issue. I will need to investigate this further, but it seems like ASPIRE is having some trouble at the mean volume step when using the ground truth orientations to back project.

If you add an orientation estimation step just before mean volume estimation you should get a more faithful reconstruction. You could use less images to speed up this process, `n=500` should do (you can do this inline as shown below). This step would look like:

```
from aspire.source import OrientedSource
source = OrientedSource(source[:500])
```

The whitening step shouldn't be necessary since you have clean images, but I would apply the phase flip since you've added CTF corruption. So the full pipeline would look like:
1. Downsample
2. Phase flip
3. Estimate orientations (will take a few minutes)
4. Mean volume estimation

In theory, the orientation estimation step should not be necessary, so I will have to investigate as to why we're not getting a good reconstruction using the ground truth orientations.

Please let us know if this added pipeline step improves your reconstruction. I will follow up with any findings on our end.

Thanks!

**Comment by j-c-c** [comment]
@phonchi, I would also recommend taking advantage of ASPIRE's Fast Fourier Bessel Basis, `aspire.basis.FFBBasis3D`, during the mean volume estimation step (as opposed to `FBBasis3D`).

**Comment by janden** [comment]
Thank you for reporthing this @phonchi. Indeed, this should work without any trouble. Do you observe the same artifacts when you project without CTFs?

**Comment by phonchi** [comment]
Dear developers:

Thank you for your prompt response and guidance. Following your suggestions, I introduced the `OrientedSource` step before the reconstruction as shown:

```
import os

import matplotlib.pyplot as plt
import numpy as np

from aspire.basis import FFBBasis3D
from aspire.noise import AnisotropicNoiseEstimator
from aspire.reconstruction import MeanEstimator
from aspire.source import RelionSource
from aspire.source import OrientedSource

data_folder = "/home/user"
file_path = "/home/user/proj.star"

source = RelionSource(
    file_path,
    pixel_size=5,
    max_rows=10000,
    data_folder=data_folder,
)

# Reduce the resolution
L = 32  
source = source.downsample(L)

source = source.phase_flip()
source = OrientedSource(source[:1000])
#noise_estimator = AnisotropicNoiseEstimator(source)
#source = source.whiten(noise_estimator)
# We'll create a 3D Fourier Bessel Basis corresponding to volume resolution L.
basis = FFBBasis3D((L, L, L))
# Estimate mean Volume
mean_estimator = MeanEstimator(source, basis, batch_size=8192)
mean_est = mean_estimator.estimate()

vol = mean_est.asnumpy()[0]
# Visualize volume
L = vol.shape[0]
# Plots
plt.suptitle("Orthogonal Projections", size=20)
plt.subplot(1, 3, 1, title="x-axis")
plt.imshow(np.sum(vol, axis=0), cmap="gray")
plt.subplot(1, 3, 2, title="y-axis")
plt.imshow(np.sum(vol, axis=1), cmap="gray")
plt.subplot(1, 3, 3, title="z-axis")
plt.imshow(np.sum(vol, axis=2), cmap="gray")
plt.tight_layout()
plt.subplots_adjust(top=1.25)
plt.show()

mean_est.save('aspire.mrc', overwrite=True)
```

The reconstruction yielded reasonable results. The orthogonal projections can be viewed here: ![aspire2](https://github.com/ComputationalCryoEM/ASPIRE-Python/assets/11373055/0a0264e1-3b52-4be1-9956-7bfc0e142dd6)

However, when I eliminated the orientation estimation step, the familiar artifact reappeared.

Moreover, when I opted not to include the CTF, I encountered a `ValueError`. The relevant log is as follows:

```
2023-10-11 20:35:24,372 INFO [aspire.source.relion] Creating ImageSource from STAR file at path /home/phonchi/aspire/proj2.star
2023-10-11 20:35:24,377 INFO [aspire.storage.starfile] Parsing star file at: /home/phonchi/aspire/proj2.star
2023-10-11 20:35:24,450 INFO [aspire.storage.starfile] Created StarFile with blocks: optics, particles
2023-10-11 20:35:24,502 INFO [aspire.source.image] Creating RelionSource with 3000 images.
2023-10-11 20:35:24,504 WARNING [aspire.source.relion] Found partially populated CTF Params.  To automatically populate CTFFilters provide ['_rlnVoltage', '_rlnDefocusU', '_rlnDefocusV', '_rlnDefocusAngle', '_rlnSphericalAberration', '_rlnAmplitudeContrast']
2023-10-11 20:35:24,505 INFO [aspire.source.relion] Populated 0 CTFFilters from '/home/phonchi/aspire/proj2.star'
2023-10-11 20:35:24,510 INFO [aspire.source.image] Setting max. resolution of source = 50
2023-10-11 20:35:24,513 INFO [aspire.basis.ffb_3d] Expanding 3D map in a frequency-domain Fourier–Bessel basis using the fast method.
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Cell In[10], line 32
     30 # Estimate mean Volume
     31 mean_estimator = MeanEstimator(source, basis, batch_size=8192)
---> 32 mean_est = mean_estimator.estimate()
     34 vol = mean_est.asnumpy()[0]
     35 # Visualize volume

File ~/ASPIRE-Python/src/aspire/reconstruction/estimator.py:64, in Estimator.estimate(self, b_coeff, tol, regularizer)
     62 """Return an estimate as a Volume instance."""
     63 if b_coeff is None:
---> 64     b_coeff = self.src_backward()
     65 est_coeff = self.conj_grad(b_coeff, tol=tol, regularizer=regularizer)
     66 est = self.basis.evaluate(est_coeff).T

File ~/ASPIRE-Python/src/aspire/reconstruction/mean.py:166, in WeightedVolumesEstimator.src_backward(self)
    162     for k in range(self.r):
    163         im = self.src.images[i : i + self.batch_size]
    165         batch_vol_rhs = (
--> 166             self.src.im_backward(im, i, self.weights[:, k]) / self.src.n
    167         )
    168         vol_rhs[k] += batch_vol_rhs.astype(self.dtype)
    170 res = np.sqrt(self.src.n) * self.basis.evaluate_t(vol_rhs)

File ~/ASPIRE-Python/src/aspire/source/image.py:955, in ImageSource.im_backward(self, im, start, weights)
    953 im *= self.amplitudes[all_idx, np.newaxis, np.newaxis]
    954 im = im.shift(-self.offsets[all_idx, :])
--> 955 im = self._apply_source_filters(im, all_idx)
    957 if weights is not None:
    958     im *= weights[all_idx, np.newaxis, np.newaxis]

File ~/ASPIRE-Python/src/aspire/source/image.py:754, in ImageSource._apply_source_filters(self, im_orig, indices)
    750 def _apply_source_filters(self, im_orig, indices):
    751     return self._apply_filters(
    752         im_orig,
    753         self.unique_filters,
--> 754         self.filter_indices[indices],
    755     )

File ~/ASPIRE-Python/src/aspire/source/image.py:435, in ImageSource.filter_indices(self)
    433 @property
    434 def filter_indices(self):
--> 435     return np.atleast_1d(self.get_metadata("__filter_indices"))

File ~/ASPIRE-Python/src/aspire/source/image.py:714, in ImageSource.get_metadata(self, metadata_fields, indices, default_value, as_dict)
    708     return self._metadata_as_dict(
    709         metadata_fields=metadata_fields,
    710         indices=indices,
    711         default_value=default_value,
    712     )
    713 else:
--> 714     return self._metadata_as_ndarray(
    715         metadata_fields=metadata_fields,
    716         indices=indices,
    717         default_value=default_value,
    718     )

File ~/ASPIRE-Python/src/aspire/source/image.py:340, in ImageSource._metadata_as_ndarray(self, metadata_fields, indices, default_value)
    338 if metadata_field not in self._metadata:
    339     if default_value is None:
--> 340         raise ValueError(
    341             f"Missing metadata field {metadata_field} and no default_value supplied"
    342         )
    343     result[:, i] = default_value
    344     dtypes[i] = np.array([default_value]).dtype

ValueError: Missing metadata field __filter_indices and no default_value supplied
```

Do you have any insights or suggestions on how to proceed? Thanks in advance!

**Comment by j-c-c** [comment]
Hi @phonchi, it looks like you might still have some of the CTF fields in the starfile. The `RelionSource` is expecting all, or none, of the following CTF fields:
```
 "_rlnVoltage",
"_rlnDefocusU",
"_rlnDefocusV",
"_rlnDefocusAngle",
"_rlnSphericalAberration",
"_rlnAmplitudeContrast"
```
So if any of those remain you might try removing them.

**Comment by phonchi** [comment]
Dear developers:

Thank you for your guidance. Following your advice, I removed the specified CTF fields from the starfile. The program now runs without any errors. However, I've observed that the artifact still persists in the resulting volume.

**Comment by phonchi** [comment]
Dear Developers:

Upon further investigation, I suspect the issue might be linked to the grid generation convention. I noted that by modifying the `indexing` in [https://github.com/ComputationalCryoEM/ASPIRE-Python/blob/main/src/aspire/volume/volume.py#L661](https://github.com/ComputationalCryoEM/ASPIRE-Python/blob/main/src/aspire/volume/volume.py#L661) from 'xy' to 'yx', I can achieve a reasonable reconstruction without using the `OrientedSource` using the following code:

```
import os

import matplotlib.pyplot as plt
import numpy as np

from aspire.basis import FFBBasis3D
from aspire.noise import AnisotropicNoiseEstimator
from aspire.reconstruction import MeanEstimator
from aspire.source import RelionSource
from aspire.source import OrientedSource

data_folder = "/home/user"
file_path = "/home/user/proj.star"

source = RelionSource(
    file_path,
    pixel_size=5,
    max_rows=10000,
    data_folder=data_folder,
)

# Reduce the resolution
L = 32  
source = source.downsample(L)

source = source.phase_flip()
#noise_estimator = AnisotropicNoiseEstimator(source)
#source = source.whiten(noise_estimator)
# We'll create a 3D Fourier Bessel Basis corresponding to volume resolution L.
basis = FFBBasis3D((L, L, L))
# Estimate mean Volume
mean_estimator = MeanEstimator(source, basis, batch_size=8192)
mean_est = mean_estimator.estimate()

vol = mean_est.asnumpy()[0]
# Visualize volume
L = vol.shape[0]
# Plots
plt.suptitle("Orthogonal Projections", size=20)
plt.subplot(1, 3, 1, title="x-axis")
plt.imshow(np.sum(vol, axis=0), cmap="gray")
plt.subplot(1, 3, 2, title="y-axis")
plt.imshow(np.sum(vol, axis=1), cmap="gray")
plt.subplot(1, 3, 3, title="z-axis")
plt.imshow(np.sum(vol, axis=2), cmap="gray")
plt.tight_layout()
plt.subplots_adjust(top=1.25)
plt.show()

mean_est.save('aspire.mrc', overwrite=True)
```

I'm currently using RELION version 3.1.3-commit-fa923d. I'm wondering whether there might be varying conventions between different versions of RELION/ASPIRE that could be influencing this. Your insights would be greatly valued. Thanks!

**Comment by j-c-c** [comment]
Dear @phonchi:

Thank you for investigating further and finding this issue with the grid `indexing`. It's helpful to know that switching the grid `indexing` resulted in a reasonable reconstruction.

It is the case that our grid convention used for projecting images is different from Relion, but we are working to remedy this (#196). Our convention is internally consistent (which is why using the estimated rotations from `OrientedSource` resulted in a good recon), but we'll have to address this grid issue for Relion interoperability. I will prioritize this issue and follow up with a resolution.

Thanks!

**Comment by garrettwrong** [comment]
This appears to be a duplicate of #639 .  Because the documentation is much better here, and that user no longer exists, I am going to close 639.

**Comment by j-c-c** [comment]
@phonchi, I wanted to give a little bit of follow up here. With the completion of #1030 the ASPIRE grid convention now corresponds with Relion's. If you check out our `develop` branch your original script should run and give a reasonable reconstruction.

Best,
Josh

@garrettwrong and @janden, I am leaving this issue open in the meantime as I work on implementing a unit test for Relion interoperability comparing our simulated projection images to Relion's.

**Comment by phonchi** [comment]
Dear Developers:

Thank you for the update and your efforts. I have now tested the script using the code from the develop branch and it indeed produces a reasonable reconstruction.

Please feel free to close the issue at your convenience, especially once the unit tests are completed. Once again, thank you for your prompt and effective assistance!

**Comment by j-c-c** [comment]
Closing now that we've added a test and gallery tutorial for Relion projection interoperability.
