### ISSUE TITLE
ASPIRE CTF background estimation on micrographs recorded with K2 cameras 

### ISSUE THREAD

**Issue by ayeletheimowitz** [ComputationalCryoEM/ASPIRE-Python#1036]
A release note should be added detailing a potential issue for ASPIRE-CTF when working on micrographs recorded on a K2 camera in counting mode:

ASPIRE-CTF computes the background as a monotonically decreasing function of spatial frequency. This practice may lead to an inaccurate background estimation for experimental images produced using a K2 camera in counting mode, as the background in this case is not monotonically decreasing. Despite this, ASPIRE-CTF does successfully capture the CTF parameters in such situations.

**Comment by garrettwrong** [comment]
Hi Ayelet, I will your note to that module's documentation. Thanks

**Comment by garrettwrong** [comment]
Added. Closing.
