### ISSUE TITLE
Sync Voting Flakey Test

### ISSUE THREAD

**Issue by garrettwrong** [ComputationalCryoEM/ASPIRE-Python#1049]
Seen this expensive `tests/test_orient_sync_voting.py` test fail a few times while trying to clean up some of my own flaky tests.  I think we didn't notice before because it was often also in the company of (in the logs after) other more familiar flaky tests (the classavg and FLE ones which are improving)... 

https://github.com/ComputationalCryoEM/ASPIRE-Python/actions/runs/6906029797/job/18790107662

Hopefully just requires a look and a small change.

**Comment by j-c-c** [comment]
Looks like the tolerance can be slightly loosened on this one. We're just missing the 98% tol under non-zero offsets and even resolution.

**Comment by garrettwrong** [comment]
Sounds good, thanks!
