### ISSUE TITLE
Extend denoising module by including other basis classes

### ISSUE THREAD

**Issue by junchaoxia** [ComputationalCryoEM/ASPIRE-Python#106]
The Cov2D denoising module is using fast FB basis class for image expanding. In future it should be extended to use other basis classes.

**Comment by garrettwrong** [comment]
I think we've implemented the class abstractions to support this.  The underlying `Denoiser` is agnostic to basis and cov2d has been made agnostic to basis.

To complete the issue:

- Remove the limitation that `DenoiserCov2D` requires FFB2D.
- Test the denoiser against other basis.

Should be a small PR after #1014 and #1015.

**Comment by garrettwrong** [comment]
Bit of a wrinkle, leveraging the denoiser invokes the filter to basis mat method, so this sort of depends/relates to #1016 .

Probably the right time to look at this now.

**Comment by garrettwrong** [comment]
Closed by #1031
