### ISSUE TITLE
Clean up and include the 2D Classification method

### ISSUE THREAD

**Issue by junchaoxia** [ComputationalCryoEM/ASPIRE-Python#108]
The 2D classification method from the original Princeton University repo `(src/aspire/aspire/class_averaging.py)` need to be cleaned up, debugged and included in the general framework.

**Comment by junchaoxia** [comment]
The major steps for cleaning up and extracting 2D classification code are listed as below: 

1. replace the interface to load star and mrcs file using the RelionSoure class
2. replace the FB basis for 2D image expending using the unified FB class 
3. clean up the calculation method of bispectrum (new class to be developed)
4. clean up the nearest-neighbor classification method 
5. clean up the vector diffusion maps classification method
7. clean up the fast rotation alignment and class averaging method 
8. reorganize the class2d module
9. rewrite the CLI command

**Comment by garrettwrong** [comment]
Remaining tasks here are covered by small/moderate discrete issues in combination with larger long term projects (EM method). Closing.
