### ISSUE TITLE
CUDA/CUPY kernel for building Common Line matrix

### ISSUE THREAD

**Issue by garrettwrong** [ComputationalCryoEM/ASPIRE-Python#1114]
Given the successful speedups using CUDA for parts of the Sync3N algorithm, we should implement a similar GPU implementation for building the CL matrix.

For unit test sized problems our current implementation is tolerable, but for larger experiments (say 3000 images) it can take 5-6 hours with the current python implementation.  The legacy MATLAB code provided both a CPU and GPU implementation, though I am not sure how relevant either are to the implementation that exists in python today (tbd).

Another feature that was nice about the MATLAB code is that it provided a way to store and recall the CL matrix via the workspace.  We can consider optionally writing to disk and providing a method to load from disk.  I expect that might speed up some development tasks in the future.

**Comment by janden** [comment]
Sounds good. What sort of speedup do you think we could get here?

**Comment by garrettwrong** [comment]
For problem sizes we care about at this stage in the pipeline (a few thousand images) I suspect it should be 2 orders of magnitude conservatively.  I would work on it now, but I don't want to grow the sync3n work anymore than it already has.  Better to move the stuff thats out along and come back to this.

**Comment by garrettwrong** [comment]
Noting this is working with a nice speedup in #1167 and I will continue trying to optimize it a bit more for 0.13.1
