### ISSUE TITLE
`sklearn` release breaking API

### ISSUE THREAD

**Issue by j-c-c** [ComputationalCryoEM/ASPIRE-Python#1119]
CI is failing due to API changes in the recent release of `sklearn` v1.5. Looking into the details now.

**Comment by garrettwrong** [comment]
I see we hit an issue regarding python/package support.  Some notes.

In the past we have talked about attempting to follow numpy's python support timeline which can be found here:

https://numpy.org/neps/nep-0029-deprecation_policy.html#drop-schedule

Not we are just passed the `3.9` drop date.  Their schedule is pretty aggressive.  Slightly more relaxed is python's own guidance:

https://devguide.python.org/versions/

I personally expect 3.8 and 3.9 as most common in our expected user base right now.  We have had trouble getting all dependencies supported with the most recent releases.  I'm not sure we want to drop 3.8 until later, nor do I think we should pin scikit if making it flexible is only a few lines of code.

Pretty sure we can easily support both for a time based on the initial patch attempt.  We should discuss at the upcoming dev meeting.

**Comment by j-c-c** [comment]
Sounds good. Should be pretty easy to accommodate both versions of scikit.

**Comment by j-c-c** [comment]
Resolved by #1120
