### ISSUE TITLE
FFBBasis2D has its own expand method

### ISSUE THREAD

**Issue by janden** [ComputationalCryoEM/ASPIRE-Python#113]
Shown here: https://github.com/ComputationalCryoEM/ASPIRE-Python/blob/5a1439abcec28bb763aefb09522021ca87210339/src/aspire/basis/ffb_2d.py#L250

Shouldn't this be handled by the `expand` method in the `Basis` superclass?

**Comment by janden** [comment]
Same goes for `FFBBasis3D`.

**Comment by junchaoxia** [comment]
I believe it should be possible to move it to basis class. I remember when I implement the FFB methods the expand function in the FB 2D method is not right when using multiple images. This is an issue reported in a previous repo but got lost during the merging.

**Comment by janden** [comment]
Ok. I will do this then.

**Comment by junchaoxia** [comment]
I checked that the expand function has been move to the base class in commit # 64b6ee3. We forgot to close this. Closing now.
