### ISSUE TITLE
Volume pixel size

### ISSUE THREAD

**Issue by j-c-c** [ComputationalCryoEM/ASPIRE-Python#1152]
A user recently brought up the need for saving `Volume`s with a pixel size:

```
Hi,
When saving a Volume into an mrc file, the pixel size in the mrc is 0.
It is important to keep track of the correct pixel size.
For example, if we download 2660, its pixel size is 1.34A.
If we downsample it by a factor of 2, the new pixel size should be 2.68A.
This number must should in the saved mrc, as it is used, for example, by Chimera and RELION. 
```

**Comment by garrettwrong** [comment]
Put a PR together that adds attribute for `Volume` along with save/load methods.

I think we probably want to handle pixel_size similarly for `Image`. Will look into that next.

I still need to confirm that Chimera/RELION are picking up the value we are saving.
