### ISSUE TITLE
Dimension independence of Filters

### ISSUE THREAD

**Issue by janden** [ComputationalCryoEM/ASPIRE-Python#119]
For example, `ScalarFilter` requires the dimension to be specified when constructed:

https://github.com/ComputationalCryoEM/ASPIRE-Python/blob/24e057f3997f4b2acf7b36a91bedc339f1e16a7a/src/aspire/utils/filters.py#L192

Like other filters (`IdentityFilter`, `ZeroFilter`, etc.), the dimension is not needed here: the filter will work for arrays of any dimension. Therefore, I suggest we drop this requirement, and let `dim = None` mean that the filter is compatible with any array.

**Comment by junchaoxia** [comment]
This issue was done in PR #242. Closing now.
