### ISSUE TITLE
`ImageSource.downsample` moves particles

### ISSUE THREAD

**Issue by j-c-c** [ComputationalCryoEM/ASPIRE-Python#1196]
It looks like `ImageSource.downsample` might be applying the updated offsets to original src prior to applying downsample. Looks like the downsampled particles have different offsets from the original.

Here is a minimal script to illustrate:
```python
import numpy as np

from aspire.source import Simulation
L = 64
n = 10

offsets = np.random.choice([L//4, -L//4], size=(n, 2))
src = Simulation(L=L, n=n, offsets=offsets)
src2 = src.downsample(L//4)

print(f"src.offsets: {src.offsets}\n")
src.images[:10].show()

print(f"src2.offsets: {src2.offsets}")
src2.images[:10].show()
```
with output:
```
src.offsets: [[-16.  16.]
 [ 16. -16.]
 [-16. -16.]
 [ 16.  16.]
 [ 16.  16.]
 [ 16.  16.]
 [-16. -16.]
 [-16.  16.]
 [-16. -16.]
 [ 16.  16.]]
```
<img width="1138" alt="Screenshot 2024-10-10 at 2 27 09 PM" src="https://github.com/user-attachments/assets/bbad0043-a633-454b-9750-0108de008c39">

```
src2.offsets: [[-4.  4.]
 [ 4. -4.]
 [-4. -4.]
 [ 4.  4.]
 [ 4.  4.]
 [ 4.  4.]
 [-4. -4.]
 [-4.  4.]
 [-4. -4.]
 [ 4.  4.]]
```
<img width="1159" alt="Screenshot 2024-10-10 at 2 28 41 PM" src="https://github.com/user-attachments/assets/33dab534-86e6-42d8-aaf7-b50659c4d8dd">

**Comment by garrettwrong** [comment]
Yeah I think you are right.  Looks like another pipeline design issue.

Here are two ways to resolve, probably more.  

Preprocessing that involves scaling pixel/filters can to be overloaded in `Simulation`.  
or
Simulation can store a re-scaling factor.

I think the complication isn't solving the case you posted, but the case when you update offsets after some sequence of preprocessing.

The only nice thing about this is that the downsample might be working for real data sources :D.

**Comment by j-c-c** [comment]
Sounds good. I'll take a look at resolving this.

> The only nice thing about this is that the downsample might be working for real data sources :D.

Yeah, just checked for a `RelionSource` and looks like downsample is working as expected with regards to offsets.

**Comment by garrettwrong** [comment]
Closed via 1200
