### ISSUE TITLE
Check that `conj_grad` works without casts to real

### ISSUE THREAD

**Issue by janden** [ComputationalCryoEM/ASPIRE-Python#121]
Look into this:

https://github.com/ComputationalCryoEM/ASPIRE-Python/blob/24e057f3997f4b2acf7b36a91bedc339f1e16a7a/src/aspire/utils/optimize.py#L135

**Comment by junchaoxia** [comment]
Removing real casts still passed all unit tests of cov2d and it took around  2 seconds for all tests with and without casts using 28 cores on the tiger cluster.

_________________________________________________________________________________________
output from Removing casts: 
_________________________________________________________________________________________
../../software/ASPIRE-Python_git/tests/test_covar2d.py::Cov2DTestCase::test01GetMean
-------------------------------- live log call ---------------------------------
2020/08/20 15:16:12 Expanding 2D image in a frequency-domain Fourier–Bessel basis using the fast method.
2020/08/20 15:16:12 Trying NFFT backend finufft
2020/08/20 15:16:12 NFFT backend finufft usable
2020/08/20 15:16:12 Trying NFFT backend pynfft
2020/08/20 15:16:12 NFFT backend pynfft not usable
2020/08/20 15:16:12 Selected NFFT backend = finufft
2020/08/20 15:16:12 Caching source images
PASSED                                                                   [ 12%]
../../software/ASPIRE-Python_git/tests/test_covar2d.py::Cov2DTestCase::test02GetCovar
-------------------------------- live log call ---------------------------------
2020/08/20 15:16:12 Expanding 2D image in a frequency-domain Fourier–Bessel basis using the fast method.
2020/08/20 15:16:12 Caching source images
PASSED                                                                   [ 25%]
../../software/ASPIRE-Python_git/tests/test_covar2d.py::Cov2DTestCase::test03GetMeanCTF
-------------------------------- live log call ---------------------------------
2020/08/20 15:16:13 Expanding 2D image in a frequency-domain Fourier–Bessel basis using the fast method.
2020/08/20 15:16:13 Caching source images
PASSED                                                                   [ 37%]
../../software/ASPIRE-Python_git/tests/test_covar2d.py::Cov2DTestCase::test04GetCovarCTF
-------------------------------- live log call ---------------------------------
2020/08/20 15:16:13 Expanding 2D image in a frequency-domain Fourier–Bessel basis using the fast method.
2020/08/20 15:16:13 Caching source images
PASSED                                                                   [ 50%]
../../software/ASPIRE-Python_git/tests/test_covar2d.py::Cov2DTestCase::test05GetCovarCTFShrink
-------------------------------- live log call ---------------------------------
2020/08/20 15:16:13 Expanding 2D image in a frequency-domain Fourier–Bessel basis using the fast method.
2020/08/20 15:16:13 Caching source images
PASSED                                                                   [ 62%]
../../software/ASPIRE-Python_git/tests/test_covar2d.py::Cov2DTestCase::test06GetCWFCoeffs
-------------------------------- live log call ---------------------------------
2020/08/20 15:16:13 Expanding 2D image in a frequency-domain Fourier–Bessel basis using the fast method.
2020/08/20 15:16:13 Caching source images
PASSED                                                                   [ 75%]
../../software/ASPIRE-Python_git/tests/test_covar2d.py::Cov2DTestCase::test07GetCWFCoeffsIdentityCTF
-------------------------------- live log call ---------------------------------
2020/08/20 15:16:14 Expanding 2D image in a frequency-domain Fourier–Bessel basis using the fast method.
2020/08/20 15:16:14 Caching source images
PASSED                                                                   [ 87%]
../../software/ASPIRE-Python_git/tests/test_covar2d.py::Cov2DTestCase::test08GetCWFCoeffsClean
-------------------------------- live log call ---------------------------------
2020/08/20 15:16:14 Expanding 2D image in a frequency-domain Fourier–Bessel basis using the fast method.
2020/08/20 15:16:14 Caching source images
PASSED                                                                   [100%]

_______________________________________________________________________________________
output  from real casts:
_______________________________________________________________________________________ 
../../software/ASPIRE-Python_git/tests/test_covar2d.py::Cov2DTestCase::test01GetMean
-------------------------------- live log call ---------------------------------
2020/08/20 15:11:42 Expanding 2D image in a frequency-domain Fourier–Bessel basis using the fast method.
2020/08/20 15:11:42 Trying NFFT backend finufft
2020/08/20 15:11:42 NFFT backend finufft usable
2020/08/20 15:11:42 Trying NFFT backend pynfft
2020/08/20 15:11:42 NFFT backend pynfft not usable
2020/08/20 15:11:42 Selected NFFT backend = finufft
2020/08/20 15:11:42 Caching source images
PASSED                                                                   [ 12%]
../../software/ASPIRE-Python_git/tests/test_covar2d.py::Cov2DTestCase::test02GetCovar
-------------------------------- live log call ---------------------------------
2020/08/20 15:11:42 Expanding 2D image in a frequency-domain Fourier–Bessel basis using the fast method.
2020/08/20 15:11:42 Caching source images
PASSED                                                                   [ 25%]
../../software/ASPIRE-Python_git/tests/test_covar2d.py::Cov2DTestCase::test03GetMeanCTF
-------------------------------- live log call ---------------------------------
2020/08/20 15:11:43 Expanding 2D image in a frequency-domain Fourier–Bessel basis using the fast method.
2020/08/20 15:11:43 Caching source images
PASSED                                                                   [ 37%]
../../software/ASPIRE-Python_git/tests/test_covar2d.py::Cov2DTestCase::test04GetCovarCTF
-------------------------------- live log call ---------------------------------
2020/08/20 15:11:43 Expanding 2D image in a frequency-domain Fourier–Bessel basis using the fast method.
2020/08/20 15:11:43 Caching source images
PASSED                                                                   [ 50%]
../../software/ASPIRE-Python_git/tests/test_covar2d.py::Cov2DTestCase::test05GetCovarCTFShrink
-------------------------------- live log call ---------------------------------
2020/08/20 15:11:43 Expanding 2D image in a frequency-domain Fourier–Bessel basis using the fast method.
2020/08/20 15:11:43 Caching source images
PASSED                                                                   [ 62%]
../../software/ASPIRE-Python_git/tests/test_covar2d.py::Cov2DTestCase::test06GetCWFCoeffs
-------------------------------- live log call ---------------------------------
2020/08/20 15:11:43 Expanding 2D image in a frequency-domain Fourier–Bessel basis using the fast method.
2020/08/20 15:11:43 Caching source images
PASSED                                                                   [ 75%]
../../software/ASPIRE-Python_git/tests/test_covar2d.py::Cov2DTestCase::test07GetCWFCoeffsIdentityCTF
-------------------------------- live log call ---------------------------------
2020/08/20 15:11:44 Expanding 2D image in a frequency-domain Fourier–Bessel basis using the fast method.
2020/08/20 15:11:44 Caching source images
PASSED                                                                   [ 87%]
../../software/ASPIRE-Python_git/tests/test_covar2d.py::Cov2DTestCase::test08GetCWFCoeffsClean
-------------------------------- live log call ---------------------------------
2020/08/20 15:11:44 Expanding 2D image in a frequency-domain Fourier–Bessel basis using the fast method.
2020/08/20 15:11:44 Caching source images
PASSED                                                                   [100%]

 
I will remove the unnecessary casts in a new PR.  Note casts were used in the original Matlab code as below:

https://github.com/PrincetonUniversity/aspire/blob/master/common/conj_grad.m#L127
https://github.com/PrincetonUniversity/aspire/blob/master/common/conj_grad.m#L129
https://github.com/PrincetonUniversity/aspire/blob/master/common/conj_grad.m#L136

**Comment by janden** [comment]
I believe the cast is necessary for dealing with complex vectors. If you remove the cast, the algorithm may not converge given complex data. Do any of the tests check this?

**Comment by junchaoxia** [comment]
Currently only Cov2D in the new framework uses this customized CG method. Both unit tests and simulation example are fine. But if you worry about other cases might be different, we should keep it as the same as Matlab version. The removing of casts did not improve the performance much.

**Comment by janden** [comment]
It would be good to add a unit test to make sure things work properly when given complex data. In particular, I'm worried that the next two lines (assigning `x` and `a_x`) have a real cast while the Matlab code does not. I think those casts have to be removed for things to work with complex number.

**Comment by junchaoxia** [comment]
This issue was solved in PR #238. Closing now.
