### ISSUE TITLE
fill_struct in optimize.py

### ISSUE THREAD

**Issue by yoelsh** [ComputationalCryoEM/ASPIRE-Python#125]
The function fill_struct in src/aspire/utils/optimize.py returns a dictionary and not a struct. 
Also, in Itay's implementation the corresponding function include functionality that currently appears in TODO. See fill_struct in src/aspire/aspire/abinitio.py

**Comment by junchaoxia** [comment]
I believe that I extracted the original code from aspire/aspire/abinito.py. Recent we found  several bugs and improved. So we should use the one src/aspire/utils/optimize.py.

**Comment by itaysason** [comment]
The problem is this is not actually a struct, this is just a dictionary. What was the bug maybe I can just fix it.

**Comment by junchaoxia** [comment]
There are quite lots of changes. You can trace all changes by click the history button of the file. 
https://github.com/ComputationalCryoEM/ASPIRE-Python/commits/master/src/aspire/utils/optimize.py

Or do a diff comarison on the two files. We think a simple dictionary can solve the problem easier. But I think it can be switched to a more complex struct if it is really necessary.

**Comment by itaysason** [comment]
So the problem was in the CG and not in the fill_struct? I don't see any real change to fill struct aside from changing it from structure to dictionary. Also, fill_struct should be in some general util file as I use it in other places.

**Comment by junchaoxia** [comment]
Mostly in the CG method, but there are also some problems for overwriting and the order of taking arguments in the original fill_struct. The dictionary format should be similar to the origin struct except the  method to access attributes.
