### ISSUE TITLE
src/aspire/utils/blk_diag_func.py

### ISSUE THREAD

**Issue by yoelsh** [ComputationalCryoEM/ASPIRE-Python#126]
Scipy includes functions to handle block diagonal matrices.
Why do we need this file?

**Comment by junchaoxia** [comment]
I think you are referring to the webpage as below:  https://docs.scipy.org/doc/scipy/reference/generated/scipy.linalg.block_diag.html

The operations for spicy is very limit, only generating a large block diagonal matrix from a list. The way we implemented only need to store the diagonal blocks and perform operations based on them. This is mimicking the Matlab version using functions.  The implementation can be done using the Class idea.

**Comment by garrettwrong** [comment]
Not a concern atm, but in the future I would be in favor of re-implementing this as a python class, particularly with natural operator overloading and ability to mix in numpy instances.  I think it would make the code expression more natural.  Once I have a better idea of how (heavily) it is used, we might consider optimization here as well.  These ideas are all premature at this point.

**Comment by junchaoxia** [comment]
Yes. We have an older issue #111 for discussing this improvement. I closed this one to remove the redundancy.
