### ISSUE TITLE
lgwt

### ISSUE THREAD

**Issue by yoelsh** [ComputationalCryoEM/ASPIRE-Python#128]
The module /src/aspire/basis/basis_utils.py/ implement lgwt.
This function already exists in numpy.polynomial.legendre.leggauss

**Comment by junchaoxia** [comment]
I checked the implementation. The numpy version only generates the values and weights in the range of (-1, 1) Our implementation which matches matlab version can generate the values and weights for any specified range.  But you are right, we can use the one from numpy by shifting and rescaling. Please let me know if  the numpy version is preferred.

**Comment by junchaoxia** [comment]
This function has been re-implemented (in commit 9f35765) by creating a wrapper for the numpy version with the fixed range of (-1, 1).
