### ISSUE TITLE
Remove original Princeton Repo 

### ISSUE THREAD

**Issue by junchaoxia** [ComputationalCryoEM/ASPIRE-Python#135]
The original repo, https://github.com/PrincetonUniversity/ASPIRE-Python, includes old python code but is not maintained. We should set https://github.com/ComputationalCryoEM/ASPIRE-Python as the parent repo when we remove the old one.

**Comment by garrettwrong** [comment]
Note, I contacted GH support about this on 6/17.  Normally this should take about a business day, but they responded with a note about COVID priority order changes... I just pinged support again.  If I don't get an actionable response we may have to try from the PU Enterprise account side (GH indicated they may not be supporting non critical tasks for free open source during the crisis).

**Comment by garrettwrong** [comment]
I contacted GH again, and they were able to sever the fork relationship with the PU repo, keeping the 6 forks of ComputationalCryoEM intact.

We now just need to archive the PU repo in some way.  At our team meeting, lets confirm what we want to do with it (archive/read-only or delete etc).

**Comment by garrettwrong** [comment]
I worked with GH support to get our old PU repo redirected to ComputationalCryoEM. This required deleting the PU repo once support setup the redirect behind the scenes.

Old repo removed. Redirect is live.  

Closing
