### ISSUE TITLE
Try to Stick to ASCII

### ISSUE THREAD

**Issue by garrettwrong** [ComputationalCryoEM/ASPIRE-Python#158]
Running the latest code for hackathon I found we have injected non ascii characters into our code.  I don't think we should do that, and if we do (like for someones name), we need to do it correctly.  Here was a case of a Long-Dash \u2013 in place of a regular dash.  (copy paste accident I'm sure, easy thing to do).

We can do the whole utf-8 encoding thing, but I promise no one will like it, least of all myself. Lets just stick to ascii if we can.

Making an issue so I know that we need to check this across the code, repair, and automate something so it doesn't happen to users. (after the hackathon). It isn't something we want them to have to fix. Explaining locales and encoding etc isn't our business.

```
  File "/ccsopen/home/gwright/.conda/envs/aspire/lib/python3.6/logging/__init__.py", line 996, in emit
    stream.write(msg)
UnicodeEncodeError: 'ascii' codec can't encode character '\u2013' in position 68: ordinal not in range(128)
Call stack:
  File "tutorials/examples/cov2d_hackathon2020.py", line 172, in <module>
    main(args.img_size, args.num_imgs)
  File "tutorials/examples/cov2d_hackathon2020.py", line 83, in main
    ffbbasis = FFBBasis2D((img_size, img_size))
  File "/autofs/nccsopen-svm1_home/gwright/src/ASPIRE-Python/src/aspire/basis/fb_2d.py", line 43, in __init__
    super().__init__(size, ell_max)
  File "/autofs/nccsopen-svm1_home/gwright/src/ASPIRE-Python/src/aspire/basis/__init__.py", line 43, in __init__
    self._build()
  File "/autofs/nccsopen-svm1_home/gwright/src/ASPIRE-Python/src/aspire/basis/ffb_2d.py", line 34, in _build
    logger.info('Expanding 2D image in a frequency-domain Fourier\u2013Bessel'
Message: 'Expanding 2D image in a frequency-domain Fourier\u2013Bessel basis using the fast method.'
```

**Comment by janden** [comment]
This was me. I thought that utf-8 was more or less standard these days and restriction to ascii wasn't necessary. If that causes unnecessary problems, let's revert.

**Comment by janden** [comment]
Ok. Let's stick to ascii, then. I will learn to live with it. It's actually not that bad, it looks like there's only eight files that register as utf-8 right now and six of them are in aspire.basis (probably more en dashes).

**Comment by garrettwrong** [comment]
I didn't realize we planned to make use of utf-8 mathematics in the doc strings.  That is a good point that I did not consider at all. You got me there :).

When we do housekeeping sprints I can make an automated process that can check we shouldn't crash strangely; that is really what I worry about.

**Comment by janden** [comment]
> I didn't realize we planned to make use of utf-8 mathematics in the doc strings.

Eh that was the plan, but NumPy, SciPy, and all the others seem to manage without, so let's not get too crazy. We'll still with ascii here.
