### ISSUE TITLE
cufinufft bindings

### ISSUE THREAD

**Issue by garrettwrong** [ComputationalCryoEM/ASPIRE-Python#178]
Now that the hackathon has passed, and I think the abi and api changes have settled over at cufinufft, I will resume dressing up the bindings a little and trying to incorporate that into our code using the existing framework(s).  This has a few components

- complete bindings for singles and doubles
- complete the intelligent python wrapping layer Joakim started, and incorporate the typing logic etc.
- add some relevant unit tests (even if ugly for now, better than nothing).
- improve and document install process
- potentially consider ways to prepackage this (though that would be a future issue, worth noting now, since we'd want all packaging to work well together, ideally having one system...)

Some of this work was started already, but sort of got disrupted in the hackathon prep/event.

This combined with the `many` interface is the driving hackathon performance result, so we want to bring it in.

**Comment by junchaoxia** [comment]
Probably we should keep this as high priority since this library is used very often in other modules too.

**Comment by garrettwrong** [comment]
It shoudln't be used directly anywhere, but otherwise I agree, it is a priority. I would have been doing it today, but I have several meetings today, so chewing on smaller stuff. Thanks

**Comment by garrettwrong** [comment]
189 was merged, I think it covered all of the intended points in at least a serviceable level. Closing.
