### ISSUE TITLE
Git Grep is less useful than it could be

### ISSUE THREAD

**Issue by garrettwrong** [ComputationalCryoEM/ASPIRE-Python#183]
Because we include a variety of sources, particularly ipynb and npy/bin files, simple grep-ing can require a lot of filtering.

There are ways to manage that with git pro-actively.  One way is gitattributes, where we can tell git certain files are binary or otherwise should be ignored for certain activities.

I ran into this problem today (most days actually) doing a simple grep.  Try `git grep cg`, you'll get a lot of unhelpful stuff...

I'll push a small PR with the attributes file and an example that fixes the line above.  If when we encounter these things we note them in the file, we can make our git development experience more effective.  The file is also good for other stuff as needed..

**Comment by janden** [comment]
This makes sense. I'm not too familiar with `git grep` (or `gitattributes`), but this sounds reasonable.

**Comment by garrettwrong** [comment]
Closed but not forgotten with #184
