### ISSUE TITLE
Remove argument to ImageSource.cache

### ISSUE THREAD

**Issue by janden** [ComputationalCryoEM/ASPIRE-Python#193]
The purpose of this function is to fetch all the images in the source and store them in memory for quick lookup. It currently accepts a single argument which can be used to replace those images with an external array. This breaks a lot of assumptions about the ImageSource and should be removed. Currently, it seems to only be used in `tests/test_covar2d.py` and `tutorials/examples/cov3d_simulation.py`.

**Comment by junchaoxia** [comment]
I think the issue has been done in the PR #237. Closing now.
