### ISSUE TITLE
Standardize rotation manipulation

### ISSUE THREAD

**Issue by janden** [ComputationalCryoEM/ASPIRE-Python#195]
Currently, this is done through calls to `scipy.spatial.transform.Rotation`, which can convert between Euler angles and rotation  matrices (and quaternions, it looks like, but let's pretend we didn't know that). The issue is that for Euler angles, we have to specify the axis sequence, which adds some boilerplate to all the manipulations since it's always ZYZ. It might be a good idea to wrap this so that ZYZ is always used to reduce complexity a bit.

**Comment by junchaoxia** [comment]
Rotation manipulations are involved in several places as listed below: 

> 1) `ImageSource` class in `aspire/source/__init__.py` for building rotation matrices from Euler angles.
> 2) `Simulation` class in `aspire/source/simulations.py` for generating uniform_random_angles.
> 3) Several util functions in `aspire/utils/coor_trans.py ` for aligning rotation matrices, comparing two set of rotation matrices, and finding the common lines from rotations. 

There are related discussion in issue #213. The first PR can develop a Rotation Class first. Then we replace them in different class in other PRs.

**Comment by janden** [comment]
Agreed that the first PR should develop the `Rotation` class. Then we can start incorporating it where needed.

**Comment by garrettwrong** [comment]
Hrm, I am going to reopen this. I don't think Junchao ever actually replaced the legacy utils with the class.  We just have two implementations right now.  

Here is a superfical list of the places that need to be swapped.  I guess one concern is that if the class is not identical to the old functions this might be a bit of work to validate.

```
tests/test_coor_trans.py:    register_rotations,
tests/test_coor_trans.py:        q_mat_est, flag_est = register_rotations(rots_ref, regrots_ref)
tutorials/examples/orient3d_simulation.py:    register_rotations,
tutorials/examples/orient3d_simulation.py:Q_mat, flag = register_rotations(rots_est, rots_true)
tutorials/examples/orient3d_simulation.py:    f"MSE deviation of the estimated rotations using register_rotations : {mse_reg}"
Binary file tutorials/notebooks/Lecture_1-6_Feature_Demonstration.ipynb matches
tests/test_coor_trans.py:    get_aligned_rotations,
tests/test_coor_trans.py:        regrots_ref = get_aligned_rotations(rots_ref, q_mat, flag)
tutorials/examples/orient3d_simulation.py:    get_aligned_rotations,
tutorials/examples/orient3d_simulation.py:regrot = get_aligned_rotations(rots_est, Q_mat, flag)
Binary file tutorials/notebooks/Lecture_1-6_Feature_Demonstration.ipynb matches
tutorials/examples/orient3d_simulation.py:    get_rots_mse,
tutorials/examples/orient3d_simulation.py:mse_reg = get_rots_mse(regrot, rots_true)
Binary file tutorials/notebooks/Lecture_1-6_Feature_Demonstration.ipynb matches
src/aspire/abinitio/commonline_base.py:from aspire.utils.coor_trans import common_line_from_rots
src/aspire/abinitio/commonline_base.py:        c_ij, c_ji = common_line_from_rots(r_i.T, r_j.T, 2 * n_theta)
```

**Comment by janden** [comment]
Ok thanks for catching.

**Comment by garrettwrong** [comment]
@j-c-c , this relates to the debugging you did last week. You will over time work with these files.  We can either tackle this by replacing with our `Rotation` class wholesale, or incrementally as you work with the various files.  Assigning to your queue.

**Comment by garrettwrong** [comment]
In #499 we discussed adding `Rotation.about_{x,y,z}` utilities to clean up some of these existing and recently added uses of scipy rotations.

**Comment by garrettwrong** [comment]
These changes have been adopted. We now use our `Rotation` class wholesale. Closing.
