### ISSUE TITLE
Versioning/tagging 

### ISSUE THREAD

**Issue by garrettwrong** [ComputationalCryoEM/ASPIRE-Python#198]
in relation to master (and CI). I see there is a version existing. I might suggest we can use something like `bumpversion` and document it in some sort of developer notes w.r.t handling of master branch.

We discussed this a little in the developer meetings and guidelines.

It should be pretty minor to update everything existing to work with `bumpversion`.

Not really any sort of priority, but I'd like to see us start doing this on the next master merge, if only just for practice.

**Comment by janden** [comment]
So, if I understand correctly, we would run this (it would run as part of CI) whenever we do a merge to master (from devel). We would decide at merge time whether the changes constituted a major, minor, or patch bump. That makes sense.

I guess the need for this tool is that the version is encoded in many places, so this would take care of all of them at once?

**Comment by garrettwrong** [comment]
Yes, it updates all known occurrences in a systematic way. It even makes the git commit for you. Its easy; I'll be happy to document it when the time comes.

**Comment by janden** [comment]
Ok sounds good.

**Comment by garrettwrong** [comment]
Closed by 272.
