### ISSUE TITLE
filter_to_fb_mat jv optimization

### ISSUE THREAD

**Issue by garrettwrong** [ComputationalCryoEM/ASPIRE-Python#199]
In `blk_diag_matrix.py` the method `filter_to_fb_mat` consumes a fair amount of run time for examples etc.

We tracked it down to computation of a certain Bessel function `jv` inside a double for loop.  It might be possible to precompute these values or otherwise trim this down.

**Comment by junchaoxia** [comment]
The issue has been taken care by PR #239. Closing now.
