### ISSUE TITLE
Make tests more modular for common lines sync

### ISSUE THREAD

**Issue by janden** [ComputationalCryoEM/ASPIRE-Python#203]
Right now, tests rely on hardcoded data for checking the results, which makes them harder to inspect and more brittle than necessary. We should construct smaller test cases and apply these to the individual components (common lines calculation, voting, etc.) in addition to an integration test which verifies that we get the rotations within a prescribed MSE. This last test will necessary be quite loose, but with tighter (and simpler) tests for the individual components, this should be enough to guarantee correctness.

**Comment by garrettwrong** [comment]
@j-c-c , the tests you were showing me recently are in this direction.  If you feel we have or will cover this issue just tag the right related PR/issue. Thanks!

**Comment by garrettwrong** [comment]
@j-c-c , did we cover this in your large CL PR or is there still work to do?  I know some of your new tests where in this direction, but I'm not sure if we did anything wrt the legacy tests...

**Comment by j-c-c** [comment]
> @j-c-c , did we cover this in your large CL PR or is there still work to do? I know some of your new tests where in this direction, but I'm not sure if we did anything wrt the legacy tests...

@garrettwrong, I did make a common lines test, but it will be slightly different for non-symmetric particles. It should be a slight alteration of the test w/ symmetry. I'll work on it.

**Comment by garrettwrong** [comment]
Josh mentioned the newer (Cn symm) tests were written in this way, but will still need to address some of the legacy tests in a future release.

**Comment by j-c-c** [comment]
Closing this, as all hardcoded common lines tests were replaced with modular/logical tests in #994. See https://github.com/ComputationalCryoEM/ASPIRE-Python/pull/994/files#diff-57dc6b559879c56b31ffda34563183d9500872e95b84d0b8eac92aabe8401869
