### ISSUE TITLE
MrcStack loads all the images at once

### ISSUE THREAD

**Issue by janden** [ComputationalCryoEM/ASPIRE-Python#205]
Right now, `MrcStack` loads all the images from an MRC file at once (through a `Micrograph` object) and then indexes those during the call to `_images`. It would be better if the class instead would load the images on demand, just like `RelionSource` minus the STAR file.

**Comment by garrettwrong** [comment]
#204 should remove this in favor of an existing source.
 
 Labelling `wontfix` for now. Can close post 204.

**Comment by chris-langfield** [comment]
Closed by #718
