### ISSUE TITLE
ImageSource.cache should reset the generation pipeline

### ISSUE THREAD

**Issue by janden** [ComputationalCryoEM/ASPIRE-Python#206]
Right now, the caching mechanism in `ImageSource` does not reset the generation pipeline, which means that when a new processing step is added, the cache is invalidated and the whole pipeline has to be reapplied from the original images. Not only is this inefficient, but it creates problems when we change various metadata (such as `L` when we downsample).

A better approach would be to reset the generation pipeline when we call `cache`. We then effectively replace the “raw” images, allowing the user to apply new processing steps to them by adding elements to the pipeline. At the same time, we should rename the `_im` variable by something more descriptive, such as `_cached_im` or `_im_cache`.

**Comment by junchaoxia** [comment]
This issue was fixed in PR #237. Closing now.
