### ISSUE TITLE
Eliminate the use of binary files

### ISSUE THREAD

**Issue by vineetbansal** [ComputationalCryoEM/ASPIRE-Python#21]
Some top-level aspire functionality requires binary files, currently in the `commands/binaries` folder. See the `requires_binaries` function in `aspire.aspire.utils.helpers`. There are 2 issues:

1. Any command that needs these binaries will not function, since it naively looks for these binaries in the current working directory, which may be (and likely will be) completely removed from the package directory anyway. The decorator needs to be rewritten to use something like `importlib_resources`.

2. The entire use of binaries can theoretically be eliminated anyway, as per @janden .

**Comment by vineetbansal** [comment]
(1) fixed in commit b219c5684fec58dad66f823538942536b4f49b12

**Comment by janden** [comment]
I think this is good, right? The only place I can find binary data is in the tests and the galleries, but the core code does not use any, as far as I can tell.

**Comment by garrettwrong** [comment]
SGTM, closing :) .
