### ISSUE TITLE
RTD Documentation

### ISSUE THREAD

**Issue by garrettwrong** [ComputationalCryoEM/ASPIRE-Python#219]
We should have a chat with Vineet about our RTD setup and document it in a developer notes doc.  I don't think much has happened with it since it was setup for the project. I will start a doc.

Some thoughts:

- [x]  I think we want to update the repo from PU address, 
- [x]  It looks like we might be [stale](https://readthedocs.org/projects/aspire-python/)... master is not a year old.
- [x]  We should consider whether we want to automatically publish `develop` as well, so we don't have to build it locally.
- [x] We should be automatically building the docs as part of our CI (whether we push or not). This is one of the many things that `tox` can do for us.
- [x] I think there are some pep docstring compliance tools. We might want to see if they are any good and if we want to use them.

**Comment by garrettwrong** [comment]
Noting we have a gh pages docs as well (which is more recent :) )

https://computationalcryoem.github.io/ASPIRE-Python/installation.html

**Comment by vineetbansal** [comment]
Yes..I didn't know we still had traces of RTD. My understanding is that we set up GH pages to build automatically on master. If some fine-tuning is need there I'm happy to discuss.

**Comment by garrettwrong** [comment]
Correct, GH pages does build off master. I don't have any preference to which is better (GH or RTD), but I'd like to understand and document whichever systems we're using. Probably deprecate the old one. I started a document to collect these sort of things but it isn't quite ready to share yet.

**Comment by vineetbansal** [comment]
For what it's worth..there's some very minimal documentation in the docs on how to build them (was mostly for me to remember the steps, so nothing fancy):
https://computationalcryoem.github.io/ASPIRE-Python/installation.html#generating-documentation

Edit: Never mind, you were talking about documenting GH pages, not sphinx.

**Comment by garrettwrong** [comment]
Removed in our dev meeting 8/26

**Comment by janden** [comment]
So close?

**Comment by garrettwrong** [comment]
Lol, yeah, I was waiting to see if the rtd docs went away before closing it and making other issues.. Appears it is still online

https://aspire-python.readthedocs.io/en/latest/

**Comment by janden** [comment]
Hmm. Let's give it another day.

**Comment by garrettwrong** [comment]
Sure.  They (RTD) claim that deleting a project should remove all html version of it. I think other actions (like just disabling or making private) will still serve the old content.

**Comment by vineetbansal** [comment]
Reading the RTD documentation, it seems to be a very early iteration of the code that Robbie Brooks was working on (the one I deleted yesterday would have been at https://aspire.readthedocs.io, though I cannot be sure now that I've removed it) - I think the upstream repo that we've now disassociated with is holding the link to RTD - I'd probably contact Robbie and see if he can find and delete this.

Yes - the 'Edit in Github' link on RTD is linking back to PrincetonUniversity/ASPIRE-Python

**Comment by garrettwrong** [comment]
Cool so it looks like your removal did work then.

...It is just that ASPIRE had at least _three_ documentation websites, all different :D.

If we don't get traction with the prior dev, I'm sure we can contact RTD to help us clean it up.

**Comment by garrettwrong** [comment]
So I'm guessing we never heard back from Robbie about https://aspire-python.readthedocs.io/en/latest/ ?

**Comment by garrettwrong** [comment]
Robbie was able to remove the docs and account for us.  Success. Closing.
