### ISSUE TITLE
Make Starfile unit tests smarter

### ISSUE THREAD

**Issue by vineetbansal** [ComputationalCryoEM/ASPIRE-Python#22]
Because star-files refer to `*.mrcs` files in the filesystem, unit testing the `Starfile` class against the installed package would have to mock the filesystem access such that `*.mrcs` path resolution always succeeds, even when the entire package is zipped up.

Till this is implemented, `zip_safe` in setup.py should be set to False.

**Comment by garrettwrong** [comment]
I think this is resolved via importlib etc . If it comes up again we can make a fresh issue.
