### ISSUE TITLE
Setup a minimal tox

### ISSUE THREAD

**Issue by garrettwrong** [ComputationalCryoEM/ASPIRE-Python#220]
I'm creating this issue for documentation/discussion.

`tox` is a standard tool to automate a lot of production quality checks on python packages.  This morning, two topics have come up that are commonly addressed by using this standard tool (the first two). I dug several others out.

- Documentation checking #219 
- Consideration of automated testing of `pip install` for major vanilla python versions in #216 
- Automatic import ordering and sanity testing #179 
- Automatic linting (will require work toward compliant code, and flexible config (line too longs)) #154 #69 
- Can construct additional (upstream) environments to catch things like #218 #217 .
- For standard python code, tox can (with venv) generate our wheels as well, but I think we might be safer doing that in the many linux containers. I would need to actually think about that. That is later, I think for now `sdist` is probably fine?
- It would usually run the unit tests as well, both locally, and on the resultant packaged software (ever, oops forgot a file? :) )

Perhaps this paints a good picture why we use these tools together for those less familiar. Those are all issues that never would have made it into the code...

Generally speaking, `tox` is something that is run by a developer locally and also by the CI system. It requires some setup effort. I might suggest making a minimally viable thing that doesn't do much, and incrementally adding things above as they are addressed (or refreshed in the case of rtd). It integrate nicely with the other CI systems we have.

**Comment by janden** [comment]
This would be very useful.

>  think for now sdist is probably fine?

Yeah I don't believe any ASPIRE code needs to be compiled currently, so it makes sense to do that.

> Generally speaking, tox is something that is run by a developer locally and also by the CI system. It requires some setup effort. I might suggest making a minimally viable thing that doesn't do much, and incrementally adding things above as they are addressed (or refreshed in the case of rtd). It integrate nicely with the other CI systems we have.

Yes that makes sense. So would all our CI scripts just be replaced by a `tox` invocation?

**Comment by garrettwrong** [comment]
Not exactly, they're distinct systems but intimately related.  Some CI system would need to run `tox`, but a lot of the setup and commands would be run by the tox invocation.  This has the effect of making the CI job scripts "lighter" in code (some might just be as simple as call `tox` in a container with a checkout of the code).

**Comment by janden** [comment]
Right. That should cut down on a lot of duplication, then. Sounds like it's all upsides.

**Comment by garrettwrong** [comment]
Closed by #313
