### ISSUE TITLE
voltage to wave-length function

### ISSUE THREAD

**Issue by junchaoxia** [ComputationalCryoEM/ASPIRE-Python#228]
The voltage to wave-length function in the aspire/utils/em.py is based on Matlab Cov3D. There is some inconsistency with the original Matlab code. It need to be changed to `wave_length = 1.22639 / sqrt(voltage*1000 + 0.97845*voltage^2)` and update related unit tests.

**Comment by junchaoxia** [comment]
Tried to use wave_length = 12.2639 / sqrt(voltage*1000 + 0.97845*voltage^2). There are around ~20 unit tests need to rebuild as shown below.  I expect tests from orientation estimation will fail too. Will work on this after PR #163 is merged.  


tests/test_anisotropic_noise.py::SimTestCase::testAnisotropicNoisePSD 
----------------------------------------------------------------------- live log call ------------------------------------------------------------------------
2020/08/24 10:20:14 Applying forward transformations in pipeline
2020/08/24 10:20:14 All forward transformations applied
2020/08/24 10:20:14 Loaded 512 images
2020/08/24 10:20:14 Applying forward transformations in pipeline
2020/08/24 10:20:14 All forward transformations applied
2020/08/24 10:20:14 Loaded 512 images
2020/08/24 10:20:14 Applying forward transformations in pipeline
2020/08/24 10:20:14 All forward transformations applied
2020/08/24 10:20:14 Loaded 512 images
2020/08/24 10:20:14 Applying forward transformations in pipeline
2020/08/24 10:20:14 All forward transformations applied
2020/08/24 10:20:14 Loaded 512 images
FAILED                                                                                                                                                 [ 27%]
tests/test_anisotropic_noise.py::SimTestCase::testAnisotropicNoiseVariance 
----------------------------------------------------------------------- live log call ------------------------------------------------------------------------
2020/08/24 10:20:14 Applying forward transformations in pipeline
2020/08/24 10:20:14 All forward transformations applied
2020/08/24 10:20:14 Loaded 512 images
2020/08/24 10:20:14 Applying forward transformations in pipeline
2020/08/24 10:20:14 All forward transformations applied
2020/08/24 10:20:14 Loaded 512 images
FAILED          

 tests/test_covar2d.py::Cov2DTestCase::test03GetMeanCTF 
----------------------------------------------------------------------- live log call ------------------------------------------------------------------------
2020/08/24 10:21:50 Expanding 2D image in a frequency-domain Fourier–Bessel basis using the fast method.
2020/08/24 10:21:50 Caching source images
FAILED                                                                                                                                                 [ 42%]
tests/test_covar2d.py::Cov2DTestCase::test04GetCovarCTF 
----------------------------------------------------------------------- live log call ------------------------------------------------------------------------
2020/08/24 10:21:50 Expanding 2D image in a frequency-domain Fourier–Bessel basis using the fast method.
2020/08/24 10:21:50 Caching source images
FAILED                                                                                                                                                 [ 43%]
tests/test_covar2d.py::Cov2DTestCase::test05GetCovarCTFShrink 
----------------------------------------------------------------------- live log call ------------------------------------------------------------------------
2020/08/24 10:21:50 Expanding 2D image in a frequency-domain Fourier–Bessel basis using the fast method.
2020/08/24 10:21:50 Caching source images
FAILED                                                                                                                                                 [ 43%]
tests/test_covar2d.py::Cov2DTestCase::test06GetCWFCoeffs 
----------------------------------------------------------------------- live log call ------------------------------------------------------------------------
2020/08/24 10:21:50 Expanding 2D image in a frequency-domain Fourier–Bessel basis using the fast method.
2020/08/24 10:21:50 Caching source images
FAILED                                                                                                                                                 [ 44%]
tests/test_covar2d.py::Cov2DTestCase::test07GetCWFCoeffsIdentityCTF 
----------------------------------------------------------------------- live log call ------------------------------------------------------------------------
2020/08/24 10:21:50 Expanding 2D image in a frequency-domain Fourier–Bessel basis using the fast method.
2020/08/24 10:21:50 Caching source images
FAILED     

tests/test_filters.py::SimTestCase::testRadialCTFFilterGrid FAILED                                                                                     [ 51%]
tests/test_filters.py::SimTestCase::testRadialCTFFilterMultiplierGrid FAILED                                                                           [ 52%]

tests/test_imaging.py::ImagingTestCase::testVoltageConversion FAILED                                                                               [ 55%]
tests/test_imaging.py::ImagingTestCase::testWavelengthConversion FAILED                                                                         [ 55%]

tests/test_mean_estimator.py::MeanEstimatorTestCase::testAdjoint 
----------------------------------------------------------------------- live log call ------------------------------------------------------------------------
2020/08/24 10:22:45 Expanding 3D map in a spatial-domain Fourier–Bessel basis using the direct method.
2020/08/24 10:22:45 Applying forward transformations in pipeline
2020/08/24 10:22:45 All forward transformations applied
2020/08/24 10:22:45 Loaded 512 images
2020/08/24 10:22:45 Applying forward transformations in pipeline
2020/08/24 10:22:45 All forward transformations applied
2020/08/24 10:22:45 Loaded 512 images
2020/08/24 10:22:45 Determined adjoint mappings. Shape = (98,)
FAILED                                                                                                                                                 [ 66%]
tests/test_mean_estimator.py::MeanEstimatorTestCase::testEstimate 
----------------------------------------------------------------------- live log call ------------------------------------------------------------------------
2020/08/24 10:22:45 Expanding 3D map in a spatial-domain Fourier–Bessel basis using the direct method.
2020/08/24 10:22:45 Applying forward transformations in pipeline
2020/08/24 10:22:45 All forward transformations applied
2020/08/24 10:22:45 Loaded 512 images
2020/08/24 10:22:45 Applying forward transformations in pipeline
2020/08/24 10:22:45 All forward transformations applied
2020/08/24 10:22:45 Loaded 512 images
2020/08/24 10:22:45 Determined adjoint mappings. Shape = (98,)
2020/08/24 10:22:45 Computing kernel
2020/08/24 10:22:45 Computing non-centered Fourier Transform
2020/08/24 10:22:45 Delta 0.007176340656950733 (target 1.3393771825908104e-07)
2020/08/24 10:22:45 Delta 0.0022926215538396455 (target 1.3393771825908104e-07)
2020/08/24 10:22:45 Delta 0.0007724605029066905 (target 1.3393771825908104e-07)
2020/08/24 10:22:45 Delta 0.0002649758650663551 (target 1.3393771825908104e-07)
2020/08/24 10:22:45 Delta 9.598220603988222e-05 (target 1.3393771825908104e-07)
2020/08/24 10:22:45 Delta 4.150330751352263e-05 (target 1.3393771825908104e-07)
2020/08/24 10:22:46 Delta 1.3033841140165204e-05 (target 1.3393771825908104e-07)
2020/08/24 10:22:46 Delta 4.129751613498951e-06 (target 1.3393771825908104e-07)
2020/08/24 10:22:46 Delta 1.3288889770173327e-06 (target 1.3393771825908104e-07)
2020/08/24 10:22:46 Delta 4.1813004184113e-07 (target 1.3393771825908104e-07)
2020/08/24 10:22:46 Delta 1.5336188806997912e-07 (target 1.3393771825908104e-07)
2020/08/24 10:22:46 Delta 5.060508285904515e-08 (target 1.3393771825908104e-07)
FAILED                                                                                                                                                 [ 67%]
tests/test_mean_estimator.py::MeanEstimatorTestCase::testOptimize1 
----------------------------------------------------------------------- live log call ------------------------------------------------------------------------
2020/08/24 10:22:46 Expanding 3D map in a spatial-domain Fourier–Bessel basis using the direct method.
2020/08/24 10:22:46 Computing kernel
2020/08/24 10:22:46 Computing non-centered Fourier Transform
2020/08/24 10:22:46 Delta 0.059471939416107816 (target 2.019646365141193e-06)
2020/08/24 10:22:46 Delta 0.024348862692341867 (target 2.019646365141193e-06)
2020/08/24 10:22:46 Delta 0.006997895565652818 (target 2.019646365141193e-06)
2020/08/24 10:22:46 Delta 0.002033722455321574 (target 2.019646365141193e-06)
2020/08/24 10:22:46 Delta 0.000597880762382118 (target 2.019646365141193e-06)
2020/08/24 10:22:46 Delta 0.0002232610945154523 (target 2.019646365141193e-06)
2020/08/24 10:22:46 Delta 9.614566065610232e-05 (target 2.019646365141193e-06)
2020/08/24 10:22:46 Delta 3.813972625241194e-05 (target 2.019646365141193e-06)
2020/08/24 10:22:46 Delta 1.181505487553707e-05 (target 2.019646365141193e-06)
2020/08/24 10:22:46 Delta 4.37077462571374e-06 (target 2.019646365141193e-06)
2020/08/24 10:22:46 Delta 1.429992336562861e-06 (target 2.019646365141193e-06)
FAILED                                                                                                                                                 [ 67%]
tests/test_mean_estimator.py::MeanEstimatorTestCase::testOptimize2 
----------------------------------------------------------------------- live log call ------------------------------------------------------------------------
2020/08/24 10:22:46 Expanding 3D map in a spatial-domain Fourier–Bessel basis using the direct method.
2020/08/24 10:22:46 Computing kernel
2020/08/24 10:22:46 Computing non-centered Fourier Transform
2020/08/24 10:22:46 Computing Preconditioner kernel
2020/08/24 10:22:46 Circularizing kernel
2020/08/24 10:22:46 Circularizing dimension 0
2020/08/24 10:22:46 Circularizing dimension 1
2020/08/24 10:22:46 Circularizing dimension 2
2020/08/24 10:22:46 Delta 0.027586704564614737 (target 2.019646365141193e-06)
2020/08/24 10:22:46 Delta 0.009444416016501396 (target 2.019646365141193e-06)
2020/08/24 10:22:46 Delta 0.0027018619157898305 (target 2.019646365141193e-06)
2020/08/24 10:22:46 Delta 0.0007489202679126551 (target 2.019646365141193e-06)
2020/08/24 10:22:46 Delta 0.00019195285564836125 (target 2.019646365141193e-06)
2020/08/24 10:22:46 Delta 4.281786770183731e-05 (target 2.019646365141193e-06)
2020/08/24 10:22:46 Delta 9.310247558056335e-06 (target 2.019646365141193e-06)
2020/08/24 10:22:46 Delta 2.9216059109213806e-06 (target 2.019646365141193e-06)
2020/08/24 10:22:46 Delta 7.47860029445895e-07 (target 2.019646365141193e-06)
FAILED 
 tests/test_simulation.py::SimTestCase::testSimulationImages 
----------------------------------------------------------------------- live log call ------------------------------------------------------------------------
2020/08/24 10:22:47 Appending a NoiseAdder to generation pipeline
FAILED                                                                                                                                                 [ 86%]
tests/test_simulation.py::SimTestCase::testSimulationImagesDownsample 
----------------------------------------------------------------------- live log call ------------------------------------------------------------------------
2020/08/24 10:22:47 Appending a NoiseAdder to generation pipeline
2020/08/24 10:22:47 Setting max. resolution of source = 8
FAILED                                                                                                                                                 [ 86%]
tests/test_simulation.py::SimTestCase::testSimulationImagesNoisy 
----------------------------------------------------------------------- live log call ------------------------------------------------------------------------
2020/08/24 10:22:47 Appending a NoiseAdder to generation pipeline
2020/08/24 10:22:48 Applying forward transformations in pipeline
2020/08/24 10:22:48 All forward transformations applied
2020/08/24 10:22:48 Loaded 512 images
FAILED     

tests/test_white_noise.py::SimTestCase::testWhiteNoise 
----------------------------------------------------------------------- live log call ------------------------------------------------------------------------
2020/08/24 10:22:48 Determining Noise variance in batches of 512
2020/08/24 10:22:48 Applying forward transformations in pipeline
2020/08/24 10:22:48 All forward transformations applied
2020/08/24 10:22:48 Loaded 512 images
2020/08/24 10:22:48 Applying forward transformations in pipeline
2020/08/24 10:22:48 All forward transformations applied
2020/08/24 10:22:48 Loaded 512 images
2020/08/24 10:22:48 Noise variance = 0.00011191855212391985
FAILED

**Comment by janden** [comment]
So these two formulas differ by a factor of ten. Why do we need to change it?

**Comment by junchaoxia** [comment]
@janden I was suggested to use 1.22639 and then 12.2639 during some email communication. The current value in use is  12.2643247. There are decimal  differences for 0.97845 too. These changes are large enough to induce numerical differences to fail the unit tests.

**Comment by janden** [comment]
Ok. So the tests no longer match the hardcoded results? Are they off by a lot? It may be best to leave this until we have more flexible tests. It's also not clear to me that any one of those values are correct.

**Comment by junchaoxia** [comment]
Some unit tests have 1e-4  cutoff and some of them have 1e-7. I agree to leave as it is unless we really have better idea how to rebuild the unit tests easily.

**Comment by garrettwrong** [comment]
Okay so, I think we should check if this formula is correct.  It would be sort of embarrassing if we are publishing the wrong formula just to conform some legacy unit tests.  Maybe it is correct, but I can't tell from the discussion above. Seems suspect.

I think we have other ways of mitigating any unit test issues while having correct formula in the code going forward.

**Comment by j-c-c** [comment]
@garrettwrong 

Okay, after a little investigating it appears the formula, derived from de Bolgrie's formula, with an adjustment for the relativistic effects of the high voltage regime, is

$\lambda = \frac{h}{\sqrt{2me(V + e V^2 / 2 m c^2)}}$

where $h \approx 6.626e{-34}$ is Planck's constant, $m \approx 9.109e{-31}$ is the mass of an electron in kg, $e \approx 1.602e{-19}$ is the charge of an electron in coulombs, $c \approx 3e8$ is the speed of light. $\lambda$ is wavelength in nm and $V$ is volts.

The formula will ultimately depend on how many sig figs we want to use, but I'm seeing the following in a few places on the web and in the matlab code [here](https://github.com/PrincetonUniversity/aspire/blob/e697eee5bb185ab1962f1d6e5becaf9caa277732/projections/class_average/simulation/EWavelength.m):

$\lambda = \frac{12.2639}{\sqrt{1000 kV + 0.97845 kV^2}}$

And the current formula in our codebase is also in the [matlab code](https://github.com/PrincetonUniversity/aspire/blob/e697eee5bb185ab1962f1d6e5becaf9caa277732/projections/cryo_radial_ctf_handle.m):

$\lambda = \frac{12.2643247}{\sqrt{1000kV + 0.978466 kV^2}}$

So I think what we have in the codebase is good up to the choice of rounding.

**Comment by garrettwrong** [comment]
Cool, thanks, this is great!... and way less concerning than the 1.2 vs 12 at the top of the issue.  I can now see how Junchao might have been given/arrived at different values.

Okay, I think we can choose the sig figs to be the closest number in float64... or best available for the constant from some standard [(maybe NIST?)](https://physics.nist.gov/cuu/Constants/) for each value, and compute those two coefficients.  This might be overkill but since you are nearly there, might as well.  So that will yield a formula we can document here.

Minimally we should document the formula in the code as you have done here to start. Then the question will become, if we use that formula in our code, what breaks.  If no current unit test breaks, we should use it.  OTOH, if things break we can make a plan, but we'll need to survey damage first.

**Comment by j-c-c** [comment]
Okay, some follow up here. So it turns out the `voltage_to_wavelength()` method was indeed off by a factor of 10 (that is, if we are going from kV to nm). I've made new functions which are explicit about the scientific constants (obtained from [NIST](https://physics.nist.gov/cuu/Constants/)) and the conversion formula being used:
https://github.com/ComputationalCryoEM/ASPIRE-Python/blob/dfda533ac5738427419db7daa8f292eacbb0db28/src/aspire/operators/filters.py#L34-L77

Results of old vs new:
<img width="272" alt="Screen Shot 2022-10-19 at 4 03 40 PM" src="https://user-images.githubusercontent.com/66811911/196792623-bdc4a383-403a-4c2c-ba5e-901cc49ee4d7.png">

Implementing the correct formulation breaks about 20 of our (hardcoded) tests:
<img width="877" alt="Screen Shot 2022-10-19 at 2 25 13 PM" src="https://user-images.githubusercontent.com/66811911/196773847-1d61956a-e143-4459-8690-c55e068691b4.png">

@janden, just want to get your thoughts on this... is it possible I'm using the wrong units system (SI) here that would account for this factor of 10?

**Comment by j-c-c** [comment]
Ok, one more update. It looks like this method is actually just returning wavelength in angstroms and not nanometers. Will update the docstring and verify the accuracy of the formula (I believe the constants might not be using machine accuracy).

**Comment by garrettwrong** [comment]
Closed by #724
