### ISSUE TITLE
Inplement __str__ for all Xform classes

### ISSUE THREAD

**Issue by junchaoxia** [ComputationalCryoEM/ASPIRE-Python#232]
Currently  the information on the individual pipeline items were printed out something as `<aspire.source.xform.Downsample object at 0x2b112a581f98>`. It will be more friendly if we implement  `__repr__`  for all `Xfrom` classes to generate a short name such as `Downsample`.

**Comment by vineetbansal** [comment]
I'd recommend passing in an optional `name` in the base `Xform` constructor, which falls back to the class name on `None`.

In any case, `__str__` is the one you want to override here, not `__repr__`. It's very rare to better the default `__repr__` for any class (one usually wants the class name and the memory address for debugging purposes anyway).

**Comment by junchaoxia** [comment]
Got it. Changed the title.

**Comment by janden** [comment]
Agreed. In addition to the name, it might be good to include some of the important parameters (downsampling factor for `Downsample`, and so on).

**Comment by junchaoxia** [comment]
The issue has been fixed in PR #253. Closing now.
