### ISSUE TITLE
Xform for a constant scaling or shifting

### ISSUE THREAD

**Issue by junchaoxia** [ComputationalCryoEM/ASPIRE-Python#233]
The implementations of  `Multiply` and  `Shift` Xfrom classes need to take an `ndarray` as input. This assumes each image has different values of scaling and shifting.  It will be better if we **also** have an option to take only a scalar when the values are the same for all images, such as the case below:  

https://github.com/ComputationalCryoEM/ASPIRE-Python/blob/preprocess/src/aspire/source/__init__.py#L431

**Comment by janden** [comment]
Agreed. To be clear, we're not talking about a new `Xform`, just making `Multiply` and `Shift` take a scalar input, correct?

**Comment by junchaoxia** [comment]
Yes. We can avoid creating new classes by the size of input values of scaling and shifting.

**Comment by junchaoxia** [comment]
This issue has been addressed in PR #253. Closing now.
