### ISSUE TITLE
Create unit tests for preprocess steps using pipeline

### ISSUE THREAD

**Issue by junchaoxia** [ComputationalCryoEM/ASPIRE-Python#234]
There are some unit tests for individual functions performing preprocess steps such as tests/test_preprocess.py but not for the applications in pipeline as new framework.

**Comment by garrettwrong** [comment]
In the process of rebasing some work I found that preprocess functions and their pipeline application are not covered by unit tests.  The tutorial does capture the issues I was expecting to see.  It might be nice to have coverage of all the underlying functions and coverage in the pipeline style as suggested by Junchao.

**Comment by junchaoxia** [comment]
This issue has been addressed on PR #234. Closing now.
