### ISSUE TITLE
Ignore C in Simulation if vols is given

### ISSUE THREAD

**Issue by janden** [ComputationalCryoEM/ASPIRE-Python#235]
It doesn't make sense to specify `C` if `vols` is given to `Simulation.__init__`, since the number of maps is determined by `vols.shape[-1]`. So if `vols` is specified, we should override the given `C`.

**Comment by garrettwrong** [comment]
FWIW, we can cover this easily once the volume class is in, something like `len(vols)`, or a more expressive attribute in the class...

**Comment by janden** [comment]
Right that makes sense. Just wanted to put this in so I don't forget.

**Comment by vineetbansal** [comment]
PR #236  for this. Merged to develop.
