### ISSUE TITLE
Missing tests equivalent to tutorial examples

### ISSUE THREAD

**Issue by garrettwrong** [ComputationalCryoEM/ASPIRE-Python#244]
I have noticed different test coverage between cov2d, cov3d, preprocess tutorials and our CI `tests/`.

We should probably find a way to run these as part of CI.  This should both help our code and ensure we are continually shipping working examples.

This has some relationship to #201 , which talks about some modifications I did to the tutorials so they were more effective for scripts/benchmarking during the Hackathon.

**Comment by junchaoxia** [comment]
In general the tutorial examples have higher resolution and more images included for better pictures to demostrate. They need significantly longer time to finish unless we reduce them in the sizes of unit tests. The functions and classes in those examples generally should been included in the unit tests. It might be not necessary to do again. During a previous discussion my thought is to add a simple script to the example folder to rerun them and compare the output values with the predefined. This could be another level of tests in additional to the unit tests.

**Comment by garrettwrong** [comment]
wow. So I responded to this, but its just not worth it anymore.

**Comment by junchaoxia** [comment]
Maybe we should discuss it during the meeting first and choose which way to go.

**Comment by garrettwrong** [comment]
Closed by #246
