### ISSUE TITLE
default preconditioner in CG method 

### ISSUE THREAD

**Issue by junchaoxia** [ComputationalCryoEM/ASPIRE-Python#249]
The current implementation of CG method needs the `identity` as default preconditioner. We should make the CG method working without preconditioner too.

**Comment by janden** [comment]
Well, having the identity as the preconditioner is the same thing as CG without preconditioner. What we need is for this to be the default so that the user doesn't have to specify it. That goes for all the other options, as well.

**Comment by junchaoxia** [comment]
OK. Then we should be fine. In the current version, the `identity` is the default preconditioner, we don't need to specify it. The unit tests have been simplified to use the default setting.  Closing now.
