### ISSUE TITLE
Reduce size of installed package

### ISSUE THREAD

**Issue by vineetbansal** [ComputationalCryoEM/ASPIRE-Python#25]
The sample.star and sample.mrcs files in aspire.data folder can be drastically reduced in size. 2 related issues:

1. Missing images indices in the starfile should be tolerated, through an argument (perhaps have a common `ignore_missing` argument that ignores missing *.mrcs/stack indices.

2. The ApplePicker unit test will have to be rewritten to deal with a much reduced-in-size sample.mrc file.

**Comment by garrettwrong** [comment]
At some point I stripped out the test data from the actual package.  I just confirmed in the v0.8.1 zip it is not there.  Somehow I missed closing this.
