### ISSUE TITLE
saving image crashes for APPLE picking 

### ISSUE THREAD

**Issue by junchaoxia** [ComputationalCryoEM/ASPIRE-Python#257]
Tried to run APPLE module for checking Cupy 1D FFT and found the error as below: 

"""
Traceback (most recent call last):
  File "/home/junchaox/.conda/envs/aspire/lib/python3.6/concurrent/futures/process.py", line 175, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
  File "/tigress/junchaox/software/ASPIRE-Python_basis/src/aspire/apple/apple.py", line 116, in process_micrograph
    misc.imsave(
AttributeError: module 'scipy.misc' has no attribute 'imsave'
"""

It seems that scipy.misc.imsave has been deprecated since SciPy 1.0, and was removed in SciPy 1.2 as shown in the discussion link,  https://stackoverflow.com/questions/57253048/scipy-misc-has-no-attribute-imsave
 
`imsave` or `imwrite` from `imageio` package can be the replacement.

**Comment by janden** [comment]
Let's not add another dependency unless absolutely necessary (we already have too many). From what I understand, we already have pillow. `PIL.save` fits the requirements, so let's use that.

**Comment by junchaoxia** [comment]
@janden Didn't notice PIL package is used. It looks that it is included in the picker.py file but not in the setup.py or requirements.txt. I will try to use it if it can generate the same image.

**Comment by junchaoxia** [comment]
This issue has been fixed in PR #259. Closing now.
