### ISSUE TITLE
Create facade modules for FFTs

### ISSUE THREAD

**Issue by janden** [ComputationalCryoEM/ASPIRE-Python#258]
As part of fixin #127, we should set up a separate facade structure for FFTs. The setup in `aspire.utils.numeric` currently mixes both basic linear algebra and FFTs into the same module. Instead, we should have one set of modules for non-FFT functionality (currently cupy and numpy) and one set of modules for FFTs (cupy, scipy, and pyfftw). These would be controlled by separate flags in the config file.

**Comment by junchaoxia** [comment]
The feature has been implemented in PR #269. Closing now.
