### ISSUE TITLE
Dependencies management

### ISSUE THREAD

**Issue by janden** [ComputationalCryoEM/ASPIRE-Python#264]
Following up on the discussion in #259. Currently, dependencies are listed in three places: `environment.yml`, `requirements.txt`, and `setup.py`. We have `environment.yml` including `requirements.txt` but the dependencies in `setup.py` are independent of the others. Since the “official” installation method is through `pip install`, we should only be listing dependencies there. If it's absolutely necessary to have the other files, we need to think of a way to read them into `setup.py` so that there is only one list of dependencies used regardless of installation method.

**Comment by garrettwrong** [comment]
FWIW, in `develop` there is no `requirements.txt`.  Also, in develop `environment.yml` is trivial, just assigning a name more/less, then calling pip. There is only one place that should hold python deps for the time being (in and ahead of develop), and that is `setup.py`.

That this is causing confusion is pretty much why we shouldn't over complicate things at this stage of this software and with the resources available to the project.

**Comment by janden** [comment]
Ok thank you. I didn't see that this was already resolved in `develop`. Closing.
