### ISSUE TITLE
Deprecate vol2img

### ISSUE THREAD

**Issue by garrettwrong** [ComputationalCryoEM/ASPIRE-Python#265]
Following #231, the usage of `vol2img` will be reduced to it's own unit test and generation of `imgs_clean` in `test_covar2d.py`.  Other cases have been replaced by Volume.project.  However, this case I had trouble reproducing.  I probably wasn't using it correctly, but if I was this may require some care and regeneration of test data.

Following that `vol2img` should be totally removed.

**Comment by garrettwrong** [comment]
If 245 can naturally close this out that would be great, thanks!

**Comment by junchaoxia** [comment]
The vol2img function was removed in PR #245. Closing now.
