### ISSUE TITLE
Misc col to row conversion 

### ISSUE THREAD

**Issue by garrettwrong** [ComputationalCryoEM/ASPIRE-Python#268]
Some remaining tasks from #231.  I've made a few separate issues, but the following are items directly related to axis ordering work.

- [x] Likely want to convert some errors/warning I added to debug level messages. Others should go away as code conformance improves. Should discuss at team meeting what we want to do (maybe noisy is okay, maybe we want to work either way..?)
- [x] Revisit `kernel.py` and related code in `estimation/__init__.py`, `fb_3d` (tranposes in src_backward).  This would be a large part towards completing the transition towards using Volume class structure, so consolidated that task here.
- [x] covar3d.py's cg section. I think I'll need to repack the mock cg data, or just let cg actually run (this doesn't bother me, I think)
- [x] I've marked most altered places with the comment #RCOPT for debugging. This is temporary and should be removed as one of the final steps.

**Comment by garrettwrong** [comment]
@janden , can you remind me if `fb_3d` was one of the modules that was going to be removed? (I might try to revisit some of that today depending on how the morning goes).  Thanks.

**Comment by junchaoxia** [comment]
According to our previous discussion, we might remove the slower versions of image expanding methods such as fb_2d.py,  fb_3d.py,  and pswf_2d.py. As a compete set of image expanding methods for academic research, personally I would like them to stay but can spend less time for updating.

**Comment by garrettwrong** [comment]
Okay. `ffb_3d` and `fb_3d` both have a lot of code that should get totally rewritten. The initial conversion to python is more perverse because of the additional dimension.  I'm trying to understand what the core components are. Since we have limited resources to perform the work, I want to target the components that are going to bring value, not large blocks of unused code.

It sounds like even if it stays, it doesn't merit my attention. Thanks.

**Comment by janden** [comment]
Yes the slow methods should go, provided that the fast methods exist and provide equivalent results. So that would be `fb_2d`, `fb_3d` and `pswf_2d`.

**Comment by garrettwrong** [comment]
There are still some RCOPTs around, but they are mainly in the unit tests and some tricky code areas to indicate possible trouble areas.  Otherwise changes have been integrated, closing.
