### ISSUE TITLE
Default axes arguments for FFT facades

### ISSUE THREAD

**Issue by janden** [ComputationalCryoEM/ASPIRE-Python#280]
Right now, we have default arguments for `fft`, `ifft` (`axes=-1`), `fft2`, `ifft2` (`axes=(0, 1)`), but not for `fftn` or `ifftn`. We should decide whether we want to keep them for `fft`/`ifft` and `fft2`/`ifft2` (I think we do). If so, we should probably change the default for `fft2`/`ifft2` to `axes=(-2, -1)` to account for the row-major convention (and this also agrees with NP/CP/PyFFTW default args).

**Comment by junchaoxia** [comment]
The issue has been fixed in PR #258. Closing now.
