### ISSUE TITLE
Unit Test for basic Starfile IO

### ISSUE THREAD

**Issue by garrettwrong** [ComputationalCryoEM/ASPIRE-Python#292]
In #291 we found some missing test coverage.  I think a comprehensive end to end script is being constructed, but it would be good to have an isolated test covering basic IO.

I think the existing handful of IO tests cover the `Starfile` class, and include read/write roundtrip.  OTOH it seems in practice we're using a wrapper written outside of the class. This wrapper is called `save_star` and is untested.  It is used in exactly one place `commands/denoise.py`, a larger CLI API call for which there is currently zero test coverage.  `save_star` has multiple modes of invocation, but currently only `single` is used, in the aforementioned case.

**Comment by garrettwrong** [comment]
I thought this would be pretty trivial, and I was able to invoke the `save_star` wrapper with an image source object... However, upon inspection it appears we may not be writing valid mrc files (if I am to believe `mrcfile` package); this has become less trivial, but I think it is something we'll need to do if this is a standard file format in this field.

**Comment by junchaoxia** [comment]
It is worth of thinking about this function again.  If I remember correctly this `save_star` function was suggested to move to IO folder last year. It not only creates and saves the star file from the metadata of source object but also save corresponding standard mrcs files for output such as denoised images. It should be a general function for any submodules requiring output star and images for future analysis. In stead of using the same function, it might be better to derive it in different source classes if we want the star file have additional different information for different submodules.

**Comment by janden** [comment]
> However, upon inspection it appears we may not be writing valid mrc files

Ok. That's a problem. Maybe add as a separate issue?

> In stead of using the same function, it might be better to derive it in different source classes if we want the star file have additional different information for different submodules.

I don't quite understand. What different information would we want to save in the different source classes?

**Comment by junchaoxia** [comment]
Not sure what the problem of saving mrcs files. I was able to get mrcs files from the `denoise` click command. Currently the `save_star` only includes '_rlnImageName' column and the paths to mrc files. For other submodules we might save CFT information and/or orientational angles too.

**Comment by garrettwrong** [comment]
Yes the code wrote files for me too, but I got side tracked when I inspected their contents.  Anyway, we were not setting header details.  From reading the documentation of mrcfile package, the common usage via `set_data` would do that automatically, but in this case we were not using `set_data`. Instead we were opening with some details, and setting array data using a the slice assignment syntax.  I replaced a redundant call the `mrc.close()` with a header setting call and the file seemed fine after that.  No big deal.

I'm not sure what the motivation of other STAR file stuff would be beyond potential integration with another software. I wouldn't invest in it atm (besides making sure what exists works and is tested), but I guess it's something that might become relevant later. TBH if the popular software accepts non domain specific formats, it might be wiser to focus in that direction, but that is a totally different topic and doesn't belong in this PR about adding a unit test.

**Comment by janden** [comment]
> Anyway, we were not setting header details.

Ok. We need to be doing that.

> I'm not sure what the motivation of other STAR file stuff would be beyond potential integration with another software.

This is the format used by one of the main software packages (Relion), so we need it to work properly for importing and exporting data.

**Comment by junchaoxia** [comment]
Try to add more information. When the `save_mode` is single, it will save all images from different batches to one mrc file even if it is larger than the memory, the major motivation that we use the `mrcfile.new_mmap` function. if `save_mode` is not single, it will same one mrc file for each batch of images. We even developed more complicated cases last year, saving the mrc files according to the sizes from original Relion mrc files, but it was removed. I think the simplyest tests are using simulation class to generate images, save to files in different modes and reload them to compare.

**Comment by garrettwrong** [comment]
Closed by #300.
