### ISSUE TITLE
Unit Tests BatchedRotCov2D

### ISSUE THREAD

**Issue by garrettwrong** [ComputationalCryoEM/ASPIRE-Python#294]
In #291 we found there appear to be some code paths in BatchedRotCov2d that are not covered by `test_batched_covar2d.py`, particularly `get_cwf_coeffs`.  Probably this would involve mimicking the tests for the non batched `test_covar2d.py`.

Usage is limited to `DenoiserCov2D` which itself is limited to `commands/denoise.py`, see #293 .

**Comment by junchaoxia** [comment]
The related unit test has been added in PR #291. Closing now.

**Comment by janden** [comment]
Were there other code paths that need testing or was it just `get_cwf_coeffs`?
