### ISSUE TITLE
IndexedXform not being used where it should?

### ISSUE THREAD

**Issue by vineetbansal** [ComputationalCryoEM/ASPIRE-Python#297]
I think we talked about this once - there's an `IndexedXform` that does what you're doing here, and it doesn't care what the actual `Xform` is. The problem with this approach here is that you'l end up duplicating this logic in every Xform where you want to apply different operations grouped by indices. Is this only place where you're storing the indices where you want to apply the Xform? We may open up a new issue into this.

_Originally posted by @vineetbansal in https://github.com/ComputationalCryoEM/ASPIRE-Python/pull/295#discussion_r504829884_

**Comment by junchaoxia** [comment]
Changed to use IdexedXform in PR #305. Closing now.
