### ISSUE TITLE
Add tutorial examples using experimental dataset 

### ISSUE THREAD

**Issue by junchaoxia** [ComputationalCryoEM/ASPIRE-Python#299]
Currently we have tutorial examples for preprocess steps, Cov2D, Cov3D and orientation estimation by generating simulation data. These examples are good to understand code for developers and users. For manipulating experimental data set, running CLICK scripts under `src/aspire/commands` is necessary. It will be helpful if we have corresponding simplified scripts under tutorial examples for experimental dataset.

**Comment by janden** [comment]
The click interface may change, so let's keep these tutorials as Python scripts for now.

**Comment by junchaoxia** [comment]
The tutorial examples for experimental datasets have been added in PR #302, #302, #348 and #354 for the submodules merged into the new framework. Closing now.
