### ISSUE TITLE
Batched covar2d CWF coefficient resolution 

### ISSUE THREAD

**Issue by garrettwrong** [ComputationalCryoEM/ASPIRE-Python#307]
There appears to be a larger than usual disagreement between the `BatchedRotCov2D` and `RotCov2D` CWF coefficients (`get_cwf_coeffs`) when changing between `float32` and `float64`.

This is currently known as:
https://github.com/ComputationalCryoEM/ASPIRE-Python/blob/09eab437033bbbe6fb296d7d3301467e03b3772f/tests/test_batched_covar2d.py#L129

On my machine I respectively get the following `max(abs(diff))`:
2.8E-4 vs 1.7E-11

Most other ASPIRE methods can achieve E-6, with a select few at E-5 in singles.  It would be good to identify where this diminished resolution is coming from. Whether it is a bug, artifact, or reasonable I am unsure at this time.

**Comment by garrettwrong** [comment]
I sent some debugging code through our CI and it reported the following on ubuntu 16.04.

```
covar diff 1.6391277313232422e-07
Observered delta with covar_bcov2d 1.52587890625e-05
Observered delta with covar_nbcov2d 0.01407623291015625
```
`Covar diff` in this case is np.max(np.abs(covar_bcov2d - covar_nbcov2d )), that is batched vs non batched . The deltas are the cwf coeff as compared to the non batched algorithm.

I'll need to look more to determine if this is instability or a bug.

**Comment by janden** [comment]
I don't quite understand, if the delta compares the CWF coeffs between the batched and non-batched variants, why are there two deltas?

**Comment by garrettwrong** [comment]
The second delta case (0.01) is using the covariance from the BatchRotCov2d, as the code was implemented.

The first delta case (1.5e-5) I am forcing to use the covariance from the non batched. I was trying to narrow down what might be sensitive.

**Comment by garrettwrong** [comment]
After discussion with Joakim, in today's meeting we looked at the distribution of eigvals for sig_var_coef in BatchedRotCov2D with a hack:

```
diff --git a/src/aspire/covariance/covar2d.py b/src/aspire/covariance/covar2d.py
index 9a4772b..52395a9 100644
--- a/src/aspire/covariance/covar2d.py
+++ b/src/aspire/covariance/covar2d.py
@@ -742,6 +742,12 @@ class BatchedRotCov2D(RotCov2D):
             ctf_fb_k = ctf_fb[k]
             ctf_fb_k_t = ctf_fb_k.T
             sig_covar_coeff = ctf_fb_k @ covar_coeff @ ctf_fb_k_t
+            from matplotlib import pyplot as plt
+            XXX = np.sort(np.concatenate([np.linalg.eigvals(b).flatten() for b in sig_covar_coeff]))
+            plt.hist(XXX)
+            plt.show()
```

I found there is large concentrations of negative and near zero eigenvalues.  This supports a concern that we are ill conditioned.

We discussed checking whether we are in fact positive definite and conditioning, adding warnings etc.

To continue diagnosis, @junchaoxia to backtrace code to identify places that are contributing to the condition problem.
