### ISSUE TITLE
Add Filter.sign method

### ISSUE THREAD

**Issue by janden** [ComputationalCryoEM/ASPIRE-Python#308]
As a shorthand for `LambdaFilter(self, np.sign)`.

**Comment by junchaoxia** [comment]
@janden Could you confirm that you like to use Filter.sign method instead of LambaFilter so we can remove LambdaFilter?

**Comment by janden** [comment]
No, we just want a method `Filter.sign` that returns `LambdaFilter(self, np.sign)`.

**Comment by j-c-c** [comment]
@janden Do we want `Filter.sign()` to be a `Filter` object that can then be evaluated (ie. `Filter.sign().evaluate(omega)`) to retrieve the signs of the evaluation, or do we want `Filter.sign()` to return the signs?

**Comment by garrettwrong** [comment]
I vaguely remember discussing this at the time and I think it was the latter. (Watch me have foot in mouth, heh)

If that is the case I think we can decorate a method in the base class with `@property` so the invocation would just be `X.sign` for any subclass of `Filter`.

**Comment by garrettwrong** [comment]
A follow up task might be to replace the `LambdaFilter(.*, np.sign)` in phase flip code... with your improved syntax.

**Comment by j-c-c** [comment]
@garrettwrong Ok, per our conversation, I will use the `@property` decorator and `Filter.sign` will return a filter that can later be evaluated to obtain the signs.
