### ISSUE TITLE
Python 3.9

### ISSUE THREAD

**Issue by garrettwrong** [ComputationalCryoEM/ASPIRE-Python#320]
Following #313 we will have the product of python 3.6 3.7 3.8 x stable,dev environments under test with travis ci.  Currently some packages are not available for python 3.9 which was just released.  Instead of working around that temporarily, I think we can just wait to re-evaluate and add these lines at a later date.

```
    # Some 3.9 depends are not yet avail, 11/06/2020.
    # - python: 3.9
    #   env:
    #     - TOXENV=py39-stable
    #     - TOXENV=py39-dev
```

**Comment by janden** [comment]
Makes sense. From what I understand, 3.9 shipped just over a month ago so it'll be a while before everything shakes out. When it does, we'll be ready.

**Comment by garrettwrong** [comment]
User reported they tried to install against python 3.9 (osx I beleive) and got an error. While we're not officially supporting 3.9 yet, I thought I'd take a look at the current state of the install.

```
conda create --name aspire_py39 python=3.9 -y
conda activate aspire_py39
pip install -e ".[dev]"
Obtaining file:///home/garrett/work/ASPIRE-Python.385
Requirement already satisfied: setuptools>=0.41 in /home/garrett/anaconda3/envs/aspire_py39/lib/python3.9/site-packages (from aspire==0.6.2) (52.0.0.post20210125)
Collecting numpy==1.16
  Using cached numpy-1.16.0.zip (5.1 MB)
Collecting numpydoc==0.7.0
  Using cached numpydoc-0.7.0.tar.gz (19 kB)
Collecting pandas==0.25.3
  Using cached pandas-0.25.3.tar.gz (12.6 MB)
Collecting scikit-image==0.16.2
  Downloading scikit-image-0.16.2.tar.gz (28.9 MB)
     |████████████████████████████████| 28.9 MB 840 kB/s 
    ERROR: Command errored out with exit status 1:
     command: /home/garrett/anaconda3/envs/aspire_py39/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-86x4zudf/scikit-image_7f7569a17838472b8edf309d103c46b5/setup.py'"'"'; __file__='"'"'/tmp/pip-install-86x4zudf/scikit-image_7f7569a17838472b8edf309d103c46b5/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-c112qmlh
         cwd: /tmp/pip-install-86x4zudf/scikit-image_7f7569a17838472b8edf309d103c46b5/
    Complete output (7 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-86x4zudf/scikit-image_7f7569a17838472b8edf309d103c46b5/setup.py", line 243, in <module>
        'build_ext': openmp_build_ext(),
      File "/tmp/pip-install-86x4zudf/scikit-image_7f7569a17838472b8edf309d103c46b5/setup.py", line 71, in openmp_build_ext
        from numpy.distutils.command.build_ext import build_ext
    ModuleNotFoundError: No module named 'numpy'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

I tracked that specific error down to scikit-image.  Older versions demand that numpy is installed prior to attempting their install. This was fixed in their upstream, but that requires upgrading our numpy.  If I update that package, we have similar problems with scipy :). Joy.

So I upgraded the trio and that appears to succeed locally. I'll push a branch with these to see what happens across out CI.  Might as well consider if this is a good time to review other depends for upgrade...

**Comment by garrettwrong** [comment]
(pandas would be one we might want to upgrade, it is really slow to build a wheel for it locally...)

**Comment by garrettwrong** [comment]
I spoke too soon, the install still fails at the last step for pyfftw.  They provide wheels for 3.6 3.7 3.8, but not for 3.9. So it tries to build from source, but their packaging has a bug (it doesn't install cython ahead of time...). I'll try to get some idea what their plan is here.

**Comment by janden** [comment]
> I spoke too soon, the install still fails at the last step for pyfftw. They provide wheels for 3.6 3.7 3.8, but not for 3.9. So it tries to build from source, but their packaging has a bug (it doesn't install cython ahead of time...). I'll try to get some idea what their plan is here.

You're talking about skimage? Yeah would make sense to wait for them to release py39 wheels then.

**Comment by garrettwrong** [comment]
both skimage and pyfftw, several packages have issues. It's a mess. I was able to get around skimage by bumping numpy (which requires bumping scipy.)

There are limited versions of packages that will support all the python versions... and the newer pip is getting more strict about this...

**Comment by janden** [comment]
> both skimage and pyfftw, several packages have issues. It's a mess. I was able to get around skimage by bumping numpy (which requires bumping scipy.)

Ok got it.

> There are limited versions of packages that will support all the python versions... and the newer pip is getting more strict about this...

Right. But on the other hand, we don't necessarily want to drop support for 3.6 since it's still in use (it's default in ubuntu 18.04 which will be around for a few more years). For now, it's fine to hold off on py39 support, though.

**Comment by garrettwrong** [comment]
I agree we shouldn't drop it. OTOH I don't think the versioning issue is going to go away with time...  it will get worse, especially if I ignore it. Python 3 crowd is totally out of control with this stuff, unfortunately.

I _think_(tbd) I was able to find _one_ intersection of versions that will support all the platforms, but it requires relaxing the scikit-image version to >=0.17  . Any other combo, or newer numpy/scipy will require dropping 3.6. Some of our dependencies (scikit) 
 have already dropped 3.6 unfortunately. So that's great.
 
 Some good news is that I beat on the new CI a lot this morning and it seems to be taking it pretty well.

**Comment by janden** [comment]
All right. Looks like 3.6 will be EOL in December, so if we have to, we may be able to drop it sometime this year. On the other hand, not sure how Ubuntu 18.04 is dealing with this since they're going to be around until 2023. Do they maintain their own fork, then?

**Comment by garrettwrong** [comment]
I got some GH notifications that PyFFTW has been updated towards 3.9 and 3.10 so I am going to try and move this forward.

**Comment by garrettwrong** [comment]
3.9 and 3.10 are now under GH actions CI.
