### ISSUE TITLE
Run unit tests in both singles and doubles

### ISSUE THREAD

**Issue by garrettwrong** [ComputationalCryoEM/ASPIRE-Python#321]
I've constructed most of the unit tests to admit either single or double precision using a top level dtype variable and soon we'll have tox integrated.  It would be a worth while project to run the tests in both modes automatically in CI, with the ability to run the same sort of thing locally.

One way to do this is:

1. Create a util function that detects an environment variable and returns a dtype (defaulting to what our current default is).
2. Use this util function in the setup method of applicable unit tests.
3. Create a tox entry that will set that environment variable and run our usual tests.

**Comment by janden** [comment]
Why wouldn't we want the default be to run in both precisions (by parametrizing the tests)?

**Comment by garrettwrong** [comment]
It would roughly double the run time unless we add logic to skip parameterizing sometimes (but I'm not sure what that would look like).

This is just a different way to achieve the same thing.

I'm not a huge fan of the parameterization/subtest framework for python3, but we could certainly use it.  It might come down to if you a) expect to have multiple parameters, b) don't expect to have too many corner cases to code around where you do not wish to (or cannot) run.

What I was proposing would just be an additional (tox) environment, which ideally would take the same amount of time and be able to run as a parallel job.

Def open to ideas either way. Mainly would like to see tests run both ways. We found a lot switching between dtypes...

**Comment by janden** [comment]
How much is the total test suite for you right now, locally? I guess as long as it's possible to run both precisions easily on a local machine with tox, it doesn't matter so much. Just want to make sure this is not a CI-only setup.

**Comment by garrettwrong** [comment]
tox isn't CI only at all.. `tox -e py36-double` or something like that, or `MYFLAG=double pytest`.

5 minutes.  I think it is about 15 minutes on a typical PU machine.

I agree. I don't mind writing an example of both and picking what is best for the project, they're small.

**Comment by janden** [comment]
Right. That makes sense then.

**Comment by garrettwrong** [comment]
I think we've ended up doing this via pytest fixtures in the end. Closing.
