### ISSUE TITLE
APPLE over subscription

### ISSUE THREAD

**Issue by garrettwrong** [ComputationalCryoEM/ASPIRE-Python#324]
When I tried to run apple command with a real dataset (10017 dataset of 84 data files) it just about brought my machine down...  This is because there are multiple forms of parallelism implemented.  On my desktop, the default config spawns 4 processes for apple, each of which tries to consume more than the entire CPU at the same time.

Note, if I sigkill the main parent process the children will keep running until completion, which is also not ideal but can be sometimes expected depending on how the multiprocessing is implemented (unfortunately).

Regardless, this is too aggressive for a default.  I think we'll need to map out all points of parallelism in the apple code and resolve defaults across the different configurations that make more sense, or adapt to different machines bettter.  For multi socket machines it could theoretically make sense to have different tiers, but only if you're pinning things based on numa, which is way out of scope for basic ASPIRE usage. That would be a good project for someone getting into hpc one day when ASPIRE is mature.

The easiest thing to do for a laptop/desktop user is to make apple n_processes=1, which appears to be faster than oversubscribing for me. I'll try to run the defaults later when I don't need to use the machine anymore to confirm...

**Comment by junchaoxia** [comment]
Yes. n_proccesses=4 is default setting for running on HPC cluster for GPU Hackathon las year. Eventually we should have final command script to read in user choices and override the parameters on config.ini, depending on where the user is going to run the jobs.

**Comment by garrettwrong** [comment]
The problem is that this doesn't result in 4 cores... On my machine this results in something like 24 cores of work plus who knows how many threads... on a 4c machine.  That's absurd; we shouldn't be shipping a fork bomb.

Our defaults should just do something reasonable on most machines, not crash things. Its just an oversight, no big deal.

**Comment by garrettwrong** [comment]
I'm sure we would have caught this if we tested a mode other than the single `mrc_file`.

**Comment by janden** [comment]
Agreed that we should bring the default number of processes down to one. Do we know how many threads it will spawn in that case?

The other important question here is why do we have both multi-processing and multi-threading in the first place?

**Comment by garrettwrong** [comment]
On my machine with `nworkers=1` I can see many threads (17 here) and four processes. This is a full load, using most of the processing power on this consumer chip. I'll make a PR with the one line config change, but this probably deserves a real look to document what the code is doing and where resources are going.  Probably the threading is builtin to some other methods already (side eyeing SVM)...

```
pstree -pt 2256121
python(2256121)─┬─python(2256138)─┬─{python}(2256141)
                │                 ├─{python}(2256142)
                │                 ├─{python}(2256143)
                │                 ├─{python}(2256144)
                │                 ├─{python}(2256145)
                │                 ├─{python}(2256146)
                │                 ├─{python}(2256147)
                │                 ├─{python}(2256150)
                │                 ├─{python}(2256151)
                │                 ├─{python}(2256189)
                │                 ├─{python}(2256190)
                │                 ├─{python}(2256191)
                │                 ├─{python}(2256192)
                │                 ├─{python}(2257178)
                │                 ├─{python}(2257179)
                │                 ├─{python}(2257180)
                │                 └─{python}(2257181)
                ├─{python}(2256137)
                ├─{python}(2256139)
                └─{python}(2256140)
```

**Comment by garrettwrong** [comment]
following #513 , the process and thread settings should be exposed in both the class and CLI interfaces.
