### ISSUE TITLE
Duplicated large data files

### ISSUE THREAD

**Issue by garrettwrong** [ComputationalCryoEM/ASPIRE-Python#349]
Two 65MB files `tutorials/data/falcon_2012_06_12-14_33_35_0.mrc ` and `tests/saved_test_data/sample.mrc` are the same file.    They were both added in the same commit (370b1aa). 

This results in our PyPI package being around 110MB.  Unfortunately this exceeded the limit for PyPI.

We never encountered this before because the software hasn't successfully pushed a release there since Jul 30, 2019.

Last time I hit this the policy was 60MB. Removing that file leaves us at 63MB for the tar.gz. I'll try to ask the PyPI folks to extend the limit for us.  I think given what we do we can probably justify shipping one real mrc data file...

**Comment by junchaoxia** [comment]
I have impression that we probably don't want the tests folder going to release package. The tutorial folder also can be distributed separately. That is the reason we put them in separate folders. Namely the release PyPI version only needs to contain the ASPIRE source code.  @janden should decide.

**Comment by garrettwrong** [comment]
Not sure what that has to do with including the same large file twice. 

I guess we didn't satisfy that reasoning at the time.  

I can remove these folders from the manifest. No big deal. This is why I scheduled extra time... so we can still be successful.

**Comment by junchaoxia** [comment]
Maybe the user doesn't want to download both  tests and tutorials folders. I think we tried to make these two folders independent to each other. I believe these two folders will include more dataset in future. So it is a good idea not to include them in the release.

**Comment by garrettwrong** [comment]
Nothing about what you just said makes sense except the not including them part (although this is not a default practice).

**Comment by janden** [comment]
Agreed that we should remove one of these. No need to have the same data in two places.

Ultimately, we want to move away from storing these files in the repo at all and just generate our test data. For the tutorial, we can have the user download the sample data separately from git-lfs, zenodo, etc.

**Comment by garrettwrong** [comment]
Closed by #350
