### ISSUE TITLE
Deprecating Travis CI

### ISSUE THREAD

**Issue by garrettwrong** [ComputationalCryoEM/ASPIRE-Python#358]
Travis is resource constrained for free projects (ie non-paying customers).  A project with the requirements and usage of ours does not fit well into their (or really anyone's) free tier.  This was made increasingly apparent after Nov 1st policy/QoS changes.  Despite waiting now and then, I was able to run 12 total Travis CI round trips yesterday (each having several independent tests/VMs), but some days it is hard to get that many through.

While my personal preference is very much towards Gitlab, from talking with another Princeton RSE who is interested in these things, he is suggesting Github Actions; mainly because his project is already using it :D.

I think we should give it a try.  By that I mean, make a branch where we migrate the `tox` framework of tests to GH Actions instead of Travis.  This will give us a taste of the syntax/administration.  There are two main things I would like to understand better wrt GH Actions, because I have not used them before... First performance/limitations. Second is how well their self hosted (and in particular their self hosted GPU) runners work relative to my experience from Gitlab. With that information we could probably make a good decision about what to do going forward. 

There are also other platforms (circle-ci etc), and the PU Jenkins, but I think that would be more effort to manage. I am expecting the integration of GH's own services to be better than multiple products.

**Comment by janden** [comment]
Makes sense. What would be the drawback of using GitLab? I don't have any experience with GitLab or GH Actions, so it's hard to make a good decision here.

I agree that it would make sense to test things out before going further. Since you've already worked with GitLab, we can discuss pros and cons after that.

We do need to move away from Travis, though, that's clear.

**Comment by garrettwrong** [comment]
We'd need to put up a machine to run things on...  because we would burn through their free minutes (1-2k a month) too quickly...  That and there is one less integration to manage.

**Comment by garrettwrong** [comment]
With that said, GH has tried to mimic the same, so theoretically we could do the same things with GH actions now if it came to it.

**Comment by janden** [comment]
Ok got it. Looking at the GL website, looks like it's closer to 400 minutes per month for the free tier, which isn't going to cut it… Don't know how many minutes we get from GH actions, but I'm guessing it's in the same range (and we have to share it with the rest of PU), so it looks like for both GL and GH we'd have to self-host runners. At that point, do we gain that much compared to using the existing PU Jenkins server?

We also have to remember that the servers on the math network are isolated from the internet so we can't use those. Maybe there are other machines at RSE we could use?

**Comment by garrettwrong** [comment]
Oh, GL must have also reduced it quite a bit since I last had an issue.

I think there is some situation with GH that yields more time for PU projects because we are enterprise GH, but I'm not certain. Lets not worry about it yet.. I'll try to get some clarification.

IIRC the Jenkins is just the server, which isn't the part we need :). Jenkins administration is a FT job (or two). I would avoid it. It isn't going to solve this problem. Its true it is administered, but just the part that we can get anywhere else for free...

**Comment by garrettwrong** [comment]
(I just remembered ComputationalCryoEM is not under PU, so PU's GH status might not actually be relevant to this project).

**Comment by junchaoxia** [comment]
When I tried to enable the debug mode, I was suggested by the Travis supporter to move tavis-ci.org repo to  travis-ci.com to avoid the queue. There are still free things available. But I am not sure how many of them. I will forward the email to you and we can discuss tomorrow. Probably we can do through Azure Pipeline too.

**Comment by janden** [comment]
Ok. So let's try travis-ci.com for now, see how GH Actions works out and then evaluate whether we want to move to GL or GH Actions.

**Comment by garrettwrong** [comment]
GHA is live now.  First successful automated run on `develop` completed this morning. We can consider the self hosted approaches in the background. Closing.

**Comment by garrettwrong** [comment]
(#376)
