### ISSUE TITLE
Alternate implementations of im_translate

### ISSUE THREAD

**Issue by vineetbansal** [ComputationalCryoEM/ASPIRE-Python#36]
We have two alternate implementations of `im_translate` - `_im_translate` (ported by Vineet directly from Cov3D), and `_im_translate2` (from Yoel's Python code).

They probably amount to the same thing, but `_im_translate2` is running 40-50% faster (probably because it's using numpy fft instead of scipy fft?). In any case, one of these should be removed, and the implementation moved directly inside the `Image.shift` method, so that we can concentrate on speeding up one implementation in the future (perhaps by using the `numeric.xp` object).

https://github.com/ComputationalCryoEM/ASPIRE-Python/blob/ddc8a4b1f6af638e9b6660677e3f2ccfd76e61cd/src/aspire/image/__init__.py#L13

**Comment by garrettwrong** [comment]
Noting that the image translation code is moving inside the `Image` class as part of the column to row major conversion (since we're trying to pass the classes around more there, it was a natural thing to do).

**Comment by garrettwrong** [comment]
This reminds me of the recent downsample issues. Triaging to 0.9.1.

**Comment by chris-langfield** [comment]
I'm actually getting that `_im_translate2` is a tad bit slower than `_im_translate`. This is for applying the same shift to a stack of images.

Setup:

```python
vol = Volume(np.load("/Users/langfield/ASPIRE-Python/tests/saved_test_data/clean70SRibosome_vol.npy").astype(np.float32))
n = 1000
L = 65
sim = Simulation(vols=vol, n=n)
display_num = 1000
images = sim.projections[:display_num]
shifts = np.array([100,200])
```

Timing test

im_translate
```
%%timeit -r20
shifted = images.shift(shifts)
>>> 22 ms ± 136 µs per loop (mean ± std. dev. of 20 runs, 10 loops each)
```

im_translate2
```
%%timeit -r20
shifted2 = _im_translate2(images, -shifts)
>>> 24.5 ms ± 82.8 µs per loop (mean ± std. dev. of 20 runs, 10 loops each)
```

These indeed replicate the same result

### `im_translate2` is broken for a stack of shifts

`im_translate2` doesn't work if you give it a stack of shifts, and our tests only cover the case of giving one shift

Setup:
```python
vol = Volume(np.load("/Users/langfield/ASPIRE-Python/tests/saved_test_data/clean70SRibosome_vol.npy").astype(np.float32))
n = 1000
L = 65
sim = Simulation(vols=vol, n=n)
display_num = 10
images = sim.projections[:display_num]
shifts = np.random.rand(display_num,2)*(L//2)
```

```python
images.show()
```
![og](https://user-images.githubusercontent.com/34426450/203601143-d1aa8fc8-cc94-488e-80e0-589c7ef5e6cc.png)



```python
shifted = images.shift(shifts)
shifted.show()
```
![shift1](https://user-images.githubusercontent.com/34426450/203601201-5f293343-ba7e-4e75-ba03-b6050f7e3149.png)



```python
shifted2 = _im_translate2(images, -shifts)
shifted2.show()
```
![shift2](https://user-images.githubusercontent.com/34426450/203601251-9a328cc1-7df7-4d0e-9282-079c91796829.png)

**Comment by chris-langfield** [comment]
Even with the patch in #775 `im_translate2` is slower (this is testing 1000 random shifts)
1000 images, resolution 65
```
%%timeit -r20
shifted = images.shift(shifts)
>>> 96.7 ms ± 700 µs per loop (mean ± std. dev. of 20 runs, 10 loops each)

```

```
%%timeit -r20
shifted2 = _im_translate2(images, -shifts)
>>> 144 ms ± 810 µs per loop (mean ± std. dev. of 20 runs, 10 loops each)

```
