### ISSUE TITLE
Unnecessary method in ImageSource

### ISSUE THREAD

**Issue by vineetbansal** [ComputationalCryoEM/ASPIRE-Python#38]
The `eval_filter_grid` method in the `ImageSource` class is duplicating what a `Filter.evaluate_grid` is doing. The former is likely there as a stepping stone to refactoring, and should be removed.

**Comment by chris-langfield** [comment]
The behavior isn't exactly duplicated, but it does make more sense to make it a module method in `filters`, that takes a source, evaluates the `unique_filters` at `filter_indices`, and returns the filter kernels evaluated on a grid whose dimensions are based on the source. Will be closed by #517
