### ISSUE TITLE
Eliminate console_progressbar dependency

### ISSUE THREAD

**Issue by vineetbansal** [ComputationalCryoEM/ASPIRE-Python#4]
The aspire package came with the `console_progressbar` dependency that had been added to the (joint) `environment.yml`. I suspect `tqdm` (that we have already been using) should suffice for all cases. We need to find cases of `console_progressbar` usage and convert to `tqdm`, and remove this dependency eventually.

**Comment by garrettwrong** [comment]
Closed via #191
