### ISSUE TITLE
ImageSource.whiten return nans

### ISSUE THREAD

**Issue by itaysason** [ComputationalCryoEM/ASPIRE-Python#401]
When running the following script to whiten noise I get an array of nans in `images`:

```
import numpy as np
from src.aspire.image import Image
from src.aspire.noise.noise import AnisotropicNoiseEstimator
from src.aspire.source import ArrayImageSource


stack = np.load(PATH_TO_FILE).T.copy()
image_source = ArrayImageSource(Image(stack))
estimator = AnisotropicNoiseEstimator(image_source, 1, 512)
image_source.whiten(estimator.filter)
images = image_source.images(0, 100).data
```

PATH_TO_FILE is the path for the npy here [stack.zip](https://github.com/ComputationalCryoEM/ASPIRE-Python/files/6117194/stack.zip)

**Comment by garrettwrong** [comment]
Your script seems to have some oddities, but I can quasi confirm.

1) `src` package doesn't correspond to any version of aspire I've used... I assume that is just your folder name? (there are some better ways described in the README if you want..).
2) Your array as written is rejected by current aspire code as having the wrong shape.

Working past those by removing the `src.` and the .T.copy() I can get the nans but it gives a tb with some indication what is happening...

```
2021-03-10 11:16:31,505 INFO   Applying FilterXform (PowerFilter)
/home/garrett/work/Itay/ASPIRE-Python_dev/src/aspire/operators/filters.py:154: RuntimeWarning: divide by zero encountered in power
  return self._filter.evaluate(omega) ** self._power
```

Replacing with `WhiteNoiseEstimator` as a sanity check does not yield nans.  I'll look close into the Aiso estimator.

Just for reference, can you comment on where the source data is from?

Thanks for reporting this.

**Comment by itaysason** [comment]
1. I just use the path to import, just checked and I can drop the src, works with and without it.
2. Sorry, when saving the file I already fixed it, you are right removing the .T works.

The source data is from leia server /scratch/yoelsh/datasets/10028/data/particles/shiny_2sets.star, after I apply my preprocess (phaseflip, downsample, normalize_background). Taking the first 100 images.

**Comment by garrettwrong** [comment]
Interesting, 10028, I think I use that in other examples of this same estimation and whitening method without those preprocessing steps.

**Comment by itaysason** [comment]
Ok, so if I am not doing [normalize_background](https://github.com/itaysason/aspire_refactored/blob/master/aspire/preprocessor/normalize_background.py) the code works
normalize_background simply look at each image edges (outside the circle of some radius) and compute it's mean and std, then normalize the entire image accordingly. 

My guess is that somewhere in the filter computation we compute the mean and std of the edges?

**Comment by itaysason** [comment]
On even sized images the code works, when diving a little deeper into the filter I noticed that there is np.inf in the edge of the filter, so when trying images of size 88x88 it worked as intended.

**Comment by garrettwrong** [comment]
Awesome. I saw your other note re normalizing background, but I don't see it here.  This is encouraging.  

We also talked about some other way to improve robustness with this filter this morning, but for synthetic data.

I'll see if I can reproduce what you described. Thanks!

**Comment by garrettwrong** [comment]
Can confirm if I downsample the provided data to 88 the whitening procedure no longer produces the nans.  Further, some odd downsampled resolutions appear to work with this dataset (eg 77) while many others do not.  The problem remains whether we do a crop or a downsample. The same resolutions work/fail.

I'm downloading emdb10028 particles locally and will try to reproduce this error from raw unprocessed data.

**Comment by garrettwrong** [comment]
I was not able to reproduce this using the first 100 rows or raw 10028 particles from Empiar. I tried running right into the aniso noise estimator and also using a phase_flip->downsample->normalize_background preprocessing pipeline as implemented in ASPIRE-Python.  ~Currently it is running~ It also ran over the entire 10028 particle set.

I still very much want to understand (and fix) whatever is happening here. Just reporting we have somewhat different behavior.

**Comment by garrettwrong** [comment]
@janden Narrowing this down a little... Briefly, I think our (ASPIRE-Python's) interpolater or our usage of it is not correct.

I saved the results of `_input_pts` and `self.xfer_fn_array` from `ArrayFilter._evaluate` as a `.mat`.  From there I can show that the results of our `RegularGridInterpolator` do not match MATLAB's `interpn` which is suggested in the code...  Namely we get many `0` values for this data set in python which we do not get from MATLAB.

Specifically, it appears using our tool is returning a halo (boundary) of zeros.  I confirmed this in the arrays, but you might also pick it out in image of the interpolated results (the black halo).

Matlab:
![MatlabTerps_bug](https://user-images.githubusercontent.com/47759732/112355493-16348d00-8ca4-11eb-8a4d-e17e9f7ed85a.png)

Python:
![PythonTerps_bug](https://user-images.githubusercontent.com/47759732/112355514-1e8cc800-8ca4-11eb-92dd-1a266e25c6d1.png)

From this point, these zero values are then casually passed through to application of `PowerFilter`.  At this point we setup a `np.power` call with zero base and negative exponent (the logged warning), and finally yield the non finite values Itay reported.

_If I replace interpolation results in python with those from `interpn` we seem to get a reasonable result._

I will continue looking at the interpolation, but wanted to note the progress.

**Comment by garrettwrong** [comment]
After the filter grid patch was merged into develop Itay was able to check that the results from whitening are now close (between ASPIRE-Python and his preprocessing stack).  He is going to let us know if he finds anymore discrepancies that require investigating.  Closing issue following #409 .
