### ISSUE TITLE
ArrayImageSource should admit Arrays

### ISSUE THREAD

**Issue by garrettwrong** [ComputationalCryoEM/ASPIRE-Python#403]
I think this was oversight (probably my bad) to require `ArrayImageSource` to be initialized from `Image`.

We can attempt to do this for the user (checking for sanity). It should only require a few lines of code, basic unit test, and updating our example notebooks/tutorials/docs.

Result should make our examples less terse, and a more sensible api for users.

**Comment by janden** [comment]
Sounds good.

**Comment by garrettwrong** [comment]
Closed by #449
