### ISSUE TITLE
weights (het3d wts)

### ISSUE THREAD

**Issue by garrettwrong** [ComputationalCryoEM/ASPIRE-Python#405]
Port scripts for feature developed by Amit H/M to ASPIRE-Python.

Currently Amit H is working on building some utility functions to write out MATLAB data which can then be read in ASPIRE-Python for use validating MATLAB and Python versions.

I began mapping between the renamed/edited scripts and what I believe to be the original MATLAB sources (or close enough). Referring to the changes I am implementing `WeightedCovarianceEstimator` `WeightedMeanEstimator` and related conj grad.  Based on a prior discussion the plan is to first get the computations using weights implemented, then follow with weight generation.  I'm not attached to the names, just trying to stub some code in and see what shakes out.

Using subclasses seems to be keeping this change light so far, with `WeightedMeanEstimator.compute_kernel` being the first non trivial method. (I think I see pretty direct way to refactor this to also be simpler later if we want).

We can use this issue to discuss or add notes from our meetings.

**Comment by janden** [comment]
Cool. As far as I know, there should be no need for a `WeightedCovarianceEstimator`, all of the generalization happens for the mean estimation code. As far as name suggestions, maybe `WeightedMeanEstimator` should be `GeneralizedMeanEstimator` or `WeightedVolumesEstimator`.

**Comment by garrettwrong** [comment]
Yes, you are right. The other subclass I was working on was `FourierKernelMat` (the rxr collection kernel matrices), not covariance.  I was trying to write this down from my memory which can't be trusted. I'll try to be more careful.

**Comment by garrettwrong** [comment]
Moving to v0.11.1.  Should be a good time to work through this review since I will be stuck on basis/cov dev for a while.
