### ISSUE TITLE
Log length of (Relion)Source

### ISSUE THREAD

**Issue by garrettwrong** [ComputationalCryoEM/ASPIRE-Python#407]
It would be useful to log the total expected length of a source as a diagnostic when working with large (particularly experimental) data sets.  Right now we just log we are processing a block with a blocksize, but a user might appreciate a sense of how many blocks etc.

**Comment by chris-langfield** [comment]
`RelionSource` is indeed a wrapper for a STAR file. The broad plan here will be:

Implement a new StarFile object and overload `__len__` to give the number of blocks. With each block represented as a dataframe, the length of a block with a list of MRC files would also be easily read and displayed.

**Comment by garrettwrong** [comment]
Rebalancing this to Josh.  

I think we can keep it simple and just add `__len__` to image source that returns `self.n`.  Then we can log _once_ how many images are in the source... say during instantiation.  That would be adequate to give the feedback for _all_ sources without getting in the weeds of different sources or block sizes etc.
