### ISSUE TITLE
Starfile IO

### ISSUE THREAD

**Issue by garrettwrong** [ComputationalCryoEM/ASPIRE-Python#412]
It's not clear how to simply use our starfile IO utils to write some data. It does have some tests but they are more reader focused, and test tautology of reading then writing back the same structure.  Its not really clear if I have some data in python how to structure/write it with ASPIRE's tool.

If we are going to have this feature, we need to document it better, both in documentation and in some code.

We may just be able to use a package like https://github.com/alisterburt/starfile etc if that is easier. They seem to have a similar idea.

Starfile IO should be incorporated into CTF estimation utilities from #380

**Comment by janden** [comment]
> We may just be able to use a package like https://github.com/alisterburt/starfile etc if that is easier. They seem to have a similar idea.

That would be great. I think the only reason that this functionality was even included in ASPIRE was due to the lack of existing libraries. If they exist and work well, I don't see why we shouldn't use them.

**Comment by garrettwrong** [comment]
Discussed with Chris today.  He discovered one difference between the third party library and ours is the ability to have two loops in our implementation.  So the plan is to:

- [x] Check if that double loop is conformant to the spec (start with paper I guess)
- [x] Check if that double loop is something we need
- [x] Survey the level of effort to replace wholesale vs keeping our existing Starfile class as a shim.

Then we can move forward one way or another.

**Comment by chris-langfield** [comment]
Multiple loops in a data block are in example in original STAR paper: https://pubs.acs.org/doi/pdf/10.1021/ci00002a020

Also, tests/saved_test_data/sample.star contains two loops in a data block

double checking now to make sure I can't get the external library to work with multiple loops

**Comment by janden** [comment]
Problem with that `sample.star` file is that it's not something representative of files we expect to see. I think we usually only have one loop in a data block. Attaching some sample files that we should be able to read.

[run_001_it025.zip](https://github.com/ComputationalCryoEM/ASPIRE-Python/files/7077500/run_001_it025.zip)

If it's still an issue, we can either try to fork that library or use GEMMI as they suggest. In this case, I think GEMMI is the easiest, but it depends on well that library is maintained.

**Comment by janden** [comment]
I should add that since that `sample.star` is not representative, it should probably be replaced with one of the STAR files I attached above (probably the `_model.star` file).

**Comment by chris-langfield** [comment]
the starfile external packages reads all four of those nicely. however I tested it again against some starfiles with multiple loops and it definitely can't handle it.

as far as the time needed to refactor:

the ASPIRE StarFile class is used:

- In the constructor of the `RelionSource` class. In particular, the `__class__.starfile2df` image loads the star file as a pandas dataframe (much in the same way as the external package). this dataframe is saved as `metadata` and used throughout the rest of the constructor.

- in the `save_metadata()` method of the `ImageSource` class, where it writes out the properties of the image class to a new star file. in particular, it creates a STAR file with only one loop structure. The external library also writes directly from DF to a new starfile.

For both of these it seems like it would be mostly a matter of making sure the datanames are being written correctly. For instance the current code has underscores hardcoded in, which are then written to the star file, whereas the external package automatically appends an underscore when converting to STAR, assuming that the DF has names without the underscore. 

Also:

- the `write_star()` method of the `CtfEstimator` class. This method actually writes to a ".log" file and doesn't use the current StarFile class.

**Comment by chris-langfield** [comment]
and of course the starfile tests would have to be redone!

**Comment by garrettwrong** [comment]
Okay so, it seems like this is worth doing.  I agree about changing the unit test to be representative.  We can look at the `CtfEstimator` change afterwards, once the implementation is changed.  I would hope it would be easier then... at least, that will be a practical test if it was an improvement... :)

**Comment by janden** [comment]
Sounds good.

**Comment by chris-langfield** [comment]
Issues identfied with starfile.py package as they relate to tests

- Type conversion IS performed in this package (our old tests have comments saying "note that type conversion IS NOT performed). "1" in the old dataframe corresponds to (int) 1 in the new dataframe
- blank entries in STAR file are not converted to '' (empty str) values, rather they cause the read() method to fail
- Order of blocks in the OrderedDict returned by read() is not guaranteed. This means the blocks cannot be reliably indexed by number after being saved and then read back. So you need to know the name of the data block you are trying to access. e.g. after 
`starfile.write(star1, fp)`
`star2 = starfile.read(star2)`
`list(star1.items())[i][1] == list(star2.items())[i][1]` is not guaranteed for any `i`

**Comment by janden** [comment]
Regarding type conversion, that shouldn't be a big problem.

I'm not sure about the blank entries. Does that happen in our sample data? If so, is there a way to maybe submit a bugfix to the upstream package (the read function failing seems to be unwanted behavior just because a field is missing).

Regarding order of blocks, we should probably be indexing by name anyhow.

**Comment by chris-langfield** [comment]
In case this package doesn't work out, GEMMI has python bindings to read and write CIF files. The only thing is it has many other programs attached to it that I'm not sure if we need. Could be a good thing or a bad thing, for instance it has some code for PDB files #430 

From their docs:

> STAR is a human-readable data serialization format (think XML or JSON) that happens to be known and used only in molecular-structure sciences. CIF (Crystallographic Information File) – a file format used in crystallography – is a restricted derivative of STAR. It is restricted in features (to make implementation easier), but also imposes arbitrary limits – for example on the line length.

We would potentially have to make sure the STARs we use are CIF compliant

**Comment by chris-langfield** [comment]
As far as addressing the behavior with blank entries in the upstream package, I think I want to make sure I can resolve the read/write problem we discussed first.

**Comment by chris-langfield** [comment]
#### DRAFT bug report: Unexpected behavior with single-row blocks following other blocks in a STAR file

Hi `starfile` authors, we are planning to use your library in our package. When building some tests, we encountered the following issue. We're wondering whether this is a bug or whether we are possibly using the library wrong. Thanks!

#### Description

When reading in STAR files, blocks which are

- comprised of a single row of data (whether stored as a loop_ or not)
- not the *first* block of the file

exhibit unexpected behavior when read from a file, written back, and then read back again.

It seems that some data from the preceding block is copied in. For example with the following STAR file:


```
data_block_0

loop_
_val1
_val2
_val3
1.0     2.0     3.0


data_block_1

loop_
_col1
_col2
_col3
A       B       C
```
When then file is read, written, and then read back, we get the following dataframes:

```
block_0
ORIGINAL
   val1  val2  val3
0   1.0   2.0   3.0
NEW
   val1  val2  val3
0   1.0   2.0   3.0

block_1
ORIGINAL
  col1 col2 col3
0    A    B    C
NEW
   val1  val2  val3 col1 col2 col3
0   1.0   2.0   3.0    A    B    C
```

As can be seen above, some data from `block_0` is incorporated into `block_1`

#### Comparison with GEMMI - sanity check

To ensure we weren't using pathological STAR files, we attempted the same process using `starfile` and `gemmi.cif`. We used several simple example STAR files, including some from the `tests/data` path in the `starfile` directory. 

The following python script tests a few cases:

```python
import starfile
import pandas as pd
import os
from gemmi import cif

files = ['example_with_loops.star', 'example_no_loops.star', 'example_mixed_1.star', 'example_mixed_2.star', 'example_nonconsecutive.star', 'example_nonconsecutive_2.star', 'single_line_end_of_multiblock.star', 'single_line_middle_of_multiblock.star']

print('starfile package tests')
print('----------------------')
for f in files:
    orig = starfile.read(f, always_dict=True)

    starfile.write(orig, f"saved_{f.replace('.star','')}.star", overwrite=True)

    compare = starfile.read(f"saved_{f.replace('.star','')}.star", always_dict=True)

    print(f)
    good = True
    for key, df in orig.items():
        print(key)
        print('ORIGINAL')
        print(df)
        print('NEW')
        print(compare[key])
        print()
        if not compare[key].equals(orig[key]):
            good = False
            break
    if good:
        print('success!')
    else:
        print('comparison failed')
    print()

print()

print('GEMMI comparison w/ same files')
print('---------------------------')
for f in files:
    print(f)

    # read file, write out same object, and read it back
    orig = cif.read_file('gemmi/' + f)
    orig.write_file('gemmi/saved_' + f)
    compare = cif.read_file('gemmi/saved_' + f)

    # make sure they have the same number of blocks
    assert(len(orig) == len(compare))
    for block in orig:

        # get block name and find corresponding block in compare
        orig_block = block
        compare_block = compare[block.name]

        # iterate over items in block. these can be a pair or a loop
        for item in orig_block:
            if item.pair is not None:
                orig_pair = item.pair
                # find the corresponding pair in the compare block
                compare_pair = compare_block.find_pair(item.pair[0])
                # compare each pair and make sure they are equal
                assert(orig_pair == compare_pair)
                # make sure that if this block has pairs, it doesn't also
                # have a loop
                assert(item.loop is None)
            if item.loop is not None:
                orig_loop = item.loop
                # find the coresponding loop in the compare block
                compare_loop = compare_block.find_loop_item(orig_loop.tags[0]).loop

                # make sure the loops have the same tags
                assert(orig_loop.tags == compare_loop.tags)

                for tag in orig_loop.tags:
                    orig_col = orig_block.find_values(tag)
                    compare_col = compare_block.find_values(tag)
                    # make sure columns have same lengths
                    assert(len(orig_col) == len(compare_col))
                    # make sure columns are equal by index
                    for i in range(len(orig_col)):
                        assert(orig_col[i] == compare_col[i])

                # make sure that if this block has a loop, it doesn't also
                # have pairs
                assert(item.pair is None)
    print('success!')
    print()

```
We get the following output:

```

starfile package tests
----------------------
example_with_loops.star
block_0
ORIGINAL
   val1  val2  val3
0   1.0   2.0   3.0
NEW
   val1  val2  val3
0   1.0   2.0   3.0

block_1
ORIGINAL
  col1 col2 col3
0    A    B    C
NEW
   val1  val2  val3 col1 col2 col3
0   1.0   2.0   3.0    A    B    C

comparison failed

example_no_loops.star
block_0
ORIGINAL
   val1  val2  val3
0   1.0   2.0   3.0
NEW
   val1  val2  val3
0   1.0   2.0   3.0

block_1
ORIGINAL
   val1  val2  val3 col1 col2
0   1.0   2.0   3.0    A    B
NEW
   val1  val2  val3 col1 col2
0   1.0   2.0   3.0    A    B

success!

example_mixed_1.star
block_0
ORIGINAL
   val1  val2  val3
0   1.0   2.0   3.0
NEW
   val1  val2  val3
0   1.0   2.0   3.0

block_1
ORIGINAL
    .0 col1 col2
0  2.0    A    B
NEW
   val1  val2  val3   .0 col1 col2
0   1.0   2.0   3.0  2.0    A    B

comparison failed

example_mixed_2.star
block_0
ORIGINAL
   val1  val2  val3
0   1.0   2.0   3.0
NEW
   val1  val2  val3
0   1.0   2.0   3.0

block_1
ORIGINAL
  col1 col2 col3
0    A    B    C
NEW
   val1  val2  val3 col1 col2 col3
0   1.0   2.0   3.0    A    B    C

comparison failed

example_nonconsecutive.star
block_0
ORIGINAL
   val1  val2  val3
0   1.0   2.0   3.0
NEW
   val1  val2  val3
0   1.0   2.0   3.0

block_inbetween
ORIGINAL
  d1 d2 d3
0  a  b  c
1  d  e  f
2  g  h  i
NEW
  d1 d2 d3
0  a  b  c
1  d  e  f
2  g  h  i

block_1
ORIGINAL
  col1 col2 col3
0    A    B    C
NEW
     col1 col2 col3
0  h    A    B    C

comparison failed

example_nonconsecutive_2.star
block_inbetween
ORIGINAL
  d1 d2 d3
0  a  b  c
1  d  e  f
2  g  h  i
NEW
  d1 d2 d3
0  a  b  c
1  d  e  f
2  g  h  i

block_1
ORIGINAL
  col1 col2 col3
0    A    B    C
NEW
     col1 col2 col3
0  h    A    B    C

comparison failed

single_line_end_of_multiblock.star
block_1
ORIGINAL
                     rlnImageName  ... rlnCoordinateZ
0  000001@0001_sum_particles.mrcs  ...       -51.5227
1  000001@0001_sum_particles.mrcs  ...       -51.5227

[2 rows x 5 columns]
NEW
                     rlnImageName  ... rlnCoordinateZ
0  000001@0001_sum_particles.mrcs  ...       -51.5227
1  000001@0001_sum_particles.mrcs  ...       -51.5227

[2 rows x 5 columns]

block_3
ORIGINAL
                     rlnImageName  ... rlnCoordinateZ
0  000001@0001_sum_particles.mrcs  ...       -51.5227

[1 rows x 5 columns]
NEW
  00001@0001_sum_particles.mrcs  ... rlnCoordinateZ
0                  0002_sum.mrc  ...       -51.5227

[1 rows x 6 columns]

comparison failed

single_line_middle_of_multiblock.star
block_1
ORIGINAL
                     rlnImageName  ... rlnCoordinateZ
0  000001@0001_sum_particles.mrcs  ...       -51.5227

[1 rows x 5 columns]
NEW
                     rlnImageName  ... rlnCoordinateZ
0  000001@0001_sum_particles.mrcs  ...       -51.5227

[1 rows x 5 columns]

block_3
ORIGINAL
                    rlnImageName0  ... rlnCoordinateZ0
0  000001@0001_sum_particles.mrcs  ...        -51.5227

[1 rows x 5 columns]
NEW
                     rlnImageName  ... rlnCoordinateZ0
0  000001@0001_sum_particles.mrcs  ...        -51.5227

[1 rows x 10 columns]

comparison failed


GEMMI comparison w/ same files
---------------------------
example_with_loops.star
success!

example_no_loops.star
success!

example_mixed_1.star
success!

example_mixed_2.star
success!

example_nonconsecutive.star
success!

example_nonconsecutive_2.star
success!

single_line_end_of_multiblock.star
success!

single_line_middle_of_multiblock.star
success!


```

**Comment by garrettwrong** [comment]
That is a very detailed bug report. Thank you.  We'll talk in a few minutes.  I think you should be able to pass that to them.  Really curious how you feel about the two different APIs (`starfile` vs `GEMMI`) now that you've used them both.

**Comment by chris-langfield** [comment]
Issue has been submitted to the `starfile` authors. We'll see what they say and discuss next week whether it could be better to use `gemmi` because of the pdb support. The `gemmi` framework for reading starfiles is much more complicated, though, and could be overkill.

**Comment by chris-langfield** [comment]
The bug in `starfile` has been fixed. However, the package now requires python >= 3.7. I force installed it and tried it out but the package now uses `annotations` from `futures`, which is only available in python >= 3.7. Our conda env is frozen at 3.6

**Comment by garrettwrong** [comment]
Another challenge. We (as developers) can use different python versions, conda or otherwise, but deprecating 3.6 is a larger question. It has other moving parts (3.9 for example). We should talk about it during our dev meeting.

I think you can still try this out locally in an empty python 3.7 conda env, followed by the developer pip install line.

**Comment by janden** [comment]
> whether it could be better to use `gemmi` because of the pdb support. 

I agree this might be a good feature. I don't know what other options are available for pdbs. I tried `prody`, but it also includes a lot of stuff that we may not need.

> The `gemmi` framework for reading starfiles is much more complicated, though, and could be overkill.

We should discuss this. It might be good to have a backend library that offers more flexibility down the road.

> Another challenge. We (as developers) can use different python versions, conda or otherwise, but deprecating 3.6 is a larger question. It has other moving parts (3.9 for example). We should talk about it during our dev meeting.

Yes this is another problem. What are the version requirements for gemmi?

**Comment by chris-langfield** [comment]
I am currently working on implementing a GEMMI backend. However, here's something we could keep in mind:

https://github.com/alisterburt/starfile/issues/17#issuecomment-919039508

**Comment by garrettwrong** [comment]
Very good. Thank you Chris!

**Comment by garrettwrong** [comment]
I think we covered this issue, thanks!  Closing
