### ISSUE TITLE
Add Wavelet Based Earth Mover Distance

### ISSUE THREAD

**Issue by garrettwrong** [ComputationalCryoEM/ASPIRE-Python#418]
Amit M has provided some code used by the ASPIRE group relating to this paper:

https://home.ttic.edu/~ssameer/Research/Papers/WEMD_CVPR08.pdf

```
Basically, it performs a wavelet transform of a signal (image, volume, etc.) and weights the coefficients according to a formula. Then one can use L1 distances between the weighted coefficients to approximate an Earthmover's distance.
```

I will submit a draft PR with a stub test file after meetings this morning. When the tests are added we can undraft for review.

**Comment by janden** [comment]
Solved?

**Comment by garrettwrong** [comment]
I think so, forgot to close. (For some reason the automation doesn't alwasy work well on GH, haven't had time to figure out why). Thanks.
