### ISSUE TITLE
Add Adaptive Support method

### ISSUE THREAD

**Issue by garrettwrong** [ComputationalCryoEM/ASPIRE-Python#431]
Integrate adaptive support function for image stacks. This came up in some discussions with Amit and Yunpeng (also in the class averaging code). In the legacy code this was theoretically available in `choose_support_v6.m`.  

Some notes. In practice the MATLAB script was not working.  It crashes for even resolutions and doesn't always return both the values it was intending to compute when it does run. FWIW.

This is being broken out of the larger Class Averaging PR into something small since it is a relatively standalone feature.  
I was able to clean it up a little so that it no longer crashes for even resolutions and appears to reproduce the MATLAB results for an odd image stack quite well.  I also made some minor changes:

1. Name, calling it `adaptive_support` instead of `choose_support`
2. Input, admits `Image` instance instead of array of centered Fourier transform of image stack.
3. Scale, I no longer scale the Fourier limit because the only use of the code immediately re-normalized it to [0,0.5]. I think this Nyquist view is more consistent with most of ASPIRE-Python.

**Comment by janden** [comment]
I remember `choose_support_v6` being broken. Not crashing, but just giving wrong results for the support. It would be good to take a closer look at this to see if there are some deeper algorithmic issues. I remember Jane was supposed to look at this, but I don't know if anything came of it.

**Comment by garrettwrong** [comment]
I know in some cases it was not returning one of the two values because of an array indexing error.  In that case things could have gone wrong many ways...  (this was happening to me during validation and driving me nuts, can tell you more later).  I believe I fixed that issue in this code.

The cumulative energies looked sane (I plotted them during validation). 

I'd be happy to dig a little deeper into this if it wasn't validated even for the cases it originally ran on. I feel less bad about calling out this code now 👼 .

**Comment by janden** [comment]
IIRC it was an issue of giving wildly inaccurate support values in certain circumstances, but I don't remember the details. It's a component that should be validated, for sure.

**Comment by garrettwrong** [comment]
This came up again today.

1) Amit mentioned I can find the topic in one of the steerable pca papers. I'll look again and try to add reference.
2) Yunpeng's recent experiments seem to indicate we get worse performance with non default support, so there is no rush to link this up with FFB quite yet.

**Comment by garrettwrong** [comment]
Closed by #432
