### ISSUE TITLE
Block Tridiagonal Matrix

### ISSUE THREAD

**Issue by garrettwrong** [ComputationalCryoEM/ASPIRE-Python#436]
During a research group meeting, a user requested Block Tridiagonal Matrix implementation (analogous to our `BlkDiagMatrix`) to support their research.

Ostensibly this doesn't seem too difficult but there are a couple design concerns/decisions that need to be considered.

1)  Are all the blocks the same size?  Generally when people refer to Block Diagonal and Block Tridiagonal it is implicit that the blocks are square and identically sized.  Our block diagonal is already somewhat different in that we admit arbitrary square block sizes.  This gets somewhat more complex for block tridiagonal.  Hand wavy arguments can be made that the matrix action is the same as for scalars (and id blocks), but the implementation and interface for this is just a little more tricky...
2) Non square blocks?  In the past it has come up that we may want to support non square blocks for `BlkDiagMatrix`.  This is somewhat involved.  For example multiplying two identical non square blocked matrix will yield a new matrix of a different layout.
3) What operations does it need to support?  Does it require specialized implementations for performance, or is this more for memory constraints?
4) What matrices does it need to interact with? (BlkDiag?, dense numpy?, other block tridiag with different layouts?)

If we can nail down the above I think we can implement this.  It might be more efficient to wait until we revisit BlkDiagMatrix, but I'm not sure what the timeline/research need really is for this ask relative to our other work.

**Comment by garrettwrong** [comment]
Adding some notes.

I mentioned block tridiagonal matrices are not closed under multiplication during the most recent ASPIRE lunch meeting, and I think that sort of damped the interest in this as a software feature.  Further, it turns out the matrices in question are probably manageably small anyway.  I'll leave this issue open until we have chance to discuss it a little.

**Comment by janden** [comment]
> During a research group meeting, a user requested Block Tridiagonal Matrix implementation (analogous to our `BlkDiagMatrix`) to support their research.

I guess the first question here is why? I suspect it has to do with improving performance of some computation, but as we start adding complexity, we may have a hard time reaching the desired performance improvement over dense. It really has to be tested to see if an important speedup is achievable here.

> Further, it turns out the matrices in question are probably manageably small anyway.

Ok then it's likely hard to get the desired improvement. If the interested party wants to put together a prototype (based on `BlkDiagMatrix`) to investigate, we can see whether it's worth bringing in.

**Comment by garrettwrong** [comment]
I think the original inquisitor has reached similar conclusion.  Probably safe to close this, just wanted to keep you in the loop.
