### ISSUE TITLE
Lazy evaluation of transformation functions on ImageSource

### ISSUE THREAD

**Issue by vineetbansal** [ComputationalCryoEM/ASPIRE-Python#44]
Among other motivations, the following is one:

```
        logger.debug("Applying whitening filter to all images and caching")
        whitened_images = Image(images[:, :, :]).filter(whiten_filter)
        self.cache(whitened_images)
```

This is very expensive. We're calculating *all* the images, filtering them, and storing them in the `ImageSource` object. If the entire dataset is a couple hundred gigabytes, we're in trouble.

_Originally posted by @janden in https://github.com/_render_node/MDE3OlB1bGxSZXF1ZXN0UmV2aWV3Mjg0NjA5ODgz/pull_request_reviews/more_threads_

**Comment by garrettwrong** [comment]
The application of whitening no longer requires maintaining the entire image set.  It is implemented as a pipelined application of a filter. This issue was from before that time.

Closing.
