### ISSUE TITLE
Compressed Eigen Vector Matrix (BlockDiagMatrix)

### ISSUE THREAD

**Issue by garrettwrong** [ComputationalCryoEM/ASPIRE-Python#442]
In #411 one of the main pieces of data is a block diagonal matrix of eigenvectors.

When we sort by eigenvalue and truncate to some number of top components I believe this matrix loses its structure.

Because it was only one matrix I cheated and got around this by expanding it to a dense representation.  This works but is somewhat unsatisfying.

One way to manage this might be to use masks and index translation, but that should be wrapped up in a class.  Essentially population selection would not really change the underlying matrix, rather defining the mask/swapping.

I believe this area of the legacy MATLAB code was somewhat bespoke, while we are trying to maintain some more uniformity in ASPIRE-Python.  I am open to other ways of managing this...

**Comment by janden** [comment]
One way to do this is to separately sort and truncate each block. There's really no need for a global sort (other than to determine the cutoff value, which can be applied block-by-block).

**Comment by garrettwrong** [comment]
By structure, I meant square block diagonal; it does lose its structure... If we truncate blocks, it is now not a square block diagonal...

The blocks are sorted by eigval, no problem there. In the current code we get the eigvals block by block so we won't know the global truncation value until the end, fwiw.

If you mean to create a new block diagonal with zero/mask vectors when the eigval is less than the global kth component's value...  this reduces the rank only on paper, but doesn't actually helps us multiply the matrices directly... or truncate the resulting estimation matrix (the main point right)...  not without incorporating masks etc.

So I guess I can offer at least two options here:

1)  "The Masked Approach".  We use the existing block diagonal in conjunction with a mask of the column space (based on eigval cutoff).  We then use the existing block diagonal matrix multiply with each block applying it's slice of mask to reduce rank.  This would require extending block diagonal's multiplication to admit a mask.

2)  "The irregular Block Diagonal Approach" We construct a non square block diagonal extension and use that.  Lot of bookkeeping if you want to offer same level of methods (mainly for @) , but doable.

I guess one question would be how often this will come up again later, which I don't have any insight into.

**Comment by janden** [comment]
I was thinking of option two, but was perhaps ignoring implementation complexities here. Other than checking for compatible sizes, what would be involved?

**Comment by garrettwrong** [comment]
I think 2 is straightforward if we ignore matmul.  Matmul is tricky because the combination of sizes and class types. It would potentially need to handle BlockDiagonal, IrregularBlockDiagonal, and Numpy.

I will take a crack at it, maybe it won't be so bad.

**Comment by janden** [comment]
My thinking was just to extend `BlockDiagonal` to handle rectangular blocks. Would that be too messy?

**Comment by garrettwrong** [comment]
No, I agree.  When I listed `BlockDiagonal, IrregularBlockDiagonal, and Numpy` was more conceptual cases. I don't think we'll need an entirely new class at this time.

**Comment by garrettwrong** [comment]
FWIW, this ended up being pretty easy.  I'll have to thank the guy that wrote it for making extensible code, hahaha.

Once that PR is in it should be straightforward to use in the class averaging code.  I'll need to add a loop after we have the global eigvals to create a new reduced block diagonal.  At that point should be able to use `apply`/matmuls and remove some of the (dense) branching. Can be a seperate small PR for that.

**Comment by garrettwrong** [comment]
Supporting changes merged, closing.
