### ISSUE TITLE
Improve Indices Computation/Accessor structure consistency in Basis classes

### ISSUE THREAD

**Issue by garrettwrong** [ComputationalCryoEM/ASPIRE-Python#446]
The computation and storage of indices in the Basis classes (FB2D, FFB2D, FB3D, FFB3D, etc) is only marginally consistent and has a lot of matlab-esque flavor that makes less sense in Python.

For example, classes are using and returning a dictionary instead of class attributes.  This is because the code was ported from something that returned a cell structure etc in MATLAB.  There is also some redundancy in methods/attributes (`indices()`, `_indices`, `*compute*`, `*build*`.

I think we might be able to define, document, and implement this stuff a little better. This will require surveying the involved basis classes and trying to architect something that is generalized.

**Comment by janden** [comment]
Agreed. This is probably a good time to consider migrating these into the `SteerableBasis` class to ensure consistency. Not sure if we want to make it part of the same PR or do these things separately. One option would be to move these index functions into `SteeerableBasis`, then refactor them there.

**Comment by garrettwrong** [comment]
Common indices maps have been moved to `SteerableBasis` as part of #1015 and prior work.

What remains is to remove redundant implementations in the specific 2D classes so that only the common map variables are used.  This can come as cleanup after the interoperable milestones are in `develop`.
