### ISSUE TITLE
Migrate Tutorial Scripts to Jupyter Notebooks

### ISSUE THREAD

**Issue by garrettwrong** [ComputationalCryoEM/ASPIRE-Python#447]
We have a small collection of tutorial scripts in `tutorials/examples`. These largely come in two flavors, those that are small simulated data sets and under testing, and corresponding large examples targeting experimental datasets.

I'd like to move the examples from a script to nicely formatted (documented) Jupyter Notebooks.  These tutorials need to remain under testing.

This requires a few tasks:

- [x] Initial migration to notebooks (copy)
- [x] Reformatting
- [x] Improving documentation (requires digging into code a little)
- [x] Use/extend the existing testing infrastructure to automatically convert notebooks into run-able scripts (`nbconvert` or similar)

For a first pass I think that will get us down the road.  Long term we need to continue some discussions:

1. Whether to break of the notebooks/examples into a separate repo.
2. Whether we want the notebooks to be complete or cleared.
3. Whether to adopt more sophisticated inline documentation/examples (sphinx).
4. Relationship to `tutorials/notebooks`...
5. Optionally, we might consider using `Binder` once we have some more user buy in (or before another class etc).

**Comment by janden** [comment]
Just recapitulating the discussions @garrettwrong and I have had previously. I think the cleanest approach here is to use something like sphinx-gallery. It will require some more up-front costs, but we have the advantage that the code can get tested a part of the regular testing suite, that notebooks are regenerated after any change, and that the commit history won't get polluted by these notebook updates. The history issue can be solved using a separate repo, but this makes it harder to maintain consistency (although I imagine this can be integrated as part of CI). Another option is to leave the notebooks cleared, but that decreases the value to end users.

**Comment by garrettwrong** [comment]
This issue was solved by implementing sphinx-gallery in  #453.
