### ISSUE TITLE
Add ability to specify filters/filter indices when constructing a Simulation.

### ISSUE THREAD

**Issue by vineetbansal** [ComputationalCryoEM/ASPIRE-Python#45]
How would a user specify the filters *and* the filter indices in advance? Currently, it would always resample them.

_Originally posted by @janden in https://github.com/ComputationalCryoEM/ASPIRE-Python/pull/35_

**Comment by junchaoxia** [comment]
This is a new issue #207 for the similar problem. Closing now.

**Comment by janden** [comment]
The two issues are different. This one concerns arguments to the constructor, #207 concerns the internal storage of the filters.

**Comment by junchaoxia** [comment]
The filter indices can be constructed outside the simulation class and are able to be passed into the object in PR #295. Closing now.
