### ISSUE TITLE
Issues with downsampling

### ISSUE THREAD

**Issue by vineetbansal** [ComputationalCryoEM/ASPIRE-Python#46]
A couple of closely related issues

1. Confusing naming of `L` and `_L` attributes in `ImageSource`
 https://github.com/_render_node/MDE3OlB1bGxSZXF1ZXN0UmV2aWV3Mjg0NjA5ODgz/pull_request_reviews/more_threads_

2. Downsampling should happen in the super `images` method. Subclasses should provide whatever native resolution images they're dealing with, in their respective `_images` methods.

3. Downsampling is broken for `Simulation` objects, because the `_L` attribute doesn't exist.

**Comment by junchaoxia** [comment]
This issue has been fixed in PR #273. Closing now.
