### ISSUE TITLE
Apple Picker - create separate methods to return centers and image of picked particles

### ISSUE THREAD

**Issue by j-c-c** [ComputationalCryoEM/ASPIRE-Python#472]
Currently the `process_micrograph` method can only return either the centers or an image of picked particles.

https://github.com/ComputationalCryoEM/ASPIRE-Python/blob/4fdf77dc35fc14adc582e1750dea4f1f84d0fda7/src/aspire/apple/apple.py#L116-L127

If you want the `centers` and the `image` as in the apple_picker example gallery you have to run apple picker twice, as mentioned [here](https://github.com/ComputationalCryoEM/ASPIRE-Python/pull/453#discussion_r722415822).

**Comment by garrettwrong** [comment]
Might as well do this too while I'm patching that code up.

**Comment by garrettwrong** [comment]
Closed by 513
