### ISSUE TITLE
EMPIAR-10073

### ISSUE THREAD

**Issue by chris-langfield** [ComputationalCryoEM/ASPIRE-Python#475]
This dataset fails to load properly when initialized as a `RelionSource`.

Sample script to reproduce:

```python
DATA_FOLDER = '/tigress/cl5072/datasets/10073/data'
STARFILE_IN = '/tigress/cl5072/datasets/10073/data/Particles/shiny_correctpaths_cleanedcorruptstacks.star'
PIXEL_SIZE = 1.43

source = RelionSource(STARFILE_IN, DATA_FOLDER, pixel_size=PIXEL_SIZE, n_workers=1)

imgs = source.images(0, source.n)
```
The failure is on the last line, calling `images()`. 

```
imgs_og = source.images(0, source.n) <-----------------
  File "/home/cl5072/.conda/envs/aspire_dev/lib/python3.6/site-packages/aspire/source/image.py", line 396, in images
    im = self._images(indices=indices, *args, **kwargs)
  File "/home/cl5072/.conda/envs/aspire_dev/lib/python3.6/site-packages/aspire/source/relion.py", line 186, in _images
    data_indices, data = future.result()
  File "/home/cl5072/.conda/envs/aspire_dev/lib/python3.6/concurrent/futures/_base.py", line 425, in result
    return self.__get_result()
  File "/home/cl5072/.conda/envs/aspire_dev/lib/python3.6/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "/home/cl5072/.conda/envs/aspire_dev/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/cl5072/.conda/envs/aspire_dev/lib/python3.6/site-packages/aspire/source/relion.py", line 161, in load_single_mrcs
    data = arr[df["__mrc_index"] - 1, :, :]
IndexError: too many indices for array
```

The context of this line is `relion.load_single_mrcs(filepath, df):

```python
def load_single_mrcs(filepath, df):
            arr = mrcfile.open(filepath).data
            data = arr[df["__mrc_index"] - 1, :, :] <------------
            return df.index, data
```
Which is executed in the following parallelized code

```python
for filepath, _df in groups:
                future = executor.submit(load_single_mrcs, filepath, _df)
                to_do.append(future)
```

**Comment by chris-langfield** [comment]
- When executed with multiple cores, the filepath on which this error occurs is variable
- When executed on a single core, the last filepath printed out is `/tigress/cl5072/datasets/10073/data/Particles/img3_7836_cor_bin2_extractedparticles_22Aug15checkedautopick.mrcs`
- The file prior to this is `7835` and the file following it in the STAR file is `11Jul15_6122_cor_bin2_extractedparticles_11Jul15unchecked_shiny200-22Jun11Jul-7frames.mrcs`
- These files are loaded as normal when the code above is run if a new STAR file is created containing just the files in question. (For example, they load individually, as well as when in a STAR file containing those 3).

**Comment by garrettwrong** [comment]
First thing first, simplify... remove the threading entirely and repeat. That is, no `futures.ThreadPoolExecutor` etc.  Gut it. That whole area of code should reduce to a loop over files stuffing into an array (two lines?).  Then we can think on what that experiment tells us.

**Comment by chris-langfield** [comment]
This was being caused by one of the `.mrcs` images in the dataset. Specifically, `11Jul15_6272_cor_bin2_extractedparticles_11Jul15unchecked_shiny200-22Jun11Jul-7frames.mrcs` only contained 1 particle. Therefore, it's `arr` numpy array had shape `(380, 380)` where our code expects `(1, 380, 380)`.
