### ISSUE TITLE
Update lecture_feature_demo Tutorial to use `Rotation` methods

### ISSUE THREAD

**Issue by j-c-c** [ComputationalCryoEM/ASPIRE-Python#476]
The following should be deprecated and replaced with methods from [`Rotation`](https://github.com/ComputationalCryoEM/ASPIRE-Python/blob/gallery_447/src/aspire/utils/rotation.py)

https://github.com/ComputationalCryoEM/ASPIRE-Python/blob/2af8b29a5b3e8962124e9c10b483f4c4b7299de0/gallery/tutorials/lecture_feature_demo.py#L40-L44

**Comment by garrettwrong** [comment]
This was completed and merged.
