### ISSUE TITLE
Add class averaging to lecture_feature_demo.py tutorial

### ISSUE THREAD

**Issue by j-c-c** [ComputationalCryoEM/ASPIRE-Python#477]
Can we add an issue here to include class averaging in the script, which would complete this part?

_Originally posted by @janden in https://github.com/ComputationalCryoEM/ASPIRE-Python/pull/453#discussion_r722579892_

**Comment by garrettwrong** [comment]
I should be able to do this after the alignment updates in #479  🤞

**Comment by garrettwrong** [comment]
Adding a note. Thinking about adding this I am worried it may take too much time to run.  It might be more natural to have a second demo that performs the class average, CL, and 3D reconstruction when they are stable enough.

**Comment by janden** [comment]
An alternative would be to reduce the size of the dataset (and reduce the noise level) to make it all run in a reasonable time, but perhaps we're pushing the limits of realistic examples here.

**Comment by garrettwrong** [comment]
The small class averaging can take 5-10 min to run.  I'm sure it can be reduced, but still not sure even smaller one worth running twice.

The usage is now covered in two `gallery/experiments` though.  I'll leave it open for now, others can decide, but personally would close.  Eventually another class will run and more tutorials will be probably made ....

**Comment by garrettwrong** [comment]
This lecture feature demo has been overlapped by other examples.

I'm thinking it might make sense to break the individual components (Image, Volume, CL etc) up into their specific examples (or make new ones) and include sufficient narration to really explain their usage.

Our demo pipeline including class averaging will be covered by #713.

**Comment by garrettwrong** [comment]
Partially resolved by 713.

Remaining work is to break off any valuably bits from the lecture feature demo into either existing or new gallery examples.

I will just make a fresh issue for that. Too much noise here.
