### ISSUE TITLE
Move Image->MRC Stack 'save' function to the io module.

### ISSUE THREAD

**Issue by vineetbansal** [ComputationalCryoEM/ASPIRE-Python#48]
Not sure how closely we want to tie the `Image` class into the cryo-EM functionality. Ideally, this would be a general-purpose image-processing class that we could use in other settings as well. It might make more sense for this to be outside (in the MRC I/O module, for example).

_Originally posted by @janden in https://github.com/ComputationalCryoEM/ASPIRE-Python/pull/35_

**Comment by junchaoxia** [comment]
This issue is highly correlated with issue #141 and might be solved at the same time.

**Comment by garrettwrong** [comment]
Chris, would you mind checking whether this issue is still relevant and if so, what would be involved in completing it?

**Comment by chris-langfield** [comment]
There is no longer an `io` module. Also, I think at this point `ImageSource` is so tied in to the STAR file / mrcs output format and in general to representing a *cryo-EM* data source that it does not make sense to move its `save` method out. `Image` is closer to being the general-purpose image processing class described.
