### ISSUE TITLE
CI crashes, Potential shape/index bug in cov2d/denoiser

### ISSUE THREAD

**Issue by garrettwrong** [ComputationalCryoEM/ASPIRE-Python#480]
I think we may be tickling a bug via test_covar2d_denoiser.  Chris and I have each seen CI crash recently and it just happened to me again, so we need to dig in now.

Here is an example log (from Chris):
https://github.com/ComputationalCryoEM/ASPIRE-Python/runs/3792207219

@chris-langfield , do you want to see if you can figure it out?

I'm thinking it may relate to the following, since we are doing something like that in the area:

https://numpy.org/doc/stable/release/1.20.0-notes.html#boolean-array-indices-with-mismatching-shapes-now-properly-give-indexerror

https://github.com/numpy/numpy/pull/17010

```
              covar_ell_diag = np.array(
                  coeffs[:, mask_pos].T @ coeffs[:, mask_pos]
  >               + coeffs[:, mask_neg].T @ coeffs[:, mask_neg]
              ) / (2 * coeffs.shape[0])
  E           IndexError: boolean index did not match indexed array along dimension 1; dimension is 2474 but corresponding boolean dimension is 94124253513920
  
  ../.tox/py3.6-dev/lib/python3.6/site-packages/aspire/covariance/covar2d.py:152: IndexError
  ```

**Comment by garrettwrong** [comment]
I don't know why, but I haven't seen this in a while.  Let's close it and re-open if it repeats.

**Comment by chris-langfield** [comment]
Seems to have occurred again

https://github.com/ComputationalCryoEM/ASPIRE-Python/runs/4180920427
https://github.com/ComputationalCryoEM/ASPIRE-Python/actions/runs/1449796909/attempts/1
https://github.com/ComputationalCryoEM/ASPIRE-Python/runs/4269196197
https://github.com/ComputationalCryoEM/ASPIRE-Python/runs/4383338503
https://github.com/ComputationalCryoEM/ASPIRE-Python/runs/4436084326
https://github.com/ComputationalCryoEM/ASPIRE-Python/pull/517/checks?check_run_id=4460027565

**Comment by garrettwrong** [comment]
`  E           IndexError: boolean index did not match indexed array along dimension 1; dimension is 2474 but corresponding boolean dimension is 94327066072832`

Yep, that's the one. Looks like we have a bug somewhere. 🐛  Thanks for reporting and linking the logs.

**Comment by garrettwrong** [comment]
I think this only occured in the final days of python36. Closing, lets reopen this issue if we see that indexerror ever again.
