### ISSUE TITLE
`ImageSource` subclass to represent datasets with coordinate files representing picked particles

### ISSUE THREAD

**Issue by chris-langfield** [ComputationalCryoEM/ASPIRE-Python#489]
The `RelionSource` class represents datasets comprised of stacks of picked and cropped particles output by Relion. However, some datasets instead provide whole micrographs in addition to files which store the coordinates of picked particles. For example, see [EMPIAR-10061](https://www.ebi.ac.uk/empiar/EMPIAR-10061/) and [EMPIAR-10089](https://www.ebi.ac.uk/empiar/EMPIAR-10089/).

We would like to have an `ImageSource` subclass which can automatically read in these coordinate files and chop up the micrographs into stacks of particles. 

These files are often `.box` files generated by EMAN. From [their documentation](https://blake.bcm.edu/emanwiki/Eman2OtherFiles), these are simple text files containing one row for each particle:

` [lower left X coord]    [lower left Y coord]    [box size X]    [box size Y]`

These last two parameters are usually the same, leading to a square box.

One import question:

- What happens with non-square coordinate rectangles? Are these excluded or corrected by hand before datasets are uploaded, and if not, how would we fill in the rest of the square? This is important considering that denoising relies on a square frame filled with noise.

**Comment by chris-langfield** [comment]
The trend for EMAN users uploading to EMPIAR seems to be that, rather than uploading a STAR file, they simply include a `.box` file for each micrograph file in the set, named accordingly. These box files are either piled into the same directory as the mrcs, or in their own We'll have to consider how this will change our STAR file based way of interacting with data sources. 

Examples:

[10061](https://www.ebi.ac.uk/empiar/EMPIAR-10061) 
[10033](https://www.ebi.ac.uk/empiar/EMPIAR-10033/) **corrupt .mrc files**
[10057](https://www.ebi.ac.uk/empiar/EMPIAR-10057/) **unaligned micrographs**
[10022](https://www.ebi.ac.uk/empiar/EMPIAR-10022/)  **unaligned micrographs**
[10058](https://empiar.pdbj.org/entry/10058/) **unaligned micrographs**
[10089](https://www.ebi.ac.uk/empiar/EMPIAR-10089/) **unaligned micrographs**
[10030](https://www.ebi.ac.uk/empiar/EMPIAR-10030/)
[10389](https://www.ebi.ac.uk/empiar/EMPIAR-10389/)

**Comment by janden** [comment]
> What happens with non-square coordinate rectangles?

There's nothing in the math that prevents us from working with non-square images, but this would require a significant overhaul of the code, so I don't think it's happening right now. Some sensible behavior here might be to truncate the longer dimension and center along it. Another would be to error and force the user to specify a box size (which is what would happen if only a center coordinate is provided).

> We'll have to consider how this will change our STAR file based way of interacting with data sources.

If we have a single box file, we could have it point to an mrcs file with the same root name by default and let the user override it. To deal with a directory of box/mrcs files, we may want to create a wrapper ImageSource that takes in a directory and parses the box files in it.

**Comment by chris-langfield** [comment]
What I have now is code that will exclude particles that do not fit in the micrograph dimensions, based on the box size specified in the `.box` or by the user. This happens before any images are loaded (the size of the micrograph is read and all the coordinate files are compared in the `__init__`). A message displays how many particles were excluded based on the box size.

I have not come across a dataset with only one `.box` file. Garrett and I were discussing that maybe the optimal approach is to allow *either* a directory with all the `.box` and `.mrc` files in it (in which case the code will match the filenames), *or* a text file with the matching files in two columns (maybe one text file each?). I think most users can handle making a text file like that. They may be annoyed if they have to create a star file with specific column names, since there isn't any other metadata being read in from these sets.
