### ISSUE TITLE
3D Gaussian Volume with Symmetry

### ISSUE THREAD

**Issue by j-c-c** [ComputationalCryoEM/ASPIRE-Python#494]
We need to generate a 3D volume that exhibits n-fold (C_n) symmetry to test current and proposed orientation estimation features.

**Comment by garrettwrong** [comment]
Merged, closing.

**Comment by RiceOwlXinTan** [comment]
Does aspire support D_n symmetry?

**Comment by garrettwrong** [comment]
Hi, Aspire Python does not provide a method specific to D_n at this time. Thanks
