### ISSUE TITLE
Eliminate `python-box` dependency if possible

### ISSUE THREAD

**Issue by vineetbansal** [ComputationalCryoEM/ASPIRE-Python#5]
With Python 3.6, `SimpleNamespace` (and if needed, `json`) can be used to operate between a dictionary <-> object interface. Find out where this dependency is being used, and how, and try to eliminate this if possible.

**Comment by garrettwrong** [comment]
I see this is still in requirements. I think we only use it one place atm.

Thanks for writing these down.

**Comment by garrettwrong** [comment]
Trying to work an unrelated issue and ran into this guy.  Just adding some notes:

```
(aspire_col_major_1) ➜  ASPIRE-Python.col_major_1 git:(remaining_nufft_calls) ✗ python -m aspire abinitio --help
/home/garrett/anaconda3/envs/aspire_col_major_1/lib/python3.6/site-packages/box/box.py:879: BoxWarning: tom is not found in the environment. `to_toml` and `from_toml` transforms will not work
  "tom is not found in the environment. `to_toml` and `from_toml` transforms will not work", BoxWarning
/home/garrett/anaconda3/envs/aspire_col_major_1/lib/python3.6/site-packages/box/box.py:931: BoxWarning: msgpack is not found in the environment. `to_msgpack` and `from_msgpack` transforms will not work
  BoxWarning,
```
```
pip install toml
pip install msgpack
```
Will resolve if we keep python-box.

**Comment by janden** [comment]
Don't think we need this python-box stuff. Looks like it's mostly in the legacy code?

**Comment by garrettwrong** [comment]
Only there I think....  IIRC this is one of the handful of issues that will be closed if we deprecate that directory.

**Comment by garrettwrong** [comment]
Code in question has been removed by #283 . Closing
