### ISSUE TITLE
`importlib_resources` deprecation of methods

### ISSUE THREAD

**Issue by chris-langfield** [ComputationalCryoEM/ASPIRE-Python#503]
The `importlib_resources` package is used in 6 tests. The purpose of the package is to load assets and files from within a Python package in a stable way. Currently, it is used in our tests to load test data. 

As of October 2021, the methods `importlib_resources.path()`, `read_text()`, `read_binary()` [show warnings that they will be deprecated](https://importlib-resources.readthedocs.io/en/latest/history.html#v5-3-0). `read_text()` is used in `aspire.__init__.py`. Instructions on replacing them are found at https://importlib-resources.readthedocs.io/en/latest/using.html#migrating-from-legacy

**Comment by janden** [comment]
Are we sure this package is even necessary? What's preventing us from loading the files based on paths, etc.?

**Comment by chris-langfield** [comment]
Per @garrettwrong this is the preferred way to load assets from within a Python package

**Comment by garrettwrong** [comment]
Yes, I asked the same question... 

It is possible to use relative dirs, but we already know that is ugly (and simply fragile) if you leave the local dir.

What is not so obvious is that there are also other problems with `__file__` when you package up the code (specifically documentation cites `zip` but it comes up in other unsuspecting places, usually with other tools/platforms that expect a well formed package.).

I think it is only a few lines to update this.

**Comment by janden** [comment]
Ok got it. So we still need this.

As discussed in the meeting, from 3.7 onwards, we should be able to use `importlib.resources` instead.

**Comment by chris-langfield** [comment]
https://docs.python.org/3/library/importlib.html#module-importlib.resources

`importlib.resources` is new in 3.7. We can make these warnings go away now via the cut and paste conversions from the outdated api to the current one provided here by the `importlib_resources` backport: https://github.com/python/importlib_resources/blob/66ea2dc7eb12b1be2322b7ad002cefb1d364dff/importlib_resources/_legacy.py

Presumably, once we leave Python 3.6 behind, updating to `importlib.resources`, which is the recommended package and part of the standard library, will be as simple as changing `import importlib_resources` to `import importlib` and fiddling with the module hierarchy, but the methods should remain the same.

**Comment by garrettwrong** [comment]
Link is dead (typo), but can be found via the link in the first post.

Great, lets get rid of the warnings to close this issue. Can put these in a new file in utils for now (with the idea we'll delete it later). As part of the PR can make a new issue about migrating to `importlib.resources` for after the 3.9 adoption (3.6 drop).

**Comment by chris-langfield** [comment]
#534 will be merged soon. At that point, I think we can just delete `src/aspire/utils/importlib_legacy.py` and make minor naming changes. This issue will then be resolved by our moving to `importlib.resources`

**Comment by chris-langfield** [comment]
The merging of #535 will hold us over until Python 3.11
https://github.com/ComputationalCryoEM/ASPIRE-Python/pull/535#issuecomment-1007619307
> According to the link below, the methods we currently use (`path`, `read_text`), will be deprecated in Python 3.11. However, the replacement method, `files()`, is not available until Python 3.9. So, with this PR we'll be good until we add 3.11 support, at which point we'll get warnings on some CI runs. 
> 
> https://docs.python.org/3.11/library/importlib.resources.html


Close out this issue or keep it open for when that comes up?

**Comment by garrettwrong** [comment]
Lets close this one. If you want, you can make a new issue and add a tag for Python3.11
