### ISSUE TITLE
Search for local config file to override package defaults

### ISSUE THREAD

**Issue by janden** [ComputationalCryoEM/ASPIRE-Python#504]
Currently `aspire.__init__` only looks for the config file in the package root (which will be in `site-packages` for most installs). Since it's quite cumbersome to go in and edit that file, it would be better if a search is made (for example in `XDG_CONFIG_HOME`) for some `aspire.ini` file that the user could use to override defaults.

**Comment by garrettwrong** [comment]
I am thinking that you might want this for future CI (specifically the locally hosted GPU one).  It would be a straightforward way to load different backends.  Going to label/triage it.

**Comment by garrettwrong** [comment]
Closed by #749
