### ISSUE TITLE
Remove apple picker settings from config.ini

### ISSUE THREAD

**Issue by janden** [ComputationalCryoEM/ASPIRE-Python#505]
These are currently under the `[apple]` section of the config file. The user should be able override all of these in the apple picker API and some of the from the command line.

**Comment by garrettwrong** [comment]
In order to add a unit test for #468 (no centers case) it would be more straightforward to admit the particle size params so I am just going to tackle them together.

**Comment by janden** [comment]
Sounds good to me.

**Comment by garrettwrong** [comment]
Closed by 513
