### ISSUE TITLE
`Volume.project` vol_idx

### ISSUE THREAD

**Issue by garrettwrong** [ComputationalCryoEM/ASPIRE-Python#518]
`Volume.project` takes a `vol_idx` that is currently expected to be an integer.  I think that argument should support slices (ie Python's `Slice`).

Similarly, for `Volume.rotate` coming in #499  .

This is a "nice to have" and not blocking anything at the moment.

**Comment by Mehdi2402** [comment]
Hi, I would be glad to help with this. 
Is someone already working on it ?

**Comment by janden** [comment]
Ideally, this index should go away, so not sure it's worth spending that much time on.

**Comment by garrettwrong** [comment]
Right, yeah, I saw your comments in the review.  I thought maybe break it up into smaller changes, but Josh seems ready to do it in 499 so I'll close this out.  Thanks, and thank you for the interest @Mehdi2402 .
