### ISSUE TITLE
Restrict simulated gaussian volume to unit sphere.

### ISSUE THREAD

**Issue by j-c-c** [ComputationalCryoEM/ASPIRE-Python#521]
Currently, volumes simulated through the `Volume` and `Simulation` classes populate with randomly generated gaussian blobs centered arbitrarily in the volumes 3d array (potentially extending to the corners and edges of the box). Rotating this volume yields inaccuracies in the corners of the resulting rotated volume. Constraining our simulated volume to the unit sphere should resolve this. Possible solutions could be: 

- to multiply the volume by a spherical gaussian (or some other function) that has "small enough" values at the edges of the box
- to throw out individual gaussian blobs that extend past the sphere prior to populating the volume.
- ...

`testCnSymmetricVolume` currently restricts the region of the rotated volume under testing. This should be updated when resolving this issue.

**Comment by garrettwrong** [comment]
Relates to #659

**Comment by j-c-c** [comment]
This issue was covered in #659. Closing.
