### ISSUE TITLE
Ill-conditioned FFBBasis3D at high resolution

### ISSUE THREAD

**Issue by janden** [ComputationalCryoEM/ASPIRE-Python#528]
When running using the `FFBBasis3D` for `N = 32` and `ell_max = 1` (same thing happens for larger `ell_max`, but this simplifies testing), we obtain an ill-conditioned matrix. This should not happen since the Fourier–Bessel basis is close to orthogonal and should have a condition number close to one.

As an example, consider:
```
from aspire.basis import FFBBasis3D, FBBasis3D
import numpy as np
import matplotlib.pyplot as plt

N = 32

bas = FFBBasis3D((N, N, N), ell_max=1, dtype=np.float64)

A = bas.evaluate(np.eye(bas.count))

A = A.reshape(bas.count, -1)

print(np.linalg.cond(A))
```
This prints out about 1e18. If we replace `FFBBasis3D` with `FBBasis3D`, we get about 1.21. Reducing `N` to 16 gives more reasonable results.

If I had to guess, I would say this is related to the quadrature rule used in computing the polar grid, which may not be optimal for higher resolutions.

**Comment by janden** [comment]
If `ell_max = 15`, this is reported to be working fine.

**Comment by garrettwrong** [comment]
Starting to look into this now. I found one glaring numerical bug in `norm_assoc_legendre` for large `ell_max`, which I have a patch for, but it was not driving this issue. Continuing...

**Comment by janden** [comment]
Thanks! One thing you can try is to increase `n_r` and `n_theta` and see if things improve. Right now, these are more rules of thumb rather than known constants.

**Comment by chris-langfield** [comment]
With some experimenting I got the following general picture (`ell_max=1`)
- Increasing `n_r` by factors of 2, 4, etc, gives improvements in the condition number, but with diminishing returns.
- Increasing `n_theta` did not seem to have any effect
- Multiplying `n_r` *by* `N` seems to do the trick up to a high resolution (N=64 was the highest I could reasonably test on my machine).

Specifically, with the current implementation of `FFB3D`, the condition number blows up for `N>7`. Multiplying `n_r` by 2 pushed this up to around `N=16`, while multiplying `n_r` by 4 pushed it to around `N=32`. When I tried to increase `n_theta` by a factor of 2 or 4 I did not get any difference.

However, as stated, multiplying `n_r` by a factor of `N` led to consistent improvement (condition number less than 10 up to `N=64`). I'm aware from the Fourier Bessel 2D papers that there is a carefully selected sampling criterion dictating which specific basis functions are chosen, and that this influences the algorithm complexity. So it might be a problem adding this additional factor linear in `N`, as this is proportional to the radius of the disk supporting the basis. 

So far haven't been able to find the reference papers describing the Fourier Bessel 3D expansion so I have been assuming analogy with FB2D.

**Comment by chris-langfield** [comment]
In fact, looking at `FFBBasis2D._build()`:

https://github.com/ComputationalCryoEM/ASPIRE-Python/blob/3223d6c2c308af66f321ca2b0ddf3933045f904b/src/aspire/basis/ffb_2d.py#L39-L42

so `n_r = 4* (0.5*n_res)(0.5) = n_res`.

In FFB 2D we set the number of radial quadrature points to be exactly the resolution..

Whereas for FFB 3D:

https://github.com/ComputationalCryoEM/ASPIRE-Python/blob/3223d6c2c308af66f321ca2b0ddf3933045f904b/src/aspire/basis/ffb_3d.py#L57-L59

So in particular when setting `ell_max=1`, we are just getting two radial quadrature points no matter what the resolution is, if I'm understanding correctly.

**Comment by janden** [comment]
> I'm aware from the Fourier Bessel 2D papers that there is a carefully selected sampling criterion dictating which specific basis functions are chosen, and that this influences the algorithm complexity.

So the sampling condition dictates what basis vectors are calculated. Once that is determined, there are formulas for how the number of grid points is chosen. Here the bug seems to be with the latter calculation instead of the former.

> In FFB 2D we set the number of radial quadrature points to be exactly the resolution..

Right it makes sense to do something similar for FFB3D then. Let's make an issue to find out what the proper number of quadrature points should be.

**Comment by chris-langfield** [comment]
I believe this line from https://arxiv.org/pdf/1412.0781.pdf (just after Eq. 19) indicates the selection of the quadrature points is a rule of thumb type thing, as you mentioned higher up in the issue.

<img width="349" alt="Screen Shot 2022-02-03 at 11 47 53 AM" src="https://user-images.githubusercontent.com/34426450/152388647-34e36766-8006-4a6c-b82a-0c46f33131f7.png">

**Comment by oscarmickelin** [comment]
Hi everyone,

This should probably be a separate issue, but there might be some more accuracy problems with FFBBasis. For instance, the code below transforms a 3D Gaussian into the basis and then back into the Cartesian grid and even with the change above, my machine makes the FFBBasis a lot less accurate than FBBasis (1st plot is ground truth, 2nd is FFB, 3d is FB).


```python
from aspire.basis import *
import numpy as np
import matplotlib.pyplot as plt
from aspire.utils.fft import centered_fft3, centered_ifft3

def make_spot_3d(bright, spread, x0,y0,z0, s):
    # Create x and y indices
    x = np.linspace(-3, 3, s[0])
    y = np.linspace(-3, 3, s[1])
    z = np.linspace(-3, 3, s[2])

    X, Y, Z = np.meshgrid(x, y, z)
    Intensity = bright*np.exp(-((X-x0)/spread)**2
                                        -((Y-y0)/spread)**2
                                        -((Z-z0)/spread)**2)

    return Intensity
   
 
M = 32
s3d = (M,M,M)
lmax = 7
bas = FFBBasis3D(s3d, ell_max = lmax, dtype=np.float64)
bas2 = FBBasis3D(s3d, ell_max = lmax, dtype=np.float64)

x = make_spot_3d(1,1/2.,0,1/2.,1/2.,s3d)

c = bas.expand(x)

c2 = bas2.evaluate_t(centered_fft3(x))
y = bas.evaluate(c)

y2 = centered_ifft3(bas2.evaluate(c2))
plt.subplot(3,1,1)
plt.plot(x.flatten())
plt.subplot(3,1,2)
plt.plot(y.flatten())
plt.subplot(3,1,3)
plt.plot(y2.flatten())
plt.show()
```

**Comment by janden** [comment]
It might actually be another consequence of the same bug. If you want, you can try checking out the branch in #557 and see whether you observe the same behavior.

**Comment by chris-langfield** [comment]
> even with the change above, my machine makes the FFBBasis a lot less accurate than FBBasis (1st plot is ground truth, 2nd is FFB, 3d is FB).

If I'm understanding correctly, Oscar's example is with the change? @oscarmickelin which specific `n_r` value did you use?

Thanks

**Comment by oscarmickelin** [comment]
Yes, it is with the change in n_r which was not enough to get rid of the effect. But also increasing n_phi did work for me, so e.g.

        n_r = 128*int(self.ell_max + 1)
        n_theta = int(2 * self.sz[0])
        n_phi = 128*int(self.ell_max + 1)

does seem to achieve the same accuracy as FBBasis!

**Comment by chris-langfield** [comment]
Got it thanks! I think this can be a separate issue for tracking purposes. Feel free to make it, or I will once I get around to taking a look 😄

**Comment by chris-langfield** [comment]
It's worth noting that the condition number is still worse than FB3D even with the fix, so some loss of accuracy is to be expected, right? I'm not sure what our benchmark or guarantee is as far as this trade-off goes

**Comment by janden** [comment]
But the change in #557 is to make `n_r` proportional to the size of the volume, not `ell_max`. Even with, that you see the same error?

Also I'm seeing that you use `expand` for FB but `evaluate_t` for FFB. You should be using `expand` for both.

> It's worth noting that the condition number is still worse than FB3D even with the fix, so some loss of accuracy is to be expected, right?

Not really. The condition number indicates how far we deviate from an orthonormal basis, but with the CG iteration in `expand`, we should get comparable reconstruction accuracy.

**Comment by oscarmickelin** [comment]
Yes, if n_phi is not increased, the change in n_r is not enough to get rid of the effect. The above code snippet is for fixed volume size, so it has n_r larger than the change in #557.

As for expand for FB, this is just for speed: even using FB with evaluate_t is more accurate than using expand with FFB as shown in the generated figures

**Comment by janden** [comment]
> Yes, if n_phi is not increased, the change in n_r is not enough to get rid of the effect. The above code snippet is for fixed volume size, so it has n_r larger than the change in #557.

All right.

> As for expand for FB, this is just for speed: even using FB with evaluate_t is more accurate than using expand with FFB as shown in the generated figures

Yes but they're not comparable. Since neither FB or FFB are orthonormal, I'm not sure what is gained by comparing their adjoints. Would you mind posting the figures and MSE's?

**Comment by oscarmickelin** [comment]
The figure is attached: top is ground truth, the middle is transforming with FFB and then back, and bottom is transforming with FB and then back (all using expand). The relative residuals are 36% for FFB and 0.2% for FB.


This is all for:

 n_r = int(np.ceil(4 * self.rcut * self.kcut))
 n_theta = int(2 * self.sz[0]) 
 n_phi = int(self.ell_max + 1) 



![ffb_vs_fb](https://user-images.githubusercontent.com/40873271/152832682-f9e41709-9810-4594-a20a-ce368f0f027f.png)

**Comment by janden** [comment]
Ok. It's a little hard to see where the errors are in the plots above. Perhaps plotting the residual would make more sense here. Also looking at the images in 2D might give some clue to what's going on.

I notice in the original example you do FFT and IFFT for the FB decomposition. These basis objects are only defined for real-valued images, so this might create problems (although clearly that's not the case here, perhaps because the original image is symmetric and its FT is therefore real?).

**Comment by oscarmickelin** [comment]
A 2d residual plot of the slice x[:,:,32] - y[:,:,32] is attached! (not relative residual)

Yeah, for FB, I've extended it to be able to handle complex values, but this isn't affecting the performance of FFB.

![ffb_2d_res](https://user-images.githubusercontent.com/40873271/152836683-6ec64ee9-eee5-494d-9344-94d5d8a36d55.png)

**Comment by janden** [comment]
Continuing the discussion in #559. I suggest we close this given that #557 was merged.
