### ISSUE TITLE
Filename of saved `.mrcs` from `ImageSource.save()`

### ISSUE THREAD

**Issue by chris-langfield** [ComputationalCryoEM/ASPIRE-Python#545]
The current behavior of `ImageSource.save()` is that it accepts a STAR filename for output, grabs the stem of this filename, and tacks on `_{first_index}_{last_index}.mrcs`. This is true whether the savemode is "single" or "multiple". 

Following discussion in #520, we may want to have `ImageSource.save()` return these filename(s) and/or change the behavior, at least for "single" savemode.

**Comment by janden** [comment]
A more forward-compatible solution would be to return an `info` dict with different fields that could be added later on. On the other hand, I'm not sure what else might be returned here, so it's perhaps safe enough to just return a list of MRC files used.

**Comment by chris-langfield** [comment]
Would that be a good place for a history of the source (filters/transformations applied etc.)?

**Comment by janden** [comment]
No I don't think so. Most of that should be contained in the STAR file already. All we want here is additional information from the `save` operation. This might become relevant later on when we start saving the filters as MRC files, so maybe it's good to make this forward-compatible (i.e., with a dict).

**Comment by garrettwrong** [comment]
We can probably implement this dict solution. Seems like a reasonably small change that we can just get out of the way.

**Comment by chris-langfield** [comment]
Closed by #719
