### ISSUE TITLE
`importlib.resources` deprecation of methods

### ISSUE THREAD

**Issue by chris-langfield** [ComputationalCryoEM/ASPIRE-Python#546]
According to the link below, the methods we currently use (`path`, `read_text`) as part of the `importlib.resources` Python package resource manager, will be deprecated in Python 3.11. 

However, the replacement method, files(), is not available until Python 3.9. Once our lowest supported version is 3.9 we may want to update the methods to avoid warnings.

https://docs.python.org/3.11/library/importlib.resources.html

**Comment by garrettwrong** [comment]
Python 3.11 has an expected release 2022-10-24.  For us this would roughly coincide with potentially dropping 3.7.

If I read this correctly, we might have some situation where Python (3.7 and) 3.8 will conflict with code supporting 3.9-3.11.  Following that link, it seems like the code might still function for 3.11, perhaps with deprecation warnings.

We should check what happens and make a plan... maybe using the latest 3.11 release candidate...

**Comment by garrettwrong** [comment]
Update. Following #749 from `importlib` we will only have `path` in unit tests and `import_module` in our init.  `import_module` looks to be stable, so no problem there.

I think the easier thing to do is to just workaround this one function with a utility until 3.9. I think I can put a patch together in a few minutes.

**Comment by garrettwrong** [comment]
Closed by #754
