### ISSUE TITLE
`FFBBasis2D.evaluate()` returns an `Image` but other bases return `ndarray`

### ISSUE THREAD

**Issue by chris-langfield** [ComputationalCryoEM/ASPIRE-Python#553]
https://github.com/ComputationalCryoEM/ASPIRE-Python/blob/3223d6c2c308af66f321ca2b0ddf3933045f904b/src/aspire/basis/ffb_2d.py#L187-L190

Compare:

https://github.com/ComputationalCryoEM/ASPIRE-Python/blob/3223d6c2c308af66f321ca2b0ddf3933045f904b/src/aspire/basis/fb_2d.py#L238-L240

https://github.com/ComputationalCryoEM/ASPIRE-Python/blob/3223d6c2c308af66f321ca2b0ddf3933045f904b/src/aspire/basis/fb_3d.py#L182-L184

https://github.com/ComputationalCryoEM/ASPIRE-Python/blob/3223d6c2c308af66f321ca2b0ddf3933045f904b/src/aspire/basis/ffb_3d.py#L276-L279

We should probably be consistent and just return an `Image`/`Volume` every time

**Comment by garrettwrong** [comment]
Basis should return Image/Volumes. The original author was consistent in not implementing them, unfortunately.

**Comment by janden** [comment]
So the idea here is that:

- All `evaluate`s should take an `ndarray` as input and output a `Volume`/`Image`
- All `evaluate_t`s and `expand`s should take an `Volume`/`Image` as input (but will cast an `ndarray` to the appropriate cast after logging the warning) and redurn an `ndarray`

Certain parts of this is implemented in certain `Basis` classes and other parts in other classes. To sort this out, the best way may be to define `evaluate`, `evaluate_t`, and `expand` in a superclass and have these do the necessary checks and casts, then call `_evaluate`, `_evaluate_t`, `_expand`, and so on that will be overriden in subclasses and operate on `ndarrays`. Obviously this would have to be somewhat smart in checking whether the basis is 2D (in which case we're dealing with `Image`s) or 3D (in which case we're dealing with `Volume`s).

**Comment by chris-langfield** [comment]
Closed by #618
