### ISSUE TITLE
Validation of `CoordinateSource` behavior. 

### ISSUE THREAD

**Issue by chris-langfield** [ComputationalCryoEM/ASPIRE-Python#556]
We should validate the behavior of `CoordinateSource` more stringently with regard to real datasets. 

The relationship between the `Lower left corner` standard of `.box` files with the `upper left corner` origin of MRC files also needs to be clarified. 

One first step is to crop a bunch of particles from a real micrograph and average the results to make sure we are picking particles.

**Comment by chris-langfield** [comment]
First step: loading a bunch of particles and averaging them.

Results 10017:
![avg_10017](https://user-images.githubusercontent.com/34426450/152403580-a40bdfdb-732f-40b0-b688-1c8dccaebe92.png)

**Comment by chris-langfield** [comment]
Results from 10061 (from .box files)
![avg_10061](https://user-images.githubusercontent.com/34426450/152568917-20f3c289-2f2a-4203-b496-692210fc8b6a.png)

**Comment by chris-langfield** [comment]
Last point of validation: are images rotated by 90 degrees with picked from a micrograph?

Note that when loading and writing to `.mrc`, the X and Y directions are flipped. That is, the first axis is Y, and the second is X. However, taking this into account, we can see that the relationship between the box format, the `CoordinateSource` logic, and this MRC convention preserves the correct orientation.

The below script demonstrates this using the SciPy raccoon:

```python
from scipy.misc import face
import matplotlib.pyplot as plt
import mrcfile
from aspire.image import Image
from aspire.source import BoxesCoordinateSource
import numpy as np
import os

# Load Jim and then crop him to a 128x128 particle                                                                                                         
Jim = face(gray=True)[:,256:].astype(np.float32)
img = Image(Jim)
img = img.downsample(128)
plt.imshow(img[0],cmap="gray")
plt.show()
```
![Jim](https://user-images.githubusercontent.com/34426450/152570536-de71c418-2af5-4872-8ada-529711f5b254.png)

```python

# Put Jim somewhere in a sample micrograph                                                                                                                 
mrc_data = np.zeros((2500,2500))
# mrc convention -> (Y,X)
mrc_data[1600:1728,1200:1328] = img.asnumpy()
plt.imshow(mrc_data, cmap="gray")
plt.show()
os.system("rm jim.mrc")
mrc = mrcfile.open("jim.mrc", mode="w+")
mrc.set_data(mrc_data.astype(np.float32))
mrc.close()
# confirm that when we re-open the mrc, Jim has not been turned on his side                                                                                
with mrcfile.open("jim.mrc", mode="r+") as jim:
    plt.imshow(jim.data,cmap="gray")
    plt.show()

```
Both images are identical:
![jimparticle](https://user-images.githubusercontent.com/34426450/152570679-0d4c19b4-a509-4adc-9293-72e5e1dd5daa.png)

```python
# Make a box file so we can find Jim                                                                                                                       
with open("jim.box","w") as box:
    box.write("1200\t1600\t128\t128\n")

# Load as a particle                                                                                                                                       
JimSource = BoxesCoordinateSource([("jim.mrc", "jim.box")])
imgs = JimSource.images(0,1)
plt.imshow(imgs[0], cmap="gray")
plt.show()
```
Displaying the cropped particle, it has the same orientation as when it was written
![Jim](https://user-images.githubusercontent.com/34426450/152570536-de71c418-2af5-4872-8ada-529711f5b254.png)

**Comment by janden** [comment]
Thanks! So we're good here?

**Comment by chris-langfield** [comment]
Yes, I believe so. Was good to double check these things.
