### ISSUE TITLE
High reconstruction error in FFBasis3D

### ISSUE THREAD

**Issue by janden** [ComputationalCryoEM/ASPIRE-Python#559]
Hi everyone,

This should probably be a separate issue, but there might be some more accuracy problems with FFBBasis. For instance, the code below transforms a 3D Gaussian into the basis and then back into the Cartesian grid and even with the change above, my machine makes the FFBBasis a lot less accurate than FBBasis (1st plot is ground truth, 2nd is FFB, 3d is FB).

```python
from aspire.basis import *
import numpy as np
import matplotlib.pyplot as plt
from aspire.utils.fft import centered_fft3, centered_ifft3

def make_spot_3d(bright, spread, x0,y0,z0, s):
    # Create x and y indices
    x = np.linspace(-3, 3, s[0])
    y = np.linspace(-3, 3, s[1])
    z = np.linspace(-3, 3, s[2])

    X, Y, Z = np.meshgrid(x, y, z)
    Intensity = bright*np.exp(-((X-x0)/spread)**2
                                        -((Y-y0)/spread)**2
                                        -((Z-z0)/spread)**2)

    return Intensity
   
 
M = 32
s3d = (M,M,M)
lmax = 7
bas = FFBBasis3D(s3d, ell_max = lmax, dtype=np.float64)
bas2 = FBBasis3D(s3d, ell_max = lmax, dtype=np.float64)

x = make_spot_3d(1,1/2.,0,1/2.,1/2.,s3d)

c = bas.expand(x)

c2 = bas2.evaluate_t(centered_fft3(x))
y = bas.evaluate(c)

y2 = centered_ifft3(bas2.evaluate(c2))
plt.subplot(3,1,1)
plt.plot(x.flatten())
plt.subplot(3,1,2)
plt.plot(y.flatten())
plt.subplot(3,1,3)
plt.plot(y2.flatten())
plt.show()
```

_Originally posted by @oscarmickelin in https://github.com/ComputationalCryoEM/ASPIRE-Python/issues/528#issuecomment-1029325156_

**Comment by janden** [comment]
See more on this in #528.

**Comment by janden** [comment]
Played around with this a bit. Can reproduce it with the code below:

```python
import numpy as np

from aspire.utils.misc import gaussian_3d
from aspire.basis import FBBasis3D, FFBBasis3D

N = 16
ell_max = 7
dtype = np.float32

x = gaussian_3d(N).astype(dtype)

fb_basis = FBBasis3D((N,) * 3, ell_max=ell_max, dtype=dtype)
ffb_basis = FFBBasis3D((N,) * 3, ell_max=ell_max, dtype=dtype)

c_fb = fb_basis.expand(x)
c_ffb = ffb_basis.expand(x)

y_fb = fb_basis.evaluate(c_fb)
y_ffb = ffb_basis.evaluate(c_ffb)

print(f"{np.linalg.norm(x - y_fb)=}")
print(f"{np.linalg.norm(x - y_ffb)=}")
```

Replacing `ell_max = 7` with `ell_max = None` brings the FFB error down to that of FB.

**Comment by janden** [comment]
Looks like the issue is that the number of quadrature points in `phi` (the latitude) also depends (incorrectly) on `ell_max`. Submitting a PR to fix.

**Comment by garrettwrong** [comment]
We should discuss this on Thursday if there is time.  Mainly I'm interested in how much of this issue was resolved by 563 and how much remains...

**Comment by garrettwrong** [comment]
Closing after meeting discussion.
