### ISSUE TITLE
new class for image coefficients 

### ISSUE THREAD

**Issue by junchaoxia** [ComputationalCryoEM/ASPIRE-Python#56]
Currently the FB or PSWF coefficients of images are calculated from the memory of images and stored in memory. This might cause memory problem when performing analysis for large systems with millions images. It will be better have similar mechanism as `ImageSource ` to calculate the coefficients when reading the images and output as mrc file.

**Comment by garrettwrong** [comment]
I think this is largely handled by calling evaluate/evaluate_t on chunks of a stack.  There is perhaps some use for better coefficient handling, but I'm not sure it is a CoefficientSource-ish thing.  I'll leave open for now, but I am someone inclined to close this.

**Comment by janden** [comment]
Yeah not sure this level of abstraction is needed, even in the far future. Can reopen if that's the case.
