### ISSUE TITLE
`PolarBasis2D` default parameter bug.

### ISSUE THREAD

**Issue by j-c-c** [ComputationalCryoEM/ASPIRE-Python#560]
When initializing a `PolarBasis2D` object without specifying the parameter `nrad`, an attempt is made to set it as `self.nrad = self.nres // 2`: 
https://github.com/ComputationalCryoEM/ASPIRE-Python/blob/3223d6c2c308af66f321ca2b0ddf3933045f904b/src/aspire/basis/polar_2d.py#L32-L42

In this case, `self.nres` is defined in the parent class `Basis` and because `super()` is called after the attempt to assign `self.nrad`, an `AttributeError` occurs. 

This should be a quick fix of moving `super()` above the assignments of `nrad` and `ntheta`.

**Comment by janden** [comment]
Right. Calls to `super().__init__` should generally be done at the top of the subclass `__init__`.

**Comment by garrettwrong** [comment]
Closing issue, patch merged.
