### ISSUE TITLE
`np.squeeze()` in `ImageSource.get_metadata()`

### ISSUE THREAD

**Issue by chris-langfield** [ComputationalCryoEM/ASPIRE-Python#564]
`np.squeeze()` is used in `ImageSource.get_metadata()` to remove axes of length 1. This behavior does not work on all metadata tables (represented as numpy arrays), so we have `np.atleast_1d` calls in `ImageSource` getters for fields with 1 column. This covers the case where there is 1 particle and 1 column. 

We should figure out the situations where `np.squeeze()` actually does something to the table and implement a cleaner, more obvious way of removing extraneous axes.

**Comment by garrettwrong** [comment]
Chris, I'm not sure I follow what is described here.  

Is this something where it would make sense to instead force everything to be at_least1d instead of removing it then atleast_1d'ing it somewhere later?

**Comment by chris-langfield** [comment]
Okay, after looking into this, I believe `np.atleast_1d` is the cleanest solution. I don't see anything to be gained from trying to mess around with the `get_metadata` internals right now.
