### ISSUE TITLE
Replace `ensure` with `assert`

### ISSUE THREAD

**Issue by chris-langfield** [ComputationalCryoEM/ASPIRE-Python#578]
See discussion on #522 

`ensure` is just a wrapper for `assert` statements. We should move towards removing this and aim to use the standard library tool. Whether as we encounter it, or as one wholesale replacement in a PR.

**Comment by garrettwrong** [comment]
Just waiting on unit tests for this now.  This was good application for regular expressions. I did it in following short steps.

1) grep to find and convert multiline ensures to single line. quick and dirty, intentionally dont care about formatting now, scripts will fix it. (stacked files up in editor and smashed ~5min)
2) test and run regexp explained below
3) run isort and black over the code to clean it up
4) clean up any residual imports and one straggler (didn't bother to regex it)

<img width="1787" alt="Screen Shot 2022-02-18 at 12 41 52 PM" src="https://user-images.githubusercontent.com/47759732/154739843-0fbed1ba-f4a6-4be1-9e7b-53659b07a00b.png">

```
import pathlib
import re

regex = r"ensure\((.*?),(.*)\)"

subst = "assert \\1, \\2"

for fn in pathlib.Path(".").glob("**/*.py"):

    res = []
    with open(fn, "r") as f:
        for line in f:
            res.append(re.sub(regex, subst, line, 0))

    with open(fn, "w") as f:
        f.write("".join(res))
```

**Comment by chris-langfield** [comment]
Nice!

**Comment by garrettwrong** [comment]
Closed by 583.
