### ISSUE TITLE
`CoordinateSource` file validation is so stringent that it doesn't allow floats as coordinates

### ISSUE THREAD

**Issue by chris-langfield** [ComputationalCryoEM/ASPIRE-Python#581]
This logic should be modified to allow coordinate files to contain floats. `isnumeric()` fails for floats.

https://github.com/ComputationalCryoEM/ASPIRE-Python/blob/36cc4ecf157c3c2a1de3fa503a863182792369ee/src/aspire/source/coordinates.py#L488-L492

**Comment by garrettwrong** [comment]
Yeah, surprised we didn't see it. Send your fix over and we can get it in this release.
