### ISSUE TITLE
Elementwise division in covar2d

### ISSUE THREAD

**Issue by janden** [ComputationalCryoEM/ASPIRE-Python#59]
The line

https://github.com/ComputationalCryoEM/ASPIRE-Python/blob/1e73fceb4bab1e8e034d249614ea42c48c26d73f/src/aspire/estimation/covar2d.py#L247

has elementwise division (`np.divide`) instead of a solve, which would yield the wrong answer. Has this code been tested against the MATLAB version to ensure they have the same outputs?

**Comment by junchaoxia** [comment]
You are right. The shrinking method to the 2D covariance of coefficients Cov2D has been not done yet. Unit tests will be developed.

**Comment by junchaoxia** [comment]
This issue has been fixed in the commit de34c40 and the unit test is added in the commit 90829f4.
