### ISSUE TITLE
Move `Basis._getfbzeros` to a standalone function

### ISSUE THREAD

**Issue by janden** [ComputationalCryoEM/ASPIRE-Python#591]
This has no business being in the `Basis` class as it is only specific to the FB bases. We also need to be able to call it easily from tests. The name should also be modified to follow convention, so `get_besselj_zeros` would be more appropriate. Finally, it should be tested independently: make sure the points it actually returns are zeros of the Bessel functions and do a quick check to make sure that the Bessel functions are non-zero on some grids between the zeros.

**Comment by janden** [comment]
Looking closer at this, it's not clear what `_getfbzeros` does that `num_besselj_zeros` doesn't do. The latter also seems inappropriately named since it not only calculates the number of zeros, but actually returns the zeros themselves. More investigation is needed here.

**Comment by chris-langfield** [comment]
`ell` is k and `k` is q with reference to this paper right?

https://arxiv.org/pdf/1412.0781.pdf

**Comment by chris-langfield** [comment]
I agree that this method doesn't belong in `Basis`. However, it depends on no less than 4 class attributes which would have to become arguments (`self.ell_max`, `self.nres`, `self.ndim`, `self.dtype`) and it also modifies/creates two class attributes which are needed by the class later on (`self.ell_max` and `self.k_max`).

It was possible to pull this out into `basis_utils.py`, but ugly. How about making this function a method in `SteerableBasis`?

**Comment by chris-langfield** [comment]
I agree it would be good to test independently. The actual computation of the zeros depends on a handful of functions in `basis_utils.py` that are barely commented. I think regardless of what we do with `Basis._getfbzeros`, this could be cleaned up a bit.

**Comment by chris-langfield** [comment]
Closed by #599
