### ISSUE TITLE
`Basis` objects don't seem to be checking sizes

### ISSUE THREAD

**Issue by janden** [ComputationalCryoEM/ASPIRE-Python#593]
The following code runs:
```python
import numpy as np

from aspire.basis import FBBasis2D

L = 16

basis = FBBasis2D((L, L), dtype=np.float64)

im = np.random.randn(2*L, 2*L).astype(basis.dtype)

coef = basis.expand(im)
```
but should error. We should find out how widespread this behavior is (just `expand` or also `evaluate_t` or even `evaluate`?) and in what classes (just `FBBasis2D` or others as well) and then fix it.

**Comment by chris-langfield** [comment]
This happens for all FB bases, but not for the PWSF, etc. as far as I can tell. Correction: this happens for `FPSWFBasis2D` but not `PWSFBasis2D`
