### ISSUE TITLE
Theoretical basis of Bessel root-finding 

### ISSUE THREAD

**Issue by chris-langfield** [ComputationalCryoEM/ASPIRE-Python#597]
The functions `num_besselj_zeros`, `besselj_zeros`, `check_besselj_zeros` are almost exact ports from the MATLAB code, but are lacking clear comments.

These in turn are modifications of this script by Jonas Lundgren:

https://www.mathworks.com/matlabcentral/mlc-downloads/downloads/submissions/26639/versions/5/previews/zerobess.m/index.html

When attempting to work out what exactly these functions are doing to estimate the first few zeros, I came across several tricks that I haven't been able to find a single definitive source for. e.g.,

https://github.com/ComputationalCryoEM/ASPIRE-Python/blob/6cb389edf21e811224cc98f4fde0d63ed778b9a7/src/aspire/basis/basis_utils.py#L165-L174

Roughly, this computes initial guesses based on powers of `nu`, the real number order of the Bessel function. The closest literature I could find for this is in the following paper:

Elbert, Árpád. “Some recent results on the zeros of Bessel functions and orthogonal polynomials.” Journal of Computational and Applied Mathematics 133 (2001): 65-83.

(Section 1.3 starting around eqn 1.7)

The powers as well as the hardcoded values in our code also appear here. 

See also: https://www.boost.org/doc/libs/1_63_0/libs/math/doc/html/math_toolkit/bessel/bessel_root.html

#596 adds some commenting and clarity but does not resolve the core issue-- the source of these approximations and initial guesses. In particular the expansion in powers of `nu`, and the subsequent use of the spacing of zeros to estimate further roots.

**Comment by chris-langfield** [comment]
Some paraphrased comments by @janden from the PR thread:

> In relation to the following lines:
> 
> https://github.com/ComputationalCryoEM/ASPIRE-Python/blob/6cb389edf21e811224cc98f4fde0d63ed778b9a7/src/aspire/basis/basis_utils.py#L27-L31
> 
> I think it's rather checking that the second-order differences are zero or negative. If they were all zero, we'd have a three-term recurrence formula for the zeros and wouldn't need to find them this way (however it is true asymptotically)
> 
> 
> 
> 
>  Right. Of course. From Zhao & Singer (2013):
>  
>  ![image](https://user-images.githubusercontent.com/3976052/161067610-bf8cc3bf-e1e9-4cbe-902d-1613bbd9e7f8.png)
>  
>  So at large `q` the approximate spacing between zeros is π. In fact, we use this in
>  
> https://github.com/ComputationalCryoEM/ASPIRE-Python/blob/6cb389edf21e811224cc98f4fde0d63ed778b9a7/src/aspire/basis/basis_utils.py#L193
>  
> to initialize the search for zeros by using the last zero and adding multiples of π when the number of zeros is large enough.
>

**Comment by garrettwrong** [comment]
I think this issue of code comments was addressed in 596, closing.
