### ISSUE TITLE
Downsampling gridpoint test

### ISSUE THREAD

**Issue by chris-langfield** [ComputationalCryoEM/ASPIRE-Python#608]
We can use this issue for ongoing discussions of the new downsampling method

Will be updating this issue with progress on the problem @janden.

**Comment by chris-langfield** [comment]
### Testing the MATLAB code 

**Summary: Only even-even works**

We can generate spherically symmetric Gaussians in ASPIRE with

```python
from aspire.utils.misc import gaussian_3d
from aspire.volume import Volume
sigma = 0.1
vol = gaussian_3d(64, sigma=(L * sigma,) * 3)
Volume(vol).save("gaussian_sigma_0.1_64.mrc")
vol = gaussian_3d(65, sigma=(L * sigma,) * 3)
Volume(vol).save("gaussian_sigma_0.1_65.mrc")
```

Now in MATLAB we can load them and then slice the middle to get a symmetric 2d gaussian.

```matlab
initpath
gs64 = mrc2mat("gaussian_sigma_0.1_64.mrc")
gs65 = mrc2mat("gaussian_sigma_0.1_65.mrc")
% Get the center slices
gs2d_64 = gs64(:,:,32)
gs2d_65 = gs65(:,:,32)
% perform the downsampling for the cases we want to test
gs2d_64_32 = cryo_downsample(gs2d_64, 32)
gs2d_64_33 = cryo_downsample(gs2d_64, 33)
gs2d_65_32 = cryo_downsample(gs2d_65, 32)
gs2d_65_33 = cryo_downsample(gs2d_65, 33)
% compute the center points (+1 to each because we're not counting from 0)
ctr_64 = floor(64/2) + 1 % 33
ctr_65 = floor(65/2)  + 1 % 33
ctr_32 = floor(32/2) + 1 % 17
ctr_33 = floor(33/2) + 1 % 17

% compare the center points for each case
% even even
gs2d_64(ctr_64,ctr_64) - gs2d_64_32(ctr_32,ctr_32)
ans = -5.9605e-08
% even odd
gs2d_64(ctr_64,ctr_64) - gs2d_64_33(ctr_33,ctr_33)
ans = 0.0218
% odd even
gs2d_65(ctr_65,ctr_65) - gs2d_65_32(ctr_32,ctr_32)
ans = 0.0058
% odd odd
gs2d_65(ctr_65,ctr_65) - gs2d_65_33(ctr_33,ctr_33)
ans = 0.0055
```

For sanity check, the images below are `gs2d_64` 

![gs2d_64](https://user-images.githubusercontent.com/34426450/162307782-9d6d53ce-e654-4cdc-bec7-a0ddeeb7bf54.png)

and `gs2d_65`

![gs2d_65](https://user-images.githubusercontent.com/34426450/162308223-388ac492-4847-4903-9667-016e36706b9e.png)

**Comment by chris-langfield** [comment]
### Testing the Python Code

We see practically the same pattern when replicating with the new downsampling method in Python

```python
sigma = 0.1
vol64 = gaussian_3d(64, sigma=(L * sigma,) * 3)
vol65 = gaussian_3d(65, sigma=(L * sigma,) * 3)
img64 = Image(vol64[:,:,32])
img65 = Image(vol65[:,:,32])

img64_32 = img64.downsample(32)
img64_33 = img64.downsample(33)
img65_32 = img65.downsample(32)
img65_33 = img65.downsample(33)

# even even
print(img64[0,64//2,64//2] - img64_32[0,32//2,32//2])
# even odd
print(img64[0,64//2,64//2] - img64_33[0,33//2,33//2])
# odd even
print(img65[0,65//2,65//2] - img65_32[0,32//2,32//2])
# odd odd
print(img65[0,65//2,65//2] - img65_33[0,33//2,33//2])

0.0
0.039683640003204346
0.0058997273445129395
0.005548596382141113
```

**Comment by chris-langfield** [comment]
Testing out the idea mathematically:

The below is the formula for the DFT:

`X[k] = Sum(n=0 -> N-1) x[n] exp(-2*pi*j*k*n / N)`

Let's say we have a signal of length 4

`[x0, x1, x2, x3]`

[FFT]

`[DC, X1, X2, X3]`

[FFTSHIFT] Swaps the center with the DC component. Everything to the right of the center goes to the front,
and everything to the left of the center goes to the end of the sequence. That is, X3 is moved to the position after X2 and X1 is moved to the position after DC.

`[X2, X3, DC, X1]`

[CROP]

`[X3, DC]`

[IFFTSHIFT] Swaps the center and the DC component again.

`[DC, X3]`

I'm a little stuck on how to unravel this last part, which is the cropped, unshifted FFT, back to real space to confirm that the original center (i.e. `x2`) is preserved.

**Comment by janden** [comment]
I've looked through the math, and the center value should always be preserved in the bandlimited case. This is because

```x[n] = 1/N * sum(k=-N/2 → N/2-1) X[k] exp(-2*pi*i*k*n/N)```

so for `n = 0`, we obtain

```x[n] = 1/N * sum(k=-N/2 → N/2-1) X[k]```

If we're bandlimited, `X[k]` for `abs(k)` large enough are all zero and all that happens is that the sum is taken from `M/2` to `M/2-1` (with appropriate modification if `M` is odd) and that `1/N` is replaced by `1/M`. Consequently, after downsampling the center value is just multiplied by `N/M`, which we can (and I believe do) compensate for.

I'm not sure which code you're testing above, but I assume it's the method in #606. In that case, a potential issue is that the image is not shifted (with `fft.ifftshift`) before calling the FFT (this is what the `fft.centered_fft2` call did before). As a result, the value that is compensated is the upper left corner (which is the center for the definition of `fft.fft2`).

**Comment by chris-langfield** [comment]
Using `centered_fft2` and `centered_ifft2` appears to have done the trick. Somehow these methods are accounting for the even/odd cases in a way that doing `fft2` and then `fftshift`, and `ifftshift` followed by `ifft2`, are not.

**Comment by chris-langfield** [comment]
I believe @janden solved this so we can close to reduce clutter
