### ISSUE TITLE
MATLAB hold-overs in Fourier Bessel zero finding method

### ISSUE THREAD

**Issue by chris-langfield** [ComputationalCryoEM/ASPIRE-Python#609]
The following should be modified to be a list of arrays (possibly of variable lengths, for each ell), rather than a zero padded NumPy array.

cf. #599 

https://github.com/ComputationalCryoEM/ASPIRE-Python/blob/6cb389edf21e811224cc98f4fde0d63ed778b9a7/src/aspire/basis/basis.py#L79-L85

**Comment by garrettwrong** [comment]
Merged, closing.
