### ISSUE TITLE
Add a `.zenodo.json` file to the repository to correctly display authors on Zenodo

### ISSUE THREAD

**Issue by chris-langfield** [ComputationalCryoEM/ASPIRE-Python#613]
Currently the authors list on Zenodo has to be manually rearranged. We can create a `.zenodo.json` file to determine the order, display names, and affiliations of all authors.

https://github.com/pyxem/pyxem/issues/824

**Comment by chris-langfield** [comment]
Wanted to point out that Zenodo has a sandbox area where we can test out uploads to make sure our JSON is doing the right thing.

https://developers.zenodo.org/#testing

I haven't played around with this yet, but it could be a good starting point if we wanted to add even more customization beyond just the authors

**Comment by garrettwrong** [comment]
Merged.
