### ISSUE TITLE
3D Downsampling

### ISSUE THREAD

**Issue by chris-langfield** [ComputationalCryoEM/ASPIRE-Python#617]
#606 will close #140 by making our 2D downsampling method identical to the MATLAB code.

3D downsampling, (i.e. `Volume.downsample()`) currently uses the ported `downsample` method sitting in `aspire.image.preprocess`. This relies on the same principle as the new 2D method but is not identical. 

This `downsample` method takes 1,2, or 3 dimensional inputs, and can downsample to custom sizes. It is much more general than the `Image.downsample()` method we just replaced. We'll want to clean up this 3D downsampling method and see if we can break off a `crop_pad_3d` method for Volumes specifically.

**Comment by chris-langfield** [comment]
Once this is done, we can test using gaussian blobs and further eliminated hardcoded data. See #600

**Comment by janden** [comment]
I'd say let's move to have the 3D downsampling work as similarly to 2D downsampling as possible.

> This `downsample` method takes 1,2, or 3 dimensional inputs

We could eventually refactor to do this as well.

> can downsample to custom sizes

By this you mean non-square (non-cubic) sizes? That's less of a priority, but can be looked at later if needed.

> It is much more general than the `Image.downsample()` method we just replaced

Besides the two things above, does it do anything else that the current 2D downsampling does not do?

> We'll want to clean up this 3D downsampling method and see if we can break off a `crop_pad_3d` method for Volumes specifically.

I agree, although it might be better to start off adapting the current 2D downsampling method to the 3D case.

**Comment by chris-langfield** [comment]
> I'd say let's move to have the 3D downsampling work as similarly to 2D downsampling as possible.
> 
> We could eventually refactor to do this as well.
> 
> By this you mean non-square (non-cubic) sizes? That's less of a priority, but can be looked at later if needed.

Yes, exactly

> 
> Besides the two things above, does it do anything else that the current 2D downsampling does not do?

Based on one input, it handles 1, 2 and 3 dimensional cases, along with *stacks* of 1d, 2d, or 3d. So there are quite a few logic branches. 
> 
> I agree, although it might be better to start off adapting the current 2D downsampling method to the 3D case.

Yes definitely. The new 2d downsampling method in #606 essentially does what `aspire.image.preprocess.downsample()` does, but broken out into a special case, and with the adjustments we made. My thought was we could do more or less the same process with 3D, because it helped us understand all the ins and outs for the 2D case. Then potentially refactor into a single, generalized, improved method

**Comment by janden** [comment]
> Based on one input, it handles 1, 2 and 3 dimensional cases, along with _stacks_ of 1d, 2d, or 3d.

Supporting stacks is crucial in any dimension.

> So there are quite a few logic branches.

This can be compacted similarly to how the `grid_` functions work.

> My thought was we could do more or less the same process with 3D, because it helped us understand all the ins and outs for the 2D case. Then potentially refactor into a single, generalized, improved method

I agree.

**Comment by garrettwrong** [comment]
@chris-langfield , is this issue (excluding #710) settled by the above PRs? Thanks
