### ISSUE TITLE
`CoordinateSource` and `extract-particles` should insert particle coordinates into metadata

### ISSUE THREAD

**Issue by chris-langfield** [ComputationalCryoEM/ASPIRE-Python#628]
Typical Relion-preprocessed datasets preserve the `_rlnCoordinateX` and `_rlnCoordinateY` fields in metadata. These come from Relion's own particle picking. In addition to the option to add CTF metadata (see #622), particle centers should be added to STAR file metadata of `CoordinateSource` objects when they are saved. This includes when they are converted from micrograph datasets into particle stacks with the `extract-particle` command.

**Comment by janden** [comment]
That's a good idea.

**Comment by chris-langfield** [comment]
Looking back at this, I'm not sure if I now think it's a good idea. Imagine that we had a data source that was from EMAN or some other program, loaded with a `CoordinateSource`. Then, we'd have coordinates that came from EMAN inserted into ASPIRE metadata files, but labeled as RELION parameters? @garrettwrong Curious what you think

**Comment by garrettwrong** [comment]
I think in general we accepted speaking RELION when we decided to use starfiles.  I understand that starfiles are generic, but in this domain it seems like RELION dominates the data formats.

If the data is reasonably correct, like the coordinates match the input, what would be the worry?

**Comment by chris-langfield** [comment]
> in this domain it seems like RELION dominates the data formats.

This is a good point. Okay, yeah I'll do this. Thanks
