### ISSUE TITLE
Abinitio Pipeline - Experimental Data - Not working

### ISSUE THREAD

**Issue by vinith2** [ComputationalCryoEM/ASPIRE-Python#630]
After downloading the recomended data. The starfile cannot be parsed by the function. That is when the line 
src = RelionSource(starfile_in, pixel_size=pixel_size, max_rows=n_imgs) is run the error obtained is Wrong number of values in the loop.

**Comment by garrettwrong** [comment]
Hi, I think that the version of `10028` currently on EMPIAR has a typo in the star file.  Try the following:

```
the .star file for picked particles has a random "9" floating around at line 5476. delete and then the file reads fine
```

The typo is unfortunate, but par for the course with cryo em data afaict.

Please report back if that resolves this problem for you.  If so we will convert this into an issue about adding a note to the experiment.

**Comment by vinith2** [comment]
Hi, yes removing "9" solves the issue. Thank you for solving it.
