### ISSUE TITLE
Batched Array Image Source

### ISSUE THREAD

**Issue by garrettwrong** [ComputationalCryoEM/ASPIRE-Python#638]
Discuss relevance and estimated effort.

Alternatively, we can consider how to shoehorn array data into Relion source.

**Comment by janden** [comment]
Can you expand a bit? Would this take some sort of generator as an input?

**Comment by garrettwrong** [comment]
No, simply chunk through a user provided array... Probably using the same mechanism from Relion source.

Immediately this would provide a workaround for the FINUFFT bug, but longer term it might be useful for debugging from time to time.

**Comment by garrettwrong** [comment]
I think we decided to close this after discussing in our meeting.
