### ISSUE TITLE
Is there an error while performing the rotation on the mesh?

### ISSUE THREAD

**Issue by ghost** [ComputationalCryoEM/ASPIRE-Python#639]
When I performed the code in the def rotated_grids() (line: pts_rot[:, i, :] = rot_matrices[i, :, :] @ pts), I found the "pts" numpy was (for for example):
array([[-3.1415927, -3.1415927, -3.1415927, ...,  3.0925055,  3.0925055,
         3.0925055],
       [-3.1415927, -3.0925055, -3.043418 , ...,  2.9943306,  3.043418 ,
         3.0925055],
       [ 0.       ,  0.       ,  0.       , ...,  0.       ,  0.       ,
         0.       ]], dtype=float32).

But the right coordinates I think should be:
array([[-3.1415927, -3.0925055, -3.043418 , ...,  2.9943306,  3.043418 ,
         3.0925055],
       [-3.1415927, -3.1415927, -3.1415927, ...,  3.0925055,  3.0925055,
         3.0925055],
       [ 0.       ,  0.       ,  0.       , ...,  0.       ,  0.       ,
         0.       ]], dtype=float32).

**Comment by garrettwrong** [comment]
I think this might be a matter of conventions.  Are you encountering a problem?

**Comment by ghost** [comment]
I tried to project a 3D volume (mrc file) with eular (0,0,0) with ASPIRE. However this projection is completely different with the prection from Relion (also using the same phi,theta,psi).
Then I also tried to change the code (grid2d = grid_2d(L, indexing="xy", dtype=rot_matrices.dtype)) into (grid2d = grid_2d(L, indexing="yx", dtype=rot_matrices.dtype)). This time the resulting projection appeared to have the same projection direction as the relion projection (since the volume I used is asymmetric), although the correlation coefficient between the two projections was still not high.

**Comment by garrettwrong** [comment]
Yes, this sounds familiar.  I put code in place to migrate the conventions (the `indexing` flag) but I'm not sure we were able to convert all of them at the time.  It is a little out of my memory, but I will mention it in our next developer meeting.  Thank you for reporting.

**Comment by garrettwrong** [comment]
Closing in favor of the report in 1026
