### ISSUE TITLE
User Logging Config

### ISSUE THREAD

**Issue by garrettwrong** [ComputationalCryoEM/ASPIRE-Python#642]
User requested we expose and/or document configuring logging.

It has been a while since we reviewed our logging system, but I was probably the last one to touch it...

As I recall, currently we are just using the standard Python logging module, configured using `logging.conf` in our repo root.  The log stream is split and filtered separately for the console (INFO) and disk (DEBUG). 

It is easy to modify that as a dev, but for users here are a few ideas:

- Tutorial showing how to change level in a script or notebook
- Flags in our command line utils to set it.
- Replace some noisy logic (batching for example) with tqdm style progress bars to convey the same information.
- Perhaps revisit the logging config as it relates to #504 
- Could ask the RSE group what they're doing re best practice for user configurable Python logging.

Some of these are things we can do now, while others might be medium sized efforts.

**Comment by garrettwrong** [comment]
Chris, since I took the general configuration update, I'd like you to handle the logging updates sometime after #749 goes in.

Some of the tasks have already been completed (or in flight now).

There is some question about where the basic user interactions should be (our config or logging.conf), which we can discuss together; but I think the answer is probably that we control some basic logging in our config while still allowing advanced users to do the standard python logging library things...

**Comment by chris-langfield** [comment]
After looking at this a bit, I think a good place to start would be being able to specify 4 things in the `confuse` config file:

- *Logging directory* (this is already implemented)
- *Log filename* This can be done with a little more effort by modifying the `logging.conf` Python logging config file. I think this should default to the one we already use `aspire-{timestamp}` but be configurable in ASPIRE config.
- *Console logging level* via string (e.g. `'INFO', 'WARNING'`). We can pass this through the Python logging config file via interpolation
- *Log file logging level* via string. We can also pass this through via Python logging, by setting the consoleHandler and fileHandler levels differently.

Putting together a PR

**Comment by chris-langfield** [comment]
My proposals for defaults 

`log_dir: logs`
`log_filename:` (Not in `config.yaml`, but can be added)
`console_level: INFO`
`log_file_level: DEBUG`
