### ISSUE TITLE
`anorm` does not handle complex values properly

### ISSUE THREAD

**Issue by j-c-c** [ComputationalCryoEM/ASPIRE-Python#646]
When specifying an axis, `anorm(x, axes=[1])` computes the norm along the axis with inner product `ainner(x, x, axes=[1])`, which does not use the complex conjugate (see below).

This may be as simple as replacing `y` with `np.conj(y)` in the `return` expression.

https://github.com/ComputationalCryoEM/ASPIRE-Python/blob/1bff8d3884183203bd77695a76bccb1efc909fd3/src/aspire/utils/matrix.py#L354-L367

**Comment by garrettwrong** [comment]
Good catch, just curious, where are we using complex values.?  I thought all the areas except some portion of class averaging (bispectrum) were constrained to reals in the Python code....

**Comment by garrettwrong** [comment]
Doh, I see the linked code. Please disregard. Thanks!

**Comment by garrettwrong** [comment]
Merged.
