### ISSUE TITLE
Change Polar Fourier to Row Major

### ISSUE THREAD

**Issue by j-c-c** [ComputationalCryoEM/ASPIRE-Python#662]
In `src/aspire/abinitio/commonline_base.py` the polar Fourier `self.pf` is transposed into column major order here:
https://github.com/ComputationalCryoEM/ASPIRE-Python/blob/1bff8d3884183203bd77695a76bccb1efc909fd3/src/aspire/abinitio/commonline_base.py#L69-L70

then later converted back to row major order when performing a correlation:
https://github.com/ComputationalCryoEM/ASPIRE-Python/blob/1bff8d3884183203bd77695a76bccb1efc909fd3/src/aspire/abinitio/commonline_base.py#L161-L162

We should consider keeping this in row major form.

**Comment by garrettwrong** [comment]
Now that the CL code has entered develop it would be a better time to knock this out if it was not already covered.

If you covered it, can close. Thanks

**Comment by j-c-c** [comment]
Closed by #841
