### ISSUE TITLE
MSE accuracy different for C3 and C4 symmetry

### ISSUE THREAD

**Issue by j-c-c** [ComputationalCryoEM/ASPIRE-Python#663]
The common lines algorithm for molecules with C3 and C4 symmetry is performing better for C3 symmetry. See `tests/test_orient_symmetric.py`. We should investigate the cause of this and resolve if possible.

**Comment by garrettwrong** [comment]
Just curious, by performing, do you mean compute speed or quality?

**Comment by j-c-c** [comment]
> Just curious, by performing, do you mean compute speed or quality?

I mean quality. The MSE is much lower for C3. See this discussion https://github.com/ComputationalCryoEM/ASPIRE-Python/pull/594#discussion_r909780788

**Comment by j-c-c** [comment]
I spent a little time investigating this and I think this issue can be closed. 

Initially the test referenced here was using MSE as a metric and what looked like an order of magnitude difference in MSE between C3 and C4 turned out to be about 1 degree when converting to mean angular distance (which is the metric currently used in the test).

Furthermore, after running the test using various seeds for the simulation it turned out that sometimes C3 outperformed C4 and sometimes not.
