### ISSUE TITLE
Use ASPIRE `about_axis()` in Gallery

### ISSUE THREAD

**Issue by j-c-c** [ComputationalCryoEM/ASPIRE-Python#664]
Replace the function below with ASPIRE's `about_axis()`:
https://github.com/ComputationalCryoEM/ASPIRE-Python/blob/1bff8d3884183203bd77695a76bccb1efc909fd3/gallery/tutorials/generating_volume_projections.py#L52-L59

**Comment by j-c-c** [comment]
We can also use `Volume.load()` earlier in the script.

**Comment by garrettwrong** [comment]
I think this predates both of those. Nice catch, thanks.

**Comment by garrettwrong** [comment]
This might be a good small issue while we are sprucing up the docs. I don't think it depends/conflicts on anything upstream.

**Comment by j-c-c** [comment]
Closing. Issue was covered in #721
