### ISSUE TITLE
Test common lines method with shifted images

### ISSUE THREAD

**Issue by j-c-c** [ComputationalCryoEM/ASPIRE-Python#676]
We are currently using a `Simulation` with offsets set to zero for common lines testing in `tests/test_orient_symmetric.py`.

**Comment by garrettwrong** [comment]
If the tests aren't too long we should probably test both situations, perhaps via parameterization.

**Comment by janden** [comment]
Agreed.

**Comment by j-c-c** [comment]
Just so I remember when I tackle this issue, the trick for good performance of common lines methods for Simulations with non-zero offsets is to set `shift_step` to be sub-pixel (ie, < 1). This improves common line detection.

**Comment by garrettwrong** [comment]
Closed, completed.
