### ISSUE TITLE
pep8 line length

### ISSUE THREAD

**Issue by vineetbansal** [ComputationalCryoEM/ASPIRE-Python#69]
Let the whole code run through a linter to tackle line lengths:

1. Either go with the pep8 recommendation of 80 characters (too restrictive).
2. Go with a more liberal 120 characters (as proposed by default by Pycharm etc.

**Comment by janden** [comment]
From a purely personal perspective, I like to work with multiple tabs and my (current) monitor is relatively low-resolution. As a result, having an 80-character line width lets me get two-three splits at a comfortable resolution when editing code. It's also the default size for many terminals, so when doing work there, it's nice not to have to worry about line wrapping (especially working at a Python shell and querying the docs).

**Comment by garrettwrong** [comment]
In #313 I have implemented the Black rule which is roughly:

Try to achieve 80 char lines, but allow overage up to 88 chars.

**Comment by garrettwrong** [comment]
Closed by #313 and documented in the developer doc.
