### ISSUE TITLE
`rots` vs `rotations`

### ISSUE THREAD

**Issue by garrettwrong** [ComputationalCryoEM/ASPIRE-Python#694]
Some areas of the code use `rots` and others use `rotations`. During a presentation there was a line that looked like

`foo.rots = bar.rotations`

I feel like the attribute names should be consistent.  I am leaning towards `rotations` for user facing code (attributes of classes).  Using `rots` for a local var is fine.

Quick grep, looks like mainly `image` code, unit tests and (gallery) docs.

**Comment by janden** [comment]
> I am leaning towards `rotations` for user facing code (attributes of classes). Using `rots` for a local var is fine.

Works for me.
