### ISSUE TITLE
“x” → “×”.

### ISSUE THREAD

**Issue by vineetbansal** [ComputationalCryoEM/ASPIRE-Python#70]
`x` is used in a lot of places in documentation to indicate multipication. One suggestion is to replace “x” with “×”.

_Originally posted by @janden in https://github.com/_render_node/MDE3OlB1bGxSZXF1ZXN0UmV2aWV3MzIxODA1OTk2/pull_request_reviews/more_threads_

**Comment by janden** [comment]
I think this would be good, but maybe not a high priority. One potential approach is to make these replacements as we go through code (for other reasons). The same goes for applying the proper docstring format (NumPy style, I think) and other formatting decisions (PEP8?).

**Comment by janden** [comment]
Comment by @vineetbansal in above-mentioned PR:

> I'm a little wary of introducing non-ascii characters in code.

That's a good point. On the other hand, we're only talking about comments here (which, it's true, are parsed to generate documentation, so encoding could be an issue). UTF-8 support is pretty close to universal at this point as well, so it'd be nice to take advantage of it. From what I see, there are four(ish) options:

- “n-by-n” (favored by the MATLAB code, in places),
- “(n, n)” (we don't have this anywhere, but it's pretty straightforward),
- “nxn” (what we currently have in many places), and
- “n×n”.

Out of these, I find the last one the easiest to read (and the closest to the actual mathematical notation).

**Comment by janden** [comment]
No longer relevant per #158.
