### ISSUE TITLE
Gaussian helper function cleanup/completeness

### ISSUE THREAD

**Issue by garrettwrong** [ComputationalCryoEM/ASPIRE-Python#700]
In #616 `gaussian_3d` was extended to admit an `indexing` arg.  We may in the future want this for 2d case as well. or just for completeness.

Another improvement we can do there is to admit any iterable of length 3 instead of forcing a `tuple`.  Mainly to support taking in an array.  That would make it easier to use in a loop, ie call in loop over some (k,3) array etc.  Similarly len 2 for 2d.

I think it is a matter of checking if something is an iterable instead of tuple and checking len otherwise assuming scalar.

**Comment by j-c-c** [comment]
Resolved by #761. Closing
