### ISSUE TITLE
`evaluate_t()` passed NumPy array

### ISSUE THREAD

**Issue by j-c-c** [ComputationalCryoEM/ASPIRE-Python#701]
There are several instances of `evaluate_t()` being passed a NumPy array (which raises a warning). In particular:

https://github.com/ComputationalCryoEM/ASPIRE-Python/blob/d94bb4abf042bb3cf5b001b9108bb71ffb2b616a/src/aspire/reconstruction/estimator.py#L92

https://github.com/ComputationalCryoEM/ASPIRE-Python/blob/d94bb4abf042bb3cf5b001b9108bb71ffb2b616a/src/aspire/reconstruction/estimator.py#L149

https://github.com/ComputationalCryoEM/ASPIRE-Python/blob/d94bb4abf042bb3cf5b001b9108bb71ffb2b616a/src/aspire/denoising/denoiser_cov2d.py#L183

There may be other instances. This should be a quick PR enforcing the passing of `Volume`/`Image` into all instances of `evaluate_t()`.

**Comment by j-c-c** [comment]
I will circle back around to this shortly. It will be a quick fix.

**Comment by garrettwrong** [comment]
I think 709 forgot the one for the 3D estimator ... which was probably the one you see in the demo :)

**Comment by j-c-c** [comment]
> I think 709 forgot the one for the 3D estimator ... which was probably the one you see in the demo :)

Aah, good catch. We even had a discussion specific to that line. Must have forgot to save my `Volume` wrap. Will do a quick PR for that!
