### ISSUE TITLE
`ArrayImageSource` docstring formatting

### ISSUE THREAD

**Issue by j-c-c** [ComputationalCryoEM/ASPIRE-Python#702]
It appears that the docstring for `ArrayImageSource` is improperly formatted as the parameters are not displaying correctly in the docs (see pic). Just need to add a blank line in the `__init__`.
 
![Screen Shot 2022-09-26 at 9 17 59 AM](https://user-images.githubusercontent.com/66811911/192287537-4d29bfef-8b47-46f6-9937-712456af8ff8.png)

**Comment by garrettwrong** [comment]
Merged. Closing.
