### ISSUE TITLE
Centerpoint test discrepancies for 3D downsampling

### ISSUE THREAD

**Issue by chris-langfield** [ComputationalCryoEM/ASPIRE-Python#710]
One of the test conditions in `tests/test_downsample.py` is that the intensity at the center point of the volume should be conserved.

According to our centering conventions this is the point `v[L // 2, L // 2, L // 2]`

We are not achieving this to within the dtype tolerance for our 3D downsampling code. This is a problem inherent to the original method, which is identical to the one introduced in #689 (this PR added the tests that exposed this problem)

Current progress on investigating: https://github.com/ComputationalCryoEM/ASPIRE-Python/pull/689#issuecomment-1242230509

Update on tolerance level for each 3D downsample case:

Changing the anisotropy or the max/min sigmas shuffles things a bit but in general we're seeing that even to even is by far more accurate than the other 3 cases. 

With current sigmas

```
Even to Even (64,32): 5e-5
Even to Odd (64,33): 1e-2
Odd to Even (65,32): 5e-2
Odd to Odd (65,33): 5e-2

```
Anisotropy Removed:
```
Even to Even (64,32): 5e-5
Even to Odd (64,33): 5e-2
Odd to Even (65,32): 1e-2
Odd to Odd (65,33): 1e-2

```

Large sigmas removed (0.3)
```
Even to Even (64,32): 5e-5
Even to Odd (64,33): 5e-2
Odd to Even (65,32): 1e-2
Odd to Odd (65,33): 1e-2

```
Small sigmas removed (0.1)
```
Even to Even (64,32): 5e-5
Even to Odd (64,33): 1e-2
Odd to Even (65,32): 1e-2
Odd to Odd (65,33): 1e-2

```

**Comment by garrettwrong** [comment]
Can close this per #1162
