### ISSUE TITLE
Data Downloader

### ISSUE THREAD

**Issue by garrettwrong** [ComputationalCryoEM/ASPIRE-Python#712]
Current and future examples require some example data off the web (eg, EMD 2660).

Add a feature that downloads such data to a user configurable cache location (something like `~/.aspire/cache` by default) and integrate it into the examples.

We can decide based on code complexity whether this should be a bulk download (download all supporting data once) or lazy (on first need).

Also we can discuss whether this should download from a GitHub LFS repo in CoputationCryoEM or directly from websites.  There pros and cons to this...

I'm not sure if this should come before or after the configuration revamp yet. Just jotting things down.

**Comment by garrettwrong** [comment]
Looks like we might be able to use https://help.zenodo.org/ for larger datasets.  

They appear to allow a dataset to be 50GB and permit multiple datasets.  Obviously we don't want to abuse it, but this is probably must simpler for a dataset that is beyond the few gigs afforded by GitHub.

**Comment by janden** [comment]
I think so. Especially if we expect this to be relatively static.

**Comment by garrettwrong** [comment]
Documenting notes from today's design meeting.  These are some of the tasks, not in a particular order.  

- [ ]  Construct an `Asset` base class with common attributes and methods.  Derived classes will extend with specifics. Initially I think all our assets will be url downloadable so we likely will just have a single concrete implementation `URLAsset` or something to that effect.  Assets should be able to provide a path (`pathlib`) or a File like object (by hooking open/close/contexts).  Also provides a self check, using file checksum.  We can decide if this checksum should be in code or dynamic (ie the downloads file list is an asset...)
- [ ]  Configurable cache location.  Because caching is a general thing we might want space for, we should home the downloads in their own `downloads` sub area.  Example default `$ASPIREDIR/cache/downloads`.  Users should be able to get and set this naturally with `confuse`.
- [ ] Moving foward with Zenodo, couple questions to answer:
  - [ ] Do they provide a preferred API or just use static URL 
  - [ ] Have they added a group/organization user-interface.  Previously it was per user, but there was discussion about adding this feature at the time (1-2 years ago)
  - [ ] Start by uploading our favorite 2660 map file.
- [ ] Useful methods for interacting with a cache of downloads.  This would either be methods of `Asset` or standalone functions in the module with awareness of assets.
  - [ ]  show downloads , shows currently downloaded assets and their size/location
  - [ ] get/set downloads dir
  - [ ] download_all, downloads the currently cache entry list, checks files already downloaded, updates as needed.
  - [ ] list downloads, show all available assets and their metadata (size, source etc)
  - [ ] check downloads, loops over downloaded assets and runs self check
  - [ ] clear downloads, purge the downloads directory.
- [ ] Decide on user implementation/interface of asset.  We discussed a dictionary `{'emdb2660': URLAsset(...)}` combined with bunches of helper util functions  _or_ a more polished approach where we just use and import asset objects directly `from aspire.downloads import emdb2660` and the `emdb2660` object could be used as a path or file directly, hiding the mechanics and code from the user.  I'm leaning towards the second case. Our internal code could simply be like `with aspire.downloads.emdb2660 as f:` and `some_external_tool(emdb2660.path)`, or something to this effect.
  
The next step should probably be to answer all of the Zenodo questions and then upload the first file so there is something to build code against.  Otherwise I think the roadmap I've put together here is ready to be discussed at our team meeting.

**Comment by j-c-c** [comment]
Some follow up regarding Zenodo.

We may want to create an ASPIRE Zenodo Community that houses all ASPIRE related records/files in one location. This is the closest thing there is to an organizational account. Which ever user creates the community (by filing out [this form](https://zenodo.org/communities/new/)) is designated as the community curator. This means they will be the gatekeeper of what records/files will be associated with the community.

In terms of downloading, it appears we can use `requests` and provide a DOI as follows:
```
import requests
r = requests.get('https://doi.org/' + DOI)
```
 There is a [python package for downloading from Zenodo](https://github.com/dvolgyes/zenodo_get/tree/master/zenodo_get) but it appears to be handling many of the tasks we would like our more general `data_downloader` to handle.

**Comment by garrettwrong** [comment]
Great, thanks! Good to know about the CLI downloader, but I agree we probably just want to steal the URL formula for now.

I'll fill out that form so we can move this along.

**Comment by garrettwrong** [comment]
Live: https://zenodo.org/communities/computationalcryoem/

**Comment by j-c-c** [comment]
> Live: https://zenodo.org/communities/computationalcryoem/

Awesome. Thanks for setting that up! I'll get started on the next steps on Monday ;)

**Comment by j-c-c** [comment]
Going to close now the data downloader (#959) has been merged.
