### ISSUE TITLE
Implement dual function for a Filter object

### ISSUE THREAD

**Issue by vineetbansal** [ComputationalCryoEM/ASPIRE-Python#72]
Filtering is only symmetric if the transfer function itself is symmetric. This is the case for many of them (such as the CTF), but is not generally the case. For now, we can pretend the adjoint doesn't exist (like in `Downsample`, above), but at some point, we should have something like `Filter.dual()` that will return the dual filter (the same filter, but with a transfer function flipped around the origin, that is g(ω) = f(–ω), where f(ω) is the transfer function of the original filter).

_Originally posted by @janden in https://github.com/_render_node/MDE3OlB1bGxSZXF1ZXN0UmV2aWV3MzIxODA1OTk2/pull_request_reviews/more_threads_

**Comment by janden** [comment]
This should be fairly straightforward. Ideally, we'd have a method `Filter.dual()` that would yield this dual filter. That could be implemented by a simple wrapper class `DualFilter` that simply flips the sign of the inputs to `evaluate()`.

**Comment by junchaoxia** [comment]
The issue was resolved in PR #255. Closing now.
