### ISSUE TITLE
Build Docs without Gallery

### ISSUE THREAD

**Issue by j-c-c** [ComputationalCryoEM/ASPIRE-Python#720]
Since the gallery takes a while to build it would be good to be able to build the docs without generating the galleries. It looks like adding the following to the Makefile will do it 

```
html-noplot:
        $(SPHINXBUILD) -D plot_gallery=False -b html $(ALLSPHINXOPTS) $(SOURCEDIR) $(BUILDDIR)/html
        @echo
        @echo "Build finished. The HTML pages are in $(BUILDDIR)/html."
```

You could then run

```
sphinx-apidoc -f -o ./source ../src -H Modules
make html-noplot
```

from the `docs` directory to build the modules and html

**Comment by garrettwrong** [comment]
Merged. Closing.
