### ISSUE TITLE
`Volume.project` should not require a `vol_idx` parameter

### ISSUE THREAD

**Issue by janden** [ComputationalCryoEM/ASPIRE-Python#727]
99% of the time, we have a singleton volume that we want to project along a certain set of viewing directions, so we shouldn't have to specify `vol_idx=0`. The obvious issue that arises is what to do with volume stacks. The natural way to handle volume stacks and multiple rotations would be to do some sort of broadcasting, but this requires image arrays with multidimensional indices (which we don't have). So for the moment, I suggest we throw an error if multiple rotations are supplied when projecting a volume stack and to just allow the combination of one volume, multiple rotations or multiple volumes, one rotation.

**Comment by garrettwrong** [comment]
Now that we have multi dimensional `Volume` and `Image` this can be addressed by something like the proposed broadcasting semantics and raising when the broadcast does not make sense.

Because of potential conflicts this should come after #863 .
