### ISSUE TITLE
`__getitem__` for `Image` and `Volume` should return same class instead of NumPy

### ISSUE THREAD

**Issue by chris-langfield** [ComputationalCryoEM/ASPIRE-Python#739]
The `__mul__`, `__add__` and `__sub__` operators for `Image` and `Volume` return more `Image` and `Volume` instances.

Calling e.g. `im[0:1]` or `vol[0:1]` returns numpy arrays in the shape of the requested data. 

This API should return `Image` or `Volume` instances as well. However, this change would touch a lot of code so we would need to time when to make the change carefully.

**Comment by garrettwrong** [comment]
@chris-langfield , if you haven't started this I think we should do it first thing `v0.10.2`... lmk so I can get it on the right board, thanks.

**Comment by garrettwrong** [comment]
Volume methods (except the getter) were already returning Volumes.

Images were not.  

About half the failures were resolved by using numpy interop dunder methods, and the other half required manually `asnumpy()`ing a bunch of stuff.

**Comment by garrettwrong** [comment]
Closed by #863
