### ISSUE TITLE
Replace the grid generating method in PSWF basis 

### ISSUE THREAD

**Issue by junchaoxia** [ComputationalCryoEM/ASPIRE-Python#74]
Current the PSWF basis uses a different method for generating 2d grid. Ideally it should be used the same one `grid_2d` as that of FB methods. But the internal representation of data has be mixed up by two statements in line 61 and 62, `x = y_2d_grid[points_in_disk]; y = x_2d_grid[points_in_disk]`. This exchange of x and y has consequence in implementing other functions in the PSWF class. Simply switching back and replacing with grid_2d do not work. Need to do more carefully work when optimizing the PSWF methods.

**Comment by garrettwrong** [comment]
Should be reasonable to do this after #523

**Comment by garrettwrong** [comment]
Taking this issue.  My prior work allows this to just be swapped in now.

**Comment by garrettwrong** [comment]
Closed by #1032 and related to #1038
