### ISSUE TITLE
Create WhiteNoiseAdder

### ISSUE THREAD

**Issue by j-c-c** [ComputationalCryoEM/ASPIRE-Python#748]
As mentioned [here](https://github.com/ComputationalCryoEM/ASPIRE-Python/pull/713#discussion_r1021520028) in #713, the use of `ScalarFilter` for adding white noise in the context of a simulation is a bit confusing. One possible solution is to add a `WhiteNoiseAdder` as a subclass to `NoiseAdder`.

**Comment by garrettwrong** [comment]
`WhiteNoiseAdder` would probably subclass `NoiseAdder`, which is instantiated with a filter.

I wouldn't know what this issue is about from the name.

**Comment by j-c-c** [comment]
> `WhiteNoiseAdder` would probably subclass `NoiseAdder`, which is instantiated with a filter.
> 
> I wouldn't know what this issue is about from the name.

Edited the title and updated my comment. Thanks

**Comment by garrettwrong** [comment]
Closed by #768
