### ISSUE TITLE
Another GitHub Actions Deprecation warning

### ISSUE THREAD

**Issue by garrettwrong** [ComputationalCryoEM/ASPIRE-Python#752]
https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

**Comment by chris-langfield** [comment]
https://github.com/ComputationalCryoEM/ASPIRE-Python/actions/runs/3473984365

**Comment by chris-langfield** [comment]
It seems that the `set-output` deprecation warning was triggered once by `setup-python/v2`. 

Both `decaf` and Github hosted runners we're using are upgraded well ahead of the version this update says to upgrade them to

**Comment by chris-langfield** [comment]
This has actually been set off by `setup-python/v2` a few other times, most recently: https://github.com/ComputationalCryoEM/ASPIRE-Python/actions/runs/3490252738

**Comment by chris-langfield** [comment]
Has not happened since

**Comment by garrettwrong** [comment]
Bu that was not in the ancient past... it was.. yesterday...

Let's see if it happens next week and if not, we can close.

Thanks!

**Comment by garrettwrong** [comment]
Hey @chris-langfield , can you check if this is still happening, and if not close the issue? Thanks!

**Comment by chris-langfield** [comment]
This doesn't appear in the last 24 hours, however from the `setup-python` repo themselves, we should upgrade to `setup-python@v4` to address this

https://github.com/actions/setup-python/issues/526
