### ISSUE TITLE
Why isn't this handled by `ImageSource.whiten`?

### ISSUE THREAD

**Issue by vineetbansal** [ComputationalCryoEM/ASPIRE-Python#76]
The following code should move one level up in the class hierarchy:
``` 
self.generation_pipeline.add_xform(FilterXform(PowerFilter(whiten_filter, power=-0.5)))
```

This will imply that `Simulation` maintain it's own metadata (exclusively for generation purposes).

_Originally posted by @janden in https://github.com/ComputationalCryoEM/ASPIRE-Python/pull/68_

**Comment by chris-langfield** [comment]
Looking in the body of `whiten()` in `src/aspire/source/image.py` now, it appears this change was made:

https://github.com/ComputationalCryoEM/ASPIRE-Python/blob/3223d6c2c308af66f321ca2b0ddf3933045f904b/src/aspire/source/image.py#L427-L428
