### ISSUE TITLE
`@parameterized_class` parameterization must include base case

### ISSUE THREAD

**Issue by j-c-c** [ComputationalCryoEM/ASPIRE-Python#774]
When using the `@parameterized_class` decorator for testing, as in the (F)FBbasis tests (example below), the base case must be initialized in the class _**and**_   included in the parameterization. Otherwise, the base case will not be tested. This needs to be changed in the basis tests.
https://github.com/ComputationalCryoEM/ASPIRE-Python/blob/d08a9f7085efb352126784782f69d1146048f018/tests/test_FBbasis2D.py#L20-L33

For reference, [here](https://github.com/wolever/parameterized/issues/73) is discussion on why this occurs and the relevant section of [code](https://github.com/wolever/parameterized/blob/master/parameterized/parameterized.py#L608) causing this behavior

**Comment by garrettwrong** [comment]
Merged.
