### ISSUE TITLE
Respect index shape in Basis functions

### ISSUE THREAD

**Issue by janden** [ComputationalCryoEM/ASPIRE-Python#78]
Right now, the Basis functions (such as `FFBBasis2D.evaluate_t()`) adds an extra dimension if one is missing in the input. As a result, if we have a 256×256 image `im` and run
```
basis = FFBBasis2D(shape=(256, 256))
c = basis.evaluate_t(im)
```
we get `c.shape == (40224, 1)` instead of `(40224,)`. For this reason, when we continue with
```
imp = basis.evaluate(c)
```
we get that `imp.shape == (256, 256, 1)` and consequently `np.linalg.norm(im - imp)` is a very large number (presumably due to NP broadcasting rules). It would be good to fix this so that the shape of the output coefficients (or images) matches that of the input.

**Comment by junchaoxia** [comment]
The issue have be addressed in commit # 44d685d.
