### ISSUE TITLE
Cleanup Warnings

### ISSUE THREAD

**Issue by garrettwrong** [ComputationalCryoEM/ASPIRE-Python#798]
Seeing some warnings. I think two are relatively recent and one is from some of my code.

- [x] Complex cast
- [x]  div zero
- [x] gimbal

```
=================================================== warnings summary ====================================================
tests/test_FPSWFbasis2D.py::FPSWFBasis2DTestCase::testExpand
tests/test_PSWFbasis2D.py::PSWFBasis2DTestCase::testExpand
tests/test_PolarBasis2D.py::PolarBasis2DTestCase::testExpand
  /Users/gbwright/work/ASPIRE-Python.snr/src/aspire/basis/basis.py:201: ComplexWarning: Casting complex values to real discards the imaginary part
    v[isample], info = cg(operator, b, tol=tol, atol=0)

tests/test_utils.py::UtilsTestCase::testBump3d_1
  /Users/gbwright/work/ASPIRE-Python.snr/src/aspire/utils/misc.py:220: RuntimeWarning: divide by zero encountered in true_divide
    bump[selection] = np.exp(-1 / (spread - spread * p[selection]))

tests/test_averager2d.py: 28 warnings
  /Users/gbwright/work/ASPIRE-Python.snr/src/aspire/utils/rotation.py:68: UserWarning: Gimbal lock detected. Setting third angle to zero since it is not possible to uniquely determine all angles.
    return rotations.as_euler(self._seq_order, degrees=False).astype(self.dtype)

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
```

**Comment by j-c-c** [comment]
I'll look into the `div zero` warning since that's in the bump function test I wrote.

**Comment by garrettwrong** [comment]
Cool, there is an additional warnings about `res` ~> `resolution`, but I will fix that in a PR that is already touching image stuff.

**Comment by chris-langfield** [comment]
Looking into the complex cast

**Comment by j-c-c** [comment]
The gimbal lock warning is occurring because we are calling `.angles` on a Rotation object that represents rotations about the z-axis. This is in the context of providing a set of Euler angles to a Simulation source. The warning can be bypassed by just providing the set of angles directly instead of first creating the Rotation object and then calling `angles`.

**Comment by chris-langfield** [comment]
The complex cast warning opened a moderately sized can of worms, see #805. Basically, we were treating the bases' image dtype as the same as the coefficient dtype in some places. We can't do this, in particular with `PSWF`

**Comment by j-c-c** [comment]
"Gimbal Lock" and "div zero" warnings have been cleaned up by #807 
 and #804, respectively. Should be able to close once #805 is in.

**Comment by chris-langfield** [comment]
#805 in
