### ISSUE TITLE
RotCov2D.get_mean returns 2D array

### ISSUE THREAD

**Issue by janden** [ComputationalCryoEM/ASPIRE-Python#81]
The mean is a one-dimensional vector, so we should not use a 2D array for this. Currently, the second dimension is just a singleton dimension, so it can be removed.

**Comment by junchaoxia** [comment]
I check it again. The reason I put it in this way is that it doesn't need to do many reshaping operations when calculating the covariance using block diagonal functions. Probably I will keep it now but will make changes if necessary.

**Comment by janden** [comment]
Normally, the broadcast rules in NP should help you avoid reshaping operations. Even if that's not the case, I would argue that it's quite counterintuitive to have a 1D vector represented as a 2D array with a singleton dimension. This is especially true since it's not done elsewhere in the code.

**Comment by janden** [comment]
We need to get this sorted out. Just ran into another bug caused by this.
