### ISSUE TITLE
RotCov2D.get_covar doesn't account for noise if no CTF is present

### ISSUE THREAD

**Issue by janden** [ComputationalCryoEM/ASPIRE-Python#83]
Currently, changing `noise_var` has no effect if CTFs are not supplied. If no CTF is present, the covariance estimate still has to be corrected (either via shrinkage or plain subtraction of the estimated noise covariance), as done in https://github.com/ComputationalCryoEM/ASPIRE-Python/blob/9e4a4fe1765368be32f15602b3131efbbb380430/src/aspire/estimation/covar2d.py#L195.

**Comment by junchaoxia** [comment]
When no CTF presents, the internal function ` _get_covar`  is used as same as the Matlab code. Please check whether it is you want.

**Comment by junchaoxia** [comment]
See the two lines: 
https://github.com/ComputationalCryoEM/ASPIRE-Python/blob/9e4a4fe1765368be32f15602b3131efbbb380430/src/aspire/estimation/covar2d.py#L151
https://github.com/ComputationalCryoEM/ASPIRE-Python/blob/9e4a4fe1765368be32f15602b3131efbbb380430/src/aspire/estimation/covar2d.py#L152

**Comment by janden** [comment]
The MATLAB code doesn't handle the case of noisy, but unfiltered images. What we want to do here is to handle the no-CTF case by running the same code with filter matrices that are equal to the identity. This is *not* the same as calling `_get_covar` since it also involves subtracting the noise component. Again, see: https://github.com/ComputationalCryoEM/ASPIRE-Python/blob/9e4a4fe1765368be32f15602b3131efbbb380430/src/aspire/estimation/covar2d.py#L195

Essentially, we are looking to skip this line https://github.com/ComputationalCryoEM/ASPIRE-Python/blob/9e4a4fe1765368be32f15602b3131efbbb380430/src/aspire/estimation/covar2d.py#L184 either by literally skipping it, or replacing the relevant CTF FB matrices with identities.

**Comment by junchaoxia** [comment]
My understand  for implementation is that the following line in Matlab code 
https://github.com/PrincetonUniversity/aspire/blob/master/examples/example_003.m#L104
Calculate Cov2D without CTF information. This is corresponding to the python function `_get_covar`.
 
And the line in Matlab code 
https://github.com/PrincetonUniversity/aspire/blob/master/examples/example_003.m#L113
calculates the Cov2D with CTF information as the python function `get_covar` . 

Do you mean that in real case without CTF info, the noise also has to be removed from the coefficients?

**Comment by janden** [comment]
> My understand for implementation is that the following line in Matlab code
> https://github.com/PrincetonUniversity/aspire/blob/master/examples/example_003.m#L104
> Calculate Cov2D without CTF information. This is corresponding to the python function `_get_covar`.

That line calculates the 2D covariance without CTF information for *clean* images.

> And the line in Matlab code
> https://github.com/PrincetonUniversity/aspire/blob/master/examples/example_003.m#L113
> calculates the Cov2D with CTF information as the python function `get_covar` .

That line calculates the 2D covariance with CTF information for *noisy* images. In that script, there is no example of calculating 2D covariance without CTF information clean images, but if there were, it would assign an identity (block) matrix to `h_fb` and set `h_idx` to all ones.

> Do you mean that in real case without CTF info, the noise also has to be removed from the coefficients?

Yes. Just because there's no CTF information doesn't mean there's no noise.
