### ISSUE TITLE
`(F)PSWF` bases running in float32

### ISSUE THREAD

**Issue by chris-langfield** [ComputationalCryoEM/ASPIRE-Python#843]
As part of the effort to expand parameterized testing to the rest of the bases, the following issues were found with `evaluate_t` for the PSWF bases when in single precision:

#### `PSWFBasis2D.evaluate_t`

When passed float32 data, the function returns coefficients in `complex128`, instead of `complex64`

```python
import numpy as np
from aspire.basis import PSWFBasis2D
from aspire.image import Image

basis = PSWFBasis2D(8, dtype=np.float32)
image = Image(np.ones((8,8), dtype=np.float32))
coeffs = basis.evaluate_t(image)
coeffs.dtype
>>> np.complex128
```

#### `FPSWFBasis2D.evaluate_t` and `expand`

```python
basis = FPSWFBasis2D(8, dtype = np.float32)
basis.evaluate_t(image)
```
or
```python
basis.expand(image)
```

both result in the same ASPIRE `nufft` error:

```
RuntimeError: nufft passed inconsistent dtypes. fourier_pts: float64 does not match precision of signal data: float32.
```

**Comment by garrettwrong** [comment]
I am covering this in the Basis reconciliation effort.  The code generating points was simply not dtyped well.

**Comment by garrettwrong** [comment]
{F}PSWF can now run as both float and double. Closing.
