### ISSUE TITLE
FLE expand unit test failure

### ISSUE THREAD

**Issue by garrettwrong** [ComputationalCryoEM/ASPIRE-Python#862]
There is failure in one of the recent FLE unit tests for windows-latest with the default config.  (Expand failing to converge).

Sort of expected one or two of these.  Until fixed it will cause the CI to be red (for development branches), but so far only that one platform.

https://github.com/ComputationalCryoEM/ASPIRE-Python/actions/runs/4252873766/attempts/1

**Comment by garrettwrong** [comment]
Another 

https://github.com/ComputationalCryoEM/ASPIRE-Python/actions/runs/4254484833/jobs/7400820639

**Comment by garrettwrong** [comment]
Proposed workaround using Windows 2019.  This issue may have nothing to do with ASPIRE code.

In case we need to workaround by `xfail` in future, here is a snippet.
```
+@pytest.mark.xfail(
+    sys.platform == "win32",
+    reason="Bug on windows with latest envs, #862",
+    raises=RuntimeError,
+)
```

**Comment by garrettwrong** [comment]
Seems to still occur sporadically under windows 2019 for default (intel) env.  Will put xfail in place until we have time to trace this.

**Comment by garrettwrong** [comment]
This one occurred on ampere_gpu, which has not had any conda env changes.  If it continues we may need to xfail the test generally.

https://github.com/ComputationalCryoEM/ASPIRE-Python/actions/runs/4305641677/attempts/1

**Comment by garrettwrong** [comment]
Reporting another failure that looks related. Let's try to keep a pulse on this to see if we need to spend time debugging.

https://github.com/ComputationalCryoEM/ASPIRE-Python/actions/runs/5976871024/job/16216200713

**Comment by j-c-c** [comment]
Got another one.

https://github.com/ComputationalCryoEM/ASPIRE-Python/actions/runs/6003112294/job/16280875694?pr=996

**Comment by j-c-c** [comment]
Reporting another failure on this test.

https://github.com/ComputationalCryoEM/ASPIRE-Python/actions/runs/6110730357/job/16584465976?pr=1013

This seems to be happening fairly frequently.

**Comment by garrettwrong** [comment]
Yeah. The original report was focused on windows, but it seems to have spread to other platforms. Fun.

**Comment by garrettwrong** [comment]
https://github.com/ComputationalCryoEM/ASPIRE-Python/actions/runs/6174147211/job/16758123530

**Comment by j-c-c** [comment]
https://github.com/ComputationalCryoEM/ASPIRE-Python/actions/runs/6263290317/job/17007497109

**Comment by garrettwrong** [comment]
I haven't seen this since 1044. Closing. Can re-open if bug still occurs.
