### ISSUE TITLE
RelionSource dtype

### ISSUE THREAD

**Issue by garrettwrong** [ComputationalCryoEM/ASPIRE-Python#871]
I think we are missing a direct way to set or serve `RelionSource` images with a different dtype.  We can do it via workarounds.

For example, I might like to serve them up as float64 for developing or debugging a component using experimental data.

Logic could be added to the base Image class (and inherited), or an explicit method could be made that generates a new source of the desired type.

**Comment by janden** [comment]
I'm not following. Shouldn't `RelionSource` dtype be determined by the dtype of the underlying MRC file? What's the use case for upconversion?

**Comment by garrettwrong** [comment]
iirc, at the time I just wanted to run a pipeline with all the code and data in double precision, but the data set was in singles.  I think running in doubles is something we should support.

**Comment by garrettwrong** [comment]
Closing, was implemented.
