### ISSUE TITLE
Orientation and Boosting Sources

### ISSUE THREAD

**Issue by garrettwrong** [ComputationalCryoEM/ASPIRE-Python#875]
Recapping some design discussion.  There are two distinct components, a source for orientation estimate, and another source layer for symmetry boosting.

It is probably time to implement an `OrientedSource` which consumes a `Source` along with an `OrientationEstimator`.  It is probably safe to default to the CL sync.  This new source should serve up images with (assigning) estimated rotations.  Initially we perform an entire `estimate()` on first access. In the future this would be a good place to layer in any optimal orientation code. (I'm thinking the code(s) I've been told about that apply CL sync to the first (eg) 500 images, then use that initial batch for further orientations.)

Next, a `SymmetryBoostedSource` consumes a source (require `rotations`) and serves up images along with rotations extended by symmetry.  To avoid bias, we should shuffle these by default.    One way to do this is to construct the outer product of input image indices x rotations.  This can be held as a list of tuples (or the same data but as np arrays).  The entire product should be shuffled.  We should have a way to disable shuffling for debugging, perhaps by prescribing which way to repeat things.  When a consumer requests images or metadata this source will i) construct the unique set of indices to request from the input source ii) maintain a temporary map of these unique indices to the requested indices iii) return metadata associated with the original image but with the additional boosted rotation applied.  Whether we expand and store or serve up the boosted metadata is TBD (whichever is cleaner). iv) on image request the proceeding source will be asked only for the unique set of images, and these will be packed into a return object using the mapping from (ii), avoiding potential re-computation by the proceeding source.  

These two components together should help make this area of the pipeline consistent with the earlier stages.

**Comment by garrettwrong** [comment]
There is some question about the best way to store/prescribe the type and order of symmetry.  If OrientationEstimator or OrientedSource end up assigning it as metadata, we can hook onto that.  Otherwise it is probably better to be explicit. We can see what a rough draft of the components look like in practice before deciding this.

**Comment by garrettwrong** [comment]
I think we can subclass `RemappedSource` from #877 for this. So the boosted source would just manage generating the maps and serving the metadata with additional rotation applied.

**Comment by garrettwrong** [comment]
Some notes from developer meeting.

Seems like no complication moving forward with an `OrientationSource` or `OrientedSource`.

Some more consideration still needs to happen wrt the boosted component.  Both options below involve assigning some symmetry group attribute.  (At this point with `str`, `order`, `rotations` etc we probably ought to just make symmetries a class with desired structure/attrs....).

The approach I outlined initially is to create a `BoostedSource` component that would potentially live between `OrientedSource` and the next process (mean volume estimation).  It would just inherit from `IndexedSource` in the process outlined in my initial issue post.

Joakim suggested that we can gain efficiency by integrating the boosting rotations with backprojection for the mean volume estimation.  In the case of C4 (and probably C2) we can even reuse existing computations for 4x (2x) speedups. He also noted that we may one day prefer to use symmetry for cov3d in a smarter way than just supplying the additional images.  This could be a better way to go, but is less straightforward code (it involves digging into other components a little).  We will need to take care to inform users what is happening, and provide a clean way to disable this.

After thinking on it, I am warming up to Joakim's suggestion.  The BoostedSource was nice because it was only a few lines...

**Comment by garrettwrong** [comment]
Today we discussed creating a symmetry group base class to hold some of the useful attributes relating to symmetries since they will now be used in multiple places (Volume synth, OrientedSource, and Boosting). 

Sketched out having a symmetry type for the class, and using order to make concrete instances for types that require an order.  The concrete ordered instances should cache the rotations on first touch. Fixed ones like T, O can just be class attributes.  Class should provide __repr__  , __str__ , and rotation methods.

Before writing the code, Josh needs to determine what Relion does to denote symmetry (in the STAR files).  That will determine if we need a relion_str method, and what meta data field needs to be assigned by OrientedSource.  This may also guide how exactly to name the asymmetric class.

I proposed putting these symmetry classes in the operators module.

**Comment by j-c-c** [comment]
Relion has a metadata field `rlnSymmetryGroup` to denote symmetry:
 
```
"rlnSymmetryGroup", "Symmetry group (e.g., C1, D7, I2, I5, etc.)"
```

**Comment by garrettwrong** [comment]
Awesome, that should make things simple, can use str(instance).

**Comment by garrettwrong** [comment]
Moving to v0.11.1

**Comment by garrettwrong** [comment]
Looks like this issue is halfway done.  We have the `OrientedSource`, just need the boosting feature now.

**Comment by j-c-c** [comment]
Added boosting in #1072. Closing.
