### ISSUE TITLE
Vectorize `Rotation.angle_dist()`

### ISSUE THREAD

**Issue by j-c-c** [ComputationalCryoEM/ASPIRE-Python#886]
Currently, `Rotation.angle_dist()` only accepts two rotation matrices. This should be vectorized to accept two lists of rotation matrices.

**Comment by garrettwrong** [comment]
Maybe we can wrap with this.  Sometimes slower than manually managing the broadcasting, but maybe not by much here.  (There is also `vectorize`, but that _is_ slower ).

https://numpy.org/doc/stable/reference/generated/numpy.frompyfunc.html

**Comment by j-c-c** [comment]
Closing. This was completed as part of #994.
