### ISSUE TITLE
Smarter `overwrite` flag

### ISSUE THREAD

**Issue by garrettwrong** [ComputationalCryoEM/ASPIRE-Python#892]
Consider making `overwrite` have a smarter entry than False/True.  Perhaps in addition to boolean, we can offer a util that will append a suffix to the basename and log a usable info message.  The suffix could be first available consecutive integer or a date/epoch time.  This would avoid a raise halting the program at an inopportune time.  

This would probably be the most useful mode...

**Comment by janden** [comment]
Are we talking about `ImageSource.save` here? Makes sense. Just have to agree on a format.

**Comment by garrettwrong** [comment]
> Are we talking about `ImageSource.save` here? Makes sense. Just have to agree on a format.

Sorry missed this remark. Both `ImageSource` and `Image`.  I suspect with the `MicrographSource` coming online, that would be another.  Likely the file util code can just be shared.  Shouldn't be a big project, more tests than code.

**Comment by janden** [comment]
Sounds good.
