### ISSUE TITLE
density contrast of images

### ISSUE THREAD

**Issue by junchaoxia** [ComputationalCryoEM/ASPIRE-Python#91]
Currently the` ImageSource`  has no function to check the density contrast of image to make sure   that the molecule corresponds to brighter pixels and the background corresponds to darker pixels, the so called  globally phase flipping in the pre-proccess step.  This could result in denoised images with inconsistent representation.  We need add this automatic checking in the `ImageSource `.

**Comment by garrettwrong** [comment]
Hi Junchao, can you add some color to how #90 and #190 relate to this issue? I know we have talked about phase flipping a few times in our developer meetings.

Is this issue currently covered by your work in #190 or would this still be an additional feature? Thanks

**Comment by junchaoxia** [comment]
@garrettwrong Yes.  This issue is only a sub issue under the more general one under PR #190 . The invert of image density is only one of preprocess steps.

**Comment by junchaoxia** [comment]
This function has be implemented in PR #190. Closing now.
