### ISSUE TITLE
`FBBasis3D` NaN values for large resolution

### ISSUE THREAD

**Issue by j-c-c** [ComputationalCryoEM/ASPIRE-Python#923]
Encountered some NaN values while making a unit test for `FBBasis3D` with larger resolutions. Here is an example script to reproduce the behavior:

```
import numpy as np
from aspire.volume import AsymmetricVolume
from aspire.basis import FBBasis3D

L = 64
dtype = np.float32

vol = AsymmetricVolume(L=L, C=1, dtype=dtype).generate()
basis = FBBasis3D(L, dtype=dtype)

coeff = basis.evaluate_t(vol)

np.where(np.isnan(coeff[0]))
# Result:
array([68478, 68479, 68649, 68650, 68651, 68652, 68653, 68823, 68824,
       68825, 68826, 68827, 68828, 68829, 68999, 69000, 69001, 69002,
       69003, 69004, 69005, 69006, 69007, 69177, 69178, 69179, 69180,
       69181, 69182, 69183, 69184, 69185, 69186, 69187, 69357, 69358,
       69359, 69360, 69361, 69362, 69363, 69364, 69365, 69366, 69367,
       69368, 69369, 69539, 69540, 69541, 69542, 69543, 69544, 69545])
```

**Comment by j-c-c** [comment]
I've confirmed that we get the same behavior with `dtype=np.float64`.

**Comment by janden** [comment]
Hmm that's odd. Should be fairly straightforward to narrow down the source. Let me know if there are any updates.

**Comment by garrettwrong** [comment]
Started taking a look at this.

We catch an underflow casting result of `real_sph_harmonic` pretty early on in the basis construction here.  Not sure if related, will pick it up again another day.

**Comment by garrettwrong** [comment]
Definately getting some junk  in our `real_sph_harmonic`, which is a real light wrapper on the scipy `sph_harm`.  I can see that we do not yield junk for the adjacent indices; the example below is right on the edge.

Example (taken from an L = 61 case).

```
real_sph_harmonic(86, -85, 0, 0)
Out[55]: nan
real_sph_harmonic(86, -85, *basis.basis_coords["ang_unique"])
Out[56]: array([nan, nan, nan, ..., nan, nan, nan])
```

Some neighbors that just barely work...

```
real_sph_harmonic(86, -84, *basis.basis_coords["ang_unique"])
Out[57]: 
array([-0.00000000e+000, -3.82132282e-126,  0.00000000e+000, ...,
        3.84696087e-126, -2.77911412e-126, -0.00000000e+000])
real_sph_harmonic(85, -85, *basis.basis_coords["ang_unique"])
Out[58]: 
array([ 0.00000000e+000,  3.41617452e-126,  0.00000000e+000, ...,
       -3.43936874e-126, -7.75767303e-130,  0.00000000e+000])
```

**Comment by garrettwrong** [comment]
Looks like a related discussion:

https://github.com/scipy/scipy/issues/7778

**Comment by janden** [comment]
Interesting. May be worth shopping around for alternative implementations. Astro/geophys people probably have this covered somewhere.

**Comment by garrettwrong** [comment]
Currently looking at 

```
    y = pysh.expand.spharm_lm(j, abs_m, theta,phi,
                              kind = 'complex', degrees = False, csphase=-1, normalization='ortho')
```

Unfortunately, this appear to be much slower than scipy 🤷 . I should have a idea of how much by our meeting.

The pyshtools method offers a `real` kind, which may be able to replace some of our wrapping code.  Will look at that next.
