### ISSUE TITLE
Add `Volume.project` test with arbitrary rotation

### ISSUE THREAD

**Issue by garrettwrong** [ComputationalCryoEM/ASPIRE-Python#941]
#935 found that the error tolerance on the volume projection was a little higher than we thought compared to performing a direct rotation and sum.  This manifested by an attempt at such a test failing when running by `cufinufft`.  The existing tests for both project and rotation are about one axis at a time (though we do check each axis for multiple angles).

In our dev meeting we discussed adding a new test using an arbitrary rotation as a separate PR, and looking into any issues that come up in doing so.

I will note that the projection accuracy could be due to `cufinufft` accuracy itself, and it might be wise to dump the inputs to NUFFT call and check if they're agreeable.

**Comment by garrettwrong** [comment]
Seeing now that this might relate to #1030 .  Will discuss.

Given the confusion we've had with this topic I think this may be a rare case where having a hardcoded reference from generally accepted tool might be appropriate.

**Comment by garrettwrong** [comment]
Some triple checking is required, but it looks to me like we're returning the inverse rotation given to `Volume.rotation()`. 
 Reading code it appears we are rotating grids with the given R directly in our `Volume.rotate`.
 
Initially I tried slapping a volume in scipy and using  `geometric_transform` or `affine_transform` but was struggling to reproduce the result I thought should occur.  Those methods are a little complicated, so I went over to MATLAB where there is a simpler builtin.  I made a simple script creating a "nice" volume based off their doc example, then rotate around [7,8,9] by 123*.

Moving thosee input and output volumes to Python while accounting for F/C order looks to be confirming my suspicion.  To achieve correspondence I convert axis-angle to Rotation and invert.  This achieves the best norm and visually matches the three axis projections.

I still need to double check several things, but I'll plan to show this tomorrow if there is time in the dev meeting.

**Comment by garrettwrong** [comment]
Alright, discussed the `Volume.rotate` situation with Josh this morning.  He is going to correct and improve on the existing unit test and docs as a follow up to #1030 for `Volume.rotation`.  It might be possible to apply the same type of test to `project`.  We can discuss at the dev meeting.

**Comment by j-c-c** [comment]
Just adding some notes from our discussion. Below is a script that rotates a Volume with a single hotspot and checks that the hotspot is in the expected location after rotation. Note that the call to rotate uses `rot.invert()` implying that we need to invert the rotations used for volume rotation so that `Volume.rotate()` rotates the `Volume` within a fixed grid.

```
import numpy as np
from aspire.volume import Volume
from aspire.utils import Rotation

# Let's create a volume with a hotspot at (z, y, x) = (a, a, a)
L = 32
dtype = np.float32
vol_hot = np.zeros((L, L, L), dtype=dtype)
vol_hot[L // 2 + L//4, L // 2 + L//4, L // 2 + L//4] = 1
vol_hot = Volume(vol_hot)


# Generate a rotation about an axis (x, y, z) by d degrees
axis = (1, -5, 9)
d = 123
vec = np.array(axis, dtype=dtype)
vec /= np.linalg.norm(vec)
rot_vec = vec * d * np.pi / 180
rot = Rotation.from_rotvec(rot_vec, dtype=dtype)
rot_mat = rot.matrices


# Where does rot_mat send (a,a,a). Note, this point is in (x, y, z)
point = np.array((L // 4, L // 4, L // 4), dtype=dtype)
new_point = rot_mat @ point


# new_point in volume. Note, must flip the new point since volume is in (z, y, x)
vol_center = np.array((L // 2, L // 2, L // 2), dtype=dtype)
expected_location = new_point[:,::-1] + vol_center

# Rotate vol_hot by rot.T
rotated_vol = vol_hot.rotate(rot.invert())

# Check if the hot spot is in the new location
new_hot_spot = np.unravel_index(np.argmax(rotated_vol.asnumpy()[0]), (L, L ,L))
new_hot_spot, expected_location
```

Output: 
`((21, 14, 3), array([[20.731514, 13.944659,  3.13966 ]], dtype=float32))`

**Comment by j-c-c** [comment]
Covered by #1046. Closing.
