### ISSUE TITLE
`joblib` not listed in `environment.yml`

### ISSUE THREAD

**Issue by janden** [ComputationalCryoEM/ASPIRE-Python#95]
It's used in
https://github.com/ComputationalCryoEM/ASPIRE-Python/blob/d249781693e835db7ba8c387a4a0adbbbf09d01c/src/aspire/source/xform.py#L3
so we need to specify it as a dependency.

**Comment by vineetbansal** [comment]
fixed as part of PR #132. (added in requirements.txt)
