### ISSUE TITLE
Rename `basis_count` to `count` in `Basis` classes

### ISSUE THREAD

**Issue by janden** [ComputationalCryoEM/ASPIRE-Python#96]
Right now, we get redundancies like `basis.basis_count`. Having just `basis.count` would be more straightforward.

**Comment by junchaoxia** [comment]
You are right. There are also other variables need to refactor such as L, n in other classes.

**Comment by junchaoxia** [comment]
The basis_count was rename to count in commit 212efb5.

**Comment by janden** [comment]
> The basis_count was rename to count in commit [212efb5](https://github.com/ComputationalCryoEM/ASPIRE-Python/commit/212efb519ed92f5e80d76d993cb1ee11cd447bae).

Thanks.

> There are also other variables need to refactor such as L, n in other classes.

Ok. What do you suggest we rename those to?

**Comment by junchaoxia** [comment]
I am using nres for L or nimg for n in the DenoisorCov2D class. I think it is easier to guess what are them using the new variable for users.

**Comment by janden** [comment]
Ok. Yes we should use the same names everywhere, if we can. I think `L` and `n` are preferable here.
