### ISSUE TITLE
unit tests not running, M1 laptop installation

### ISSUE THREAD

**Issue by helenahu39** [ComputationalCryoEM/ASPIRE-Python#968]
I followed the installation instructions using an M1 laptop, but the unit tests are not running correctly. 

<img width="784" alt="image" src="https://github.com/ComputationalCryoEM/ASPIRE-Python/assets/110108401/28318e35-b649-43d0-a6b3-979fa8022396">

**Comment by garrettwrong** [comment]
Hi yes, some dependencies of ASPIRE appear to have problems with their ARM64 packages.  We are aware of the issue (#962 ), but I haven't had time to update it further yet.

You should have success using the x86_64 based conda install on your M1.  Several developers are currently running this configuration.

You can confirm if your conda is `x86_64` or `osx-arm64` by the platform line in the output of `conda info`.

**Comment by helenahu39** [comment]
Thanks for your help! I tried defining an x86 specific subdirectory by modifying the ~/.zshrc code. 
CONDA_SUBDIR=osx-64 conda create -n $@
 conda activate $1
Then, I ran the following terminal commands. 
cd Desktop/ASPIRE-Python
create_x86_conda_environment aspire_acc
conda activate aspire_acc
conda env update --file environment-accelerate.yml --name aspire_acc
pip install -e ".[dev]"
pytest
But I still got a segmentation fault.

**Comment by garrettwrong** [comment]
Hi, sorry to hear that, but I would not expect your sequence of commands to work as you intended.

We have four machines running x86_64 based conda on different M1 and M2 chips right now using our regular install process.  If you have nothing beholding you to an ARM based conda installation, I would suggest removing it (the entire ARM conda installation) and starting with a clean x86_64 miniconda installation. This has worked in all cases for us so far (we use everyday).

I suspect it is just one package causing issues with  `osx-arm`, but it will have to wait until I have time to debug an external project.  I will say supporting unoffocial conda workarounds for external dependencies is definitely out of scope for us.  If you truly must use conda's osx-arm platform, I can see about prioritizing this.  Let me know, thanks.

**Comment by helenahu39** [comment]
Would you recommend installing the Intel x86 64-bit Miniconda on an M1 machine? 

<img width="885" alt="image" src="https://github.com/ComputationalCryoEM/ASPIRE-Python/assets/110108401/80e13979-6c97-40ba-8221-cd96bff388c3">

**Comment by garrettwrong** [comment]
In this case yes, mac's rosetta will emulate x86_64.  

The problem you are having is with FFTW and pyfftw on `osx-arm` and outside the scope of ASPIRE support (though I will look into it).

**Comment by garrettwrong** [comment]
Hi again. I was able to build and locally install the latest releases of FFTW and PyFFTW from source targeting apple silicon. ASPIRE installs in an (osx-arm) conda environment after this, per the usual pip instructions, and all tests pass.  It is slightly slower on my M2 than using the emulated x86_64 (other software are not installed in an optimal way yet).

This involves specific versions, patching FFTW's configure code, multiple installation rounds, customizing your environment, and some luck.  I will update the associated issue (962) with some notes in the next day or so.  This approach won't be something we (ASPIRE) will be supporting directly though.  

The PyFFTW folks have been improving their support of this platform and I hope it will eventually be workable for us out of the box; until then, using the x86_64 conda platform is the best bet.

**Comment by helenahu39** [comment]
I tried again with x86_64, and it works much better now! Thank you!
1129 passed, 20 skipped, 321 deselected, 19 warnings in 783.09s (0:13:03)
Is this the expected result?

**Comment by garrettwrong** [comment]
More or less, yes, that install seems fine.  Good luck!
