### ISSUE TITLE
Input to apple picker

### ISSUE THREAD

**Issue by helenahu39** [ComputationalCryoEM/ASPIRE-Python#971]
Hello, for the apple particle picking function <centers, particles_img = apple_picker.process_micrograph(mrc_file_path, create_jpg=True)>, how can I take as input TIF files instead of MRC files? Thanks for your help!

**Comment by garrettwrong** [comment]
We currently don't support opening TIFF directly.  We've considered it, and it wouldn't be very difficult to do, but nobody has requested it until now.

You should be able to open them with an image library and expose the data as a numpy array. You can save the array of data to an mrc with the `mrcfile` package or ASPIRE's Image(<data_array>).save('filename.mrc).  Our save function is just wrapping `mrcfile`.

I'll add it to our issues after the holiday.

Hope that helps!

**Comment by garrettwrong** [comment]
HI @helenahu39 , I started a PR to add TIFF support.

Is there anyway you can provide a link to one of your target files so I can test it on an actual file? (not just one I've converted from TIFF to mrc).

Thanks

**Comment by garrettwrong** [comment]
Resulting feature has been merged. Closing
