### ISSUE TITLE
Broken merge in `s_em.py`

### ISSUE THREAD

**Issue by janden** [ComputationalCryoEM/ASPIRE-Python#98]
There are left over git merge tags in this file, for example here:
https://github.com/ComputationalCryoEM/ASPIRE-Python/blob/d249781693e835db7ba8c387a4a0adbbbf09d01c/src/aspire/aspire/em_classavg/s_em.py#L9
These need to be resolved in some way.

**Comment by junchaoxia** [comment]
This issue has been fixed in the commit 4cc8ecb.
