### ISSUE TITLE
Caching breaks `Simulation.clean_images`

### ISSUE THREAD

**Issue by garrettwrong** [ComputationalCryoEM/ASPIRE-Python#980]
Yields result of cached `images`.  This is a bug (but probably very minor code change).

Need to decide whether `cache` should store all variations (projections, clean_images, images), multiplying storage, or only the final result.

Its possible cache can take an argument...

**Comment by janden** [comment]
Could you elaborate on the bug here? If we call `cache`, what happens to `clean_images`?

**Comment by garrettwrong** [comment]
`clean_images` returns `images`.

**Comment by garrettwrong** [comment]
Here is a repro script:

```
from aspire.source import Simulation
from aspire.noise import WhiteNoiseAdder
from aspire.operators import RadialCTFFilter

ctf =  [RadialCTFFilter(pixel_size=5)]

src = Simulation(L=32,n=3,C=1, noise_adder=WhiteNoiseAdder(var=0.123), unique_filters=ctf)

# Expected
src.images[:].show()
src.clean_images[:].show()
src.projections[:].show()

# After `cache`
cached_src = src.cache()
cached_src.images[:].show()
cached_src.clean_images[:].show()  # == cached_src[:].images == src.images[:]
cached_src.projections[:].show()
```

At the time I think I glanced at the code and saw the problem, but the most direct/obvious way of resolving would duplicate the cache storage.  The real work here is deciding how we want to handle `projections` and `clean_images` wrt caching.

**Comment by janden** [comment]
My initial thinking here would be that we should not offer `projections` or `clean_images` from a cached source. If those are needed, the user can always go back to the original `Simulation`. Given the immutable source structure, that may be the most natural thing to do.
