### ISSUE TITLE
Remove `Volume.load` dtype FINNUFT workaround

### ISSUE THREAD

**Issue by j-c-c** [ComputationalCryoEM/ASPIRE-Python#985]
There is currently a workaround to the finnuft dtype bug in `Volume.load`:
https://github.com/ComputationalCryoEM/ASPIRE-Python/blob/a37d6eef7e5ddd65f7c9ee4be828bde1d914fbf7/src/aspire/volume/volume.py#L542-L546

This will need to be removed after the next finnuft release.

**Comment by garrettwrong** [comment]
Resolved by #1168
