### ISSUE TITLE
Handling of options in `conj_grad`

### ISSUE THREAD

**Issue by janden** [ComputationalCryoEM/ASPIRE-Python#99]
Currently, `conj_grad` crashes if `cg_opt` is not specified. A related issue is that we have to specify all the options to `cg_opt` if it *is* supplied. In other words, the default options are not filled in if missing.

The problem seems to be here:

https://github.com/ComputationalCryoEM/ASPIRE-Python/blob/d249781693e835db7ba8c387a4a0adbbbf09d01c/src/aspire/utils/optimize.py#L89

First, `fill_struct` is only called if `cg_opt` is `None`, which explains why default options are not filled in. Second, When `fill_struct` is called, it doesn't modify the given dictionary (it simply replaces it). Third, the output of `fill_struct` is an object with attributes, not a dictionary (cf. `cg_opt.store_iterates` vs. `cg_opt['store_iterates']`).

**Comment by junchaoxia** [comment]
This issue has been fixed in e678272.
