### ISSUE TITLE
Testing odd res projections are off

### ISSUE THREAD

**Issue by krissowat** [ComputationalCryoEM/ASPIRE-Python#990]
`test_project` in `tests/test_volume.py ` fails for testing projections when calling np.allclose
res = 43

```
>           assert np.allclose(vol_along_axis, prj_along_axis)
E           assert False
E            +  where False = <function allclose at 0x7fd0110e8ca0>(49317.5, 54432.273)
E            +    where <function allclose at 0x7fd0110e8ca0> = np.allclose
```

**Comment by garrettwrong** [comment]
Did we check if there was an issue relating to this already?

**Comment by krissowat** [comment]
I tried to find but couldn't, I might have skipped over it.

**Comment by garrettwrong** [comment]
Oh great, no worries, just checking. Its possible it just was a discussion in the past. Thanks for making the issue!

**Comment by garrettwrong** [comment]
I think the was resolved with some additional changes to the test. (Thanks @j-c-c ). Closing :).
