### ISSUE TITLE
Simulation 

### ISSUE THREAD

**Issue by zxt-triumph** [ComputationalCryoEM/ASPIRE-Python#993]
Why is Gen_volume_projection unable to save？
# Create a Simulation Source object
src = Simulation(
    vols=v,  # our Volume
    L=v.resolution,  # resolution, should match Volume
    n=n_img,  # number of projection images
    angles=rots.angles,  # pass our rotations as Euler angles
    offsets=shifts,  # translations (wrt to origin)
    amplitudes=amplitudes,  # amplification ( 1 is identity)
    seed=12345,  # RNG seed for reproducibility
    dtype=v.dtype,  # match our datatype to the Volume.
    noise_adder=white_noise_adder,  # optionally prescribe noise
)

src.images[:3].show()
src.projections[:3].show()

# Here we return the first n_img images as a numpy array.
dirty_ary = src.images[:n_img].asnumpy()

# And we have access to the clean images
clean_ary = src.projections[:n_img].asnumpy()
imageio.imwrite('./1.bmp', clean_ary[0])

Error in sys.excepthook:
Traceback (most recent call last):
  File "/home/dell/anaconda3/envs/aspire/lib/python3.8/site-packages/PIL/BmpImagePlugin.py", line 389, in _save
    rawmode, bits, colors = SAVE[im.mode]
KeyError: 'F'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/dell/zxt/Code/ASPIRE-Python/src/aspire/exceptions.py", line 87, in handle_exception
    raise exc_value
  File "gen_pro_single.py", line 72, in <module>
    imageio.imwrite('./1.bmp', clean_ary[0])
  File "/home/dell/anaconda3/envs/aspire/lib/python3.8/site-packages/imageio/v2.py", line 397, in imwrite
    return file.write(im, **kwargs)
  File "/home/dell/anaconda3/envs/aspire/lib/python3.8/site-packages/imageio/core/v3_plugin_api.py", line 367, in __exit__
    self.close()
  File "/home/dell/anaconda3/envs/aspire/lib/python3.8/site-packages/imageio/plugins/pillow.py", line 123, in close
    self._flush_writer()
  File "/home/dell/anaconda3/envs/aspire/lib/python3.8/site-packages/imageio/plugins/pillow.py", line 457, in _flush_writer
    primary_image.save(self._request.get_file(), **self.save_args)
  File "/home/dell/anaconda3/envs/aspire/lib/python3.8/site-packages/PIL/Image.py", line 2413, in save
    save_handler(self, fp, filename)
  File "/home/dell/anaconda3/envs/aspire/lib/python3.8/site-packages/PIL/BmpImagePlugin.py", line 392, in _save
    raise OSError(msg) from e
OSError: cannot write mode F as BMP

Original exception was:
Traceback (most recent call last):
  File "/home/dell/anaconda3/envs/aspire/lib/python3.8/site-packages/PIL/BmpImagePlugin.py", line 389, in _save
    rawmode, bits, colors = SAVE[im.mode]
KeyError: 'F'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/dell/zxt/Code/ASPIRE-Python/src/aspire/exceptions.py", line 87, in handle_exception
    raise exc_value
  File "gen_pro_single.py", line 72, in <module>
    imageio.imwrite('./1.bmp', clean_ary[0])
  File "/home/dell/anaconda3/envs/aspire/lib/python3.8/site-packages/imageio/v2.py", line 397, in imwrite
    return file.write(im, **kwargs)
  File "/home/dell/anaconda3/envs/aspire/lib/python3.8/site-packages/imageio/core/v3_plugin_api.py", line 367, in __exit__
    self.close()
  File "/home/dell/anaconda3/envs/aspire/lib/python3.8/site-packages/imageio/plugins/pillow.py", line 123, in close
    self._flush_writer()
  File "/home/dell/anaconda3/envs/aspire/lib/python3.8/site-packages/imageio/plugins/pillow.py", line 457, in _flush_writer
    primary_image.save(self._request.get_file(), **self.save_args)
  File "/home/dell/anaconda3/envs/aspire/lib/python3.8/site-packages/PIL/Image.py", line 2413, in save
    save_handler(self, fp, filename)
  File "/home/dell/anaconda3/envs/aspire/lib/python3.8/site-packages/PIL/BmpImagePlugin.py", line 392, in _save
    raise OSError(msg) from e
OSError: cannot write mode F as BMP

**Comment by zxt-triumph** [comment]
pip freeze:
aiosignal==1.3.1
alabaster==0.7.13
anyio==3.7.1
argon2-cffi==21.3.0
argon2-cffi-bindings==21.2.0
arrow==1.2.3
# Editable install with no version control (aspire==0.11.1)
-e /home/dell/zxt/Code/ASPIRE-Python/src
asttokens==2.2.1
async-lru==2.0.4
attrs==23.1.0
Babel==2.12.1
backcall==0.2.0
beautifulsoup4==4.12.2
black==23.7.0
bleach==6.0.0
build==0.10.0
bump2version==1.0.1
bumpversion==0.6.0
cachetools==5.3.1
certifi==2023.7.22
cffi==1.15.1
chardet==5.2.0
charset-normalizer==3.2.0
check-manifest==0.49
click==8.1.6
colorama==0.4.6
comm==0.1.4
confuse==2.0.1
contourpy==1.1.0
coverage==7.2.7
cryptography==41.0.3
cycler==0.11.0
debugpy==1.6.7.post1
decorator==5.1.1
defusedxml==0.7.1
distlib==0.3.7
docutils==0.18.1
exceptiongroup==1.1.2
execnet==2.0.2
executing==1.2.0
fastjsonschema==2.18.0
filelock==3.12.2
finufft==2.1.0
flake8==6.1.0
fonttools==4.42.0
fqdn==1.5.1
frozenlist==1.4.0
gemmi==0.6.2
grpcio==1.48.2
idna==3.4
imagecodecs @ file:///home/conda/feedstock_root/build_artifacts/imagecodecs_1679699544550/work
imageio @ file:///home/conda/feedstock_root/build_artifacts/imageio_1686552404404/work
imagesize==1.4.1
importlib-metadata==6.8.0
importlib-resources==6.0.1
iniconfig==2.0.0
ipykernel==6.25.1
ipython==8.12.2
ipython-genutils==0.2.0
ipywidgets==8.1.0
isoduration==20.11.0
isort==5.12.0
jaraco.classes==3.3.0
jedi==0.19.0
jeepney==0.8.0
Jinja2==3.1.2
joblib @ file:///home/conda/feedstock_root/build_artifacts/joblib_1688155275339/work
json5==0.9.14
jsonpointer==2.4
jsonschema==4.19.0
jsonschema-specifications==2023.7.1
jupyter==1.0.0
jupyter-console==6.6.3
jupyter-events==0.7.0
jupyter-lsp==2.2.0
jupyter_client==8.3.0
jupyter_core==5.3.1
jupyter_server==2.7.0
jupyter_server_terminals==0.4.4
jupyterlab==4.0.4
jupyterlab-pygments==0.2.2
jupyterlab-widgets==3.0.8
jupyterlab_server==2.24.0
keyring==24.2.0
kiwisolver==1.4.4
latexcodec==2.0.1
lazy_loader @ file:///home/conda/feedstock_root/build_artifacts/lazy_loader_1679784563552/work
markdown-it-py==3.0.0
MarkupSafe==2.1.3
matplotlib==3.7.2
matplotlib-inline==0.1.6
mccabe==0.7.0
mdurl==0.1.2
mistune==3.0.1
more-itertools==10.1.0
mrcfile==1.4.3
msgpack==1.0.5
mypy-extensions==1.0.0
nbclient==0.8.0
nbconvert==7.7.3
nbformat==5.9.2
nest-asyncio==1.5.7
networkx @ file:///home/conda/feedstock_root/build_artifacts/networkx_1680692919326/work
notebook==7.0.2
notebook_shim==0.2.3
numpy @ file:///home/conda/feedstock_root/build_artifacts/numpy_1668919078398/work
overrides==7.4.0
packaging @ file:///home/conda/feedstock_root/build_artifacts/packaging_1681337016113/work
pandocfilters==1.5.0
parameterized==0.9.0
parso==0.8.3
pathspec==0.11.2
pexpect==4.8.0
pickleshare==0.7.5
Pillow @ file:///home/conda/feedstock_root/build_artifacts/pillow_1688255848672/work
pkginfo==1.9.6
pkgutil_resolve_name==1.3.10
platformdirs==3.10.0
pluggy==1.2.0
prometheus-client==0.17.1
prompt-toolkit==3.0.39
protobuf==4.24.0
psutil==5.9.5
ptyprocess==0.7.0
pure-eval==0.2.2
pybtex==0.24.0
pybtex-docutils==1.0.2
pycodestyle==2.11.0
pycparser==2.21
pydocstyle==6.3.0
pyFFTW @ file:///home/conda/feedstock_root/build_artifacts/pyfftw_1636045121627/work
pyflakes==3.1.0
Pygments==2.16.1
pyparsing==3.0.9
pyproject-api==1.5.3
pyproject_hooks==1.0.0
pytest==7.4.0
pytest-cov==4.1.0
pytest-random-order==1.1.0
pytest-xdist==3.3.1
python-dateutil==2.8.2
python-json-logger==2.0.7
pytz==2023.3
PyWavelets @ file:///home/conda/feedstock_root/build_artifacts/pywavelets_1673082342303/work
PyYAML==6.0.1
pyzmq==25.1.0
qtconsole==5.4.3
QtPy==2.3.1
ray==2.6.2
readme-renderer==40.0
referencing==0.30.2
requests==2.31.0
requests-toolbelt==1.0.0
rfc3339-validator==0.1.4
rfc3986==2.0.0
rfc3986-validator==0.1.1
rich==13.5.2
rpds-py==0.9.2
scikit-image @ file:///home/conda/feedstock_root/build_artifacts/scikit-image_1688804534879/work/dist/scikit_image-0.21.0-cp38-cp38-linux_x86_64.whl#sha256=07534b01a4164c5bfe7b16daacd4d2c22e54d53e63caeede0072b2b0f6a438a0
scikit-learn @ file:///home/conda/feedstock_root/build_artifacts/scikit-learn_1688116515735/work
scipy==1.9.3
SecretStorage==3.3.3
Send2Trash==1.8.2
six==1.16.0
snakeviz==2.2.0
sniffio==1.3.0
snowballstemmer==2.2.0
soupsieve==2.4.1
Sphinx==6.2.1
sphinx-gallery==0.13.0
sphinx-rtd-theme==1.2.2
sphinxcontrib-applehelp==1.0.4
sphinxcontrib-bibtex==2.5.0
sphinxcontrib-devhelp==1.0.2
sphinxcontrib-htmlhelp==2.0.1
sphinxcontrib-jquery==4.1
sphinxcontrib-jsmath==1.0.1
sphinxcontrib-mermaid==0.9.2
sphinxcontrib-qthelp==1.0.3
sphinxcontrib-serializinghtml==1.1.5
stack-data==0.6.2
terminado==0.17.1
threadpoolctl @ file:///home/conda/feedstock_root/build_artifacts/threadpoolctl_1689261241048/work
tifffile @ file:///home/conda/feedstock_root/build_artifacts/tifffile_1689063654925/work
tinycss2==1.2.1
tomli==2.0.1
tornado==6.3.2
tox==4.7.0
tqdm==4.65.2
traitlets==5.9.0
twine==4.0.2
typing_extensions==4.7.1
uri-template==1.3.0
urllib3==2.0.4
virtualenv==20.24.2
wcwidth==0.2.6
webcolors==1.13
webencodings==0.5.1
websocket-client==1.6.1
widgetsnbextension==4.0.8
zipp==3.16.2

**Comment by j-c-c** [comment]
> Why is Gen_volume_projection unable to save？

It appears you are attempting to save a numpy array of floating point values (`clean_ary[0]`) as a bitmap, which only accepts `ints`. 

If you are just attempting to save the data I would recommend using `numpy.save()`. If you would like to save the data as an image you will have to either try a different file format or you could use our built-in for saving ASPIRE `Image` objects. Something like:

```
src.projections[0].save("clean_image.mrc")
```

**Comment by zxt-triumph** [comment]
The previous ASPIRE environment can use Imageio to save the BMP format image. But after re -installation of ASPIRE, it will be abnormal.

**Comment by j-c-c** [comment]
@zxt-triumph Were you able to save this same array in the BMP format? 

There should be no problem using Imageio to save in the BMP format as long as your data is in the correct format, ie. integer values in the range [0, 255].

If you first normalize the data to be in the correct range and then convert to a BMP accepted dtype you will have no problem saving this image:

```
>>> clean_ary = (clean_ary - np.min(clean_ary)) / (np.max(clean_ary) - np.min(clean_ary)) * 255
>>> np.min(clean_ary)
0.0
>>> np.max(clean_ary)
255.0
>>> clean_ary = clean_ary.astype(np.uint8)
>>> import imageio
>>> imageio.imwrite('clean_image.bmp', clean_ary[0])
>>>
```

**Comment by zxt-triumph** [comment]
Thank you for your reply and answer.
